### ISSUE TITLE
MSSQL result sets failing due to early commit

### ISSUE THREAD

**Issue by patrickmdnet** [webpy/webpy#119]
OS is Ubuntu Linux LTS 10.04.  
Arch is x86_64
FreeTDS is version 0.82-7 (from the Ubuntu Lucid repo)
pymssql-2.0.0b1_dev_20111019-py2.6-linux-x86_64
MS SQL Server is version 8.0 SP4 (SQL Server 2000).  

Freetds.conf looks like this:
    [global]
    tds version = 8.0
    text size   = 64512

This code fails to return any results:

```
import web

mssql_conn = web.database(dbn='mssql', ....)
out = mssql_conn.select("select uid from dbo.sysusers")
print(out.list())
```

but this code works:

```
trans = mssql_conn.transaction()
out = mssql_conn.select("select uid from dbo.sysusers")
print(out.list())
trans.commit()
```

The issue is that the DB.query() method (in db.py) performs a commit() at the end of the method.  This destroys the result cursor.  The workaround is to create a transaction object, dump the result cursor into a list, and then do the commit().

It's not clear to me what the best way is to work around this in db.py.

**Comment by DiJu519** [comment]
Just wanted to say thanks.

I didn't end up using the trans.commit however.

When using mssql, i find this workflow is fine:


> db = web.database(dbn='mssql',.................")
> class index:
 >   def GET(self):
>		trans = db.transaction()
>		persons = db.select("Persons")
>		return render.index(persons)
