### ISSUE TITLE
Make sessions work transparently with debugging enabled

### ISSUE THREAD

**Issue by despens** [webpy/webpy#156]
There is a cookbook example on how to make sessions work with debugging enabled: http://webpy.org/cookbook/session_with_reloader

Debugging is quite useless if debugging of session related code is not possible, so this fix is really a copypaste boilerplate for every webpy project. This is not nice.

Instead, this fix should be part of core webpy.

**Comment by iredmail** [comment]
No plan for this change recently, feel free to reopen this issue if necessary.
