### ISSUE TITLE
Lose session data (webpy 0.36-2 + mod_wsgi 3.3)

### ISSUE THREAD

**Issue by upmauro** [webpy/webpy#157]
I use Apache 2.2 + Python 2.7.3 + mod_wsgi 3.3.

Lose session data in random request. 

Simple code application for simulate :

http://dpaste.com/756381/

**Comment by iredmail** [comment]
Do you guys still have this issue? @upmauro @milsosa 

- Please try again with the latest git version of web.py.
- Link in first post is gone.
- Missing code snippet to reproduce the issue.
