### ISSUE TITLE
internal errors not handled properly for chunked encoding pages

### ISSUE THREAD

**Issue by scyclops** [webpy/webpy#166]
In application.py, the wsgi function on line 269 does special handling when handle_with_processors() returns a generator (for pages using chunked encoding).   The peep'ing on the results of these generators may raise exceptions due to bugs in user code to generate responses.  When there are exceptions raised here, they aren't handled by internalerror which causes end users to see plain text Python stack traces in their browser.

The below class is a simple test case that should trigger this problem:

``` python
class Test(object):
  def GET(self):
    a = 1/0
    yield ''
```

To fix this problem, I moved the peep'ing on the generator into the process function within the handle_with_processors method (line 232) so that any exceptions are properly caught and handled by the call to internalerror there.

**Comment by iredmail** [comment]
hi @scyclops 

Is this still an issue with web.py-0.39 or the latest git version?

**Comment by scyclops** [comment]
I just tried using the web.py==0.40.dev1 with python3.7 and I can't even run my test case or the example code from the top right of the web.py homepage.  I get the following exception:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "default.py", line 7, in <module>
    app = web.application(urls, globals())
  File "/home/user/.local/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/home/user/.local/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/home/user/.local/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration
```

**Comment by iredmail** [comment]
Could you try the latest git version of web.py? There’re many py3 related fixes.

**Comment by scyclops** [comment]
Okay, this bug doesn't seem to happen in the latest git version.  It does still happen with web.py-0.39.

**Comment by iredmail** [comment]
Thanks for the feedback. And sorry about the laaaaaaaattttttttttteeeeeee response.
