### ISSUE TITLE
Less than clear error message when python-openid is not installed

### ISSUE THREAD

**Issue by WoLpH** [webpy/webpy#169]
Trying from a brand new virtualenv I get this error when I execute the code from #168:

``` python
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from web import webopenid
  File "/home/rick/envs/webpy/lib/python2.6/site-packages/web/webopenid.py", line 26, in <module>
    import openid.consumer.consumer
ImportError: No module named openid.consumer.consumer

shell returned 1
```

Although the error is expected, the message is a bit unclear. Would be nice to catch this ImportError and replace it with something clearer like "Please install `python-openid`"

**Comment by VJalili** [comment]
I'm getting a very same error. I solved running the following, but not sure if its a "correct" solution. 

    pip install python-openid

**Comment by iredmail** [comment]
Package name maybe different on different Linux/BSD distributions, you have to figure out the correct package name based on the "ImportError" message. Sorry about this.
