### ISSUE TITLE
Why Chinese garbled when use webpy but it's normal for MySQLdb?

### ISSUE THREAD

**Issue by easongit** [webpy/webpy#189]
I create a database in mysql and use webpy to construct my web server.

But it's so strange for Chinese character between the webpy's and MySQLdb's behaviors when using them to access database respectively.

Below is my problem:

My table t_test (utf8 databse):

```
 id     name
 1      测试
```

the utf8 code for "测试" is: \xe6\xb5\x8b\xe8\xaf\x95

when using MySQLdb to do "select" like this:

```
c=conn.cursor()
c.execute("SELECT * FROM t_test")
items = c.fetchall()
c.close()
print "items=%s, name=%s"%(eval_items, eval_items[1])
```

the result is normal, it prints:

```
items=(127L, '\xe6\xb5\x8b\xe8\xaf\x95'), name=测试
```

But when I use webpy do the same things:

```
db = web.database(dbn='mysql', host="127.0.0.1", 
         user='test', pw='test', db='db_test', charset="utf8")
eval_items=db.select('t_test')
comment=eval_items[0].comment
print "comment code=%s"%repr(comment)
print "comment=%s"%comment.encode("utf8")
```

Chinese garble occured, the print result is:

```
comment code=u'\xe6\xb5\u2039\xe8\xaf\u2022'
comment=忙碌鈥姑€
```

I know webpy's database is also dependent on MySQLdb， but it's so different for these two way. Why?

BTW, for the reason above, I can just use MySQLdb directly to solve my Chinese character garble problem, but it loses the clolumn name in table——It's so ungraceful. I want to know how can I solve it with webpy?

**Comment by bpluly** [comment]
You may be suffering from a mismatch of encoding. utf-8 character set in MySQL is 3 bytes unless (5.5.3 & later), the character set utf8mbr is used which is 4 bytes. Usually its stated that the 3 byte BMP sequences are the same glyphs as 4 byte sequences (see: https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html), but it looks like there's a difference between the Mysql driver that web.py uses compared to the official Mysql driver.

I would try with a single table in a new MySQL db with the character set utf8mbr and see if you get better results. If that works you'll have to dump and reload the database to get the utf-8 4 byte encoding.

**Comment by anandology** [comment]
@easongit is this still an issue? IIRC, web.py assumes that the database encoding is UTF-8. If there is a mismatch, that might create some trouble.

**Comment by bpluly** [comment]
MySQL can now support utf84b as well as utf83b but it has to be selected
for the database.

https://dev.mysql.com/doc/refman/5.7/en/charset-unicode.html

S
