### ISSUE TITLE
Base template $if content.somevar does not work as documented

### ISSUE THREAD

**Issue by drjayvee** [webpy/webpy#199]
According to the cook book, a [site layout template](http://webpy.org/cookbook/layout_template) can use `$if content.somevar`.

However, I get

```
<type 'exceptions.AttributeError'> at /
'somevar'
```

I've tried this suggestion from a (rather old) [Google Groups post](https://groups.google.com/d/msg/webpy/cKS8rNNV0j0/_9zcXBjviiYJ):

```
$if hasattr(content, 'somevar')
```

But that results in

```
<type 'exceptions.NameError'> at /
global name 'hasattr' is not defined
```

I thought this might be a problem with [security](http://webpy.org/docs/0.3/templetor#security), but the doc says a `SecurityException` should be thrown in that case. If I change the code to use `getattr` (which is explicitly mentioned as forbidden in the docs), I get the same error (does that mean that the docs are off, and no SecurityException is thrown?).

Now, as a workaround, you can of course write `$var somevar:` in the page template, but that completely defeats the purpose of `$if content.somevar` in the base template, as you could just print `$content.somevar` if it's never unset.

By the way:

```
>>> import web
>>> web.__version__
'0.37'
```

**Comment by iredmail** [comment]
`hasattr` is not a bulitin function for templator, you need to pass it while defining the templator `render` like this:

```
render = web.template.render(
    "templates",
    base='layout',
    globals={
        'hasattr': hasattr,
        ...
    },
)
```
