### ISSUE TITLE
All POST Responses Fail

### ISSUE THREAD

**Issue by dsull** [webpy/webpy#202]
I want my web.py to do something in response to a POST request. At first, I tried having it do a web.seeother(). This wasn't working. My troubleshooting is detailed here:

http://stackoverflow.com/questions/14024855/http-303-seeother-get-works-post-fails

This led me to discover that all replies to POST requests are failing, so it has nothing to do with web.seeother(). Again, my troubles are detailed here:

http://stackoverflow.com/questions/14132343/http-post-response-fails-using-web-py

The gist is that the server replies nearly instantly, but the response is somehow garbled, and thus the browsers take a long time to decipher the response (if they're able to decipher it at all).

I'm at a complete loss as to how to fix this issue or even how to further troubleshoot.

**Comment by iredmail** [comment]
- No sample code snippet.
- Sample code snippet in second stackoverflow link works fine, so consider it as not a bug.
