### ISSUE TITLE
Templator setting wrong Content-Type header

### ISSUE THREAD

**Issue by vwochnik** [webpy/webpy#216]
Hello

Situation:
POST request for user signup
- insert user
- load user verification email template (.txt)
- sending mail
- load "thank you" page

Problem:
Page rendered in text/plain

Cause:
Templator setting Content-Type to text/plain, because .txt template is rendered first.

Workaround:
changing extension to e.g. .tpl

Solution:
Add an option to disable setting Content-Type headers.

**Comment by iredmail** [comment]
No plan for this. sorry.
