### ISSUE TITLE
How to catch internalerrors in middleware?

### ISSUE THREAD

**Issue by idbentley** [webpy/webpy#219]
I'm trying to use a middleware to catch application exceptions as suggested here:
http://webpy.org/cookbook/logging

I can't seem to get it to work, however, because web py doesn't actually raise exceptions on internalservererrors.  This was asked about in the google group a long time ago:

https://groups.google.com/forum/?fromgroups=#!topic/webpy/Wd63MK6cX64

I attempted to make a simpler version of wsgilog that is based off of their implementation (but works with my apps use of `logging`, but my `__call__` function never receives any exceptions.

```
import sys
import logging
_logger = logging.getLogger(__name__)

def _errapp(environ, start_response):
      """
      Default error handling WSGI application.
      """
      start_response("500 Internal Error", [('Content-type', 'text/plain')], sys.exc_info())
      return ["Server got itself into trouble"]

class LogMiddleware(object):

      """
      To support web application exception logging, this middleware
      specifies some intelligent defaults for handling exceptions within
      web.py applications
      """

      def __init__(self, application):
          self.application = application

      def __call__(self, environ, start_response):
          print 'hrm'
          try:
              return self.application(environ, start_response)
          except Exception as e:
              _logger.exception(e)
              return _errapp(environ, start_response)
```

web.py 0.3.7 with python 2.6

**Comment by iredmail** [comment]
No plan to fix it recently. Feel free to reopen this issue if it's required.
