### ISSUE TITLE
Fixes non-functional SSL support in built-in cherryPy server

### ISSUE THREAD

**Issue by Nmishin** [webpy/webpy#225]
Hello!
I'm using Centos release 6.4 (Final) 2.6.32-358.2.1.el6.x86_64 and python.x86_64 2.6.6-36.el6 .
When I try to run my script and use SSL in it, I get an error:

Traceback (most recent call last):
File "/usr/local/vm_manage/vm_manage.py", line 279, in <module>
app.run()
File "/usr/lib/python2.6/site-packages/web/application.py", line 313, in run
return wsgi.runwsgi(self.wsgifunc(*middleware))
File "/usr/lib/python2.6/site-packages/web/wsgi.py", line 54, in runwsgi
return httpserver.runsimple(func, validip(listget(sys.argv, 1, '')))
File "/usr/lib/python2.6/site-packages/web/httpserver.py", line 149, in runsimple
server = WSGIServer(server_address, func)
File "/usr/lib/python2.6/site-packages/web/httpserver.py", line 200, in WSGIServer
server.ssl_adapter = create_ssl_adapter(server.ssl_certificate, server.ssl_private_key)
File "/usr/lib/python2.6/site-packages/web/httpserver.py", line 187, in create_ssl_adapter
from wsgiserver.ssl_pyopenssl import pyOpenSSLAdapter
ImportError: No module named ssl_pyopenssl 

I adjusted the code here, and it worked  (vi httpserver.py ++187).

```
def create_ssl_adapter(cert, key):
    # wsgiserver tries to import submodules as cherrypy.wsgiserver.foo.
    # That doesn't work as not it is web.wsgiserver.
    # Patching sys.modules temporarily to make it work.
    #import types
    #cherrypy = types.ModuleType('cherrypy')
    #cherrypy.wsgiserver = wsgiserver
    #sys.modules['cherrypy'] = cherrypy
    #sys.modules['cherrypy.wsgiserver'] = wsgiserver

    from cherrypy.wsgiserver.ssl_pyopenssl import pyOpenSSLAdapter
    adapter = pyOpenSSLAdapter(cert, key)

    # We are done with our work. Cleanup the patches.
    #del sys.modules['cherrypy']
    #del sys.modules['cherrypy.wsgiserver']

    return adapter
```

What should I do with this?
That's right, I wrote it here?
Thank you!

**Comment by iredmail** [comment]
Won't fix according to the discussion in #110.
