### ISSUE TITLE
Improve web.input() to return a multidict

### ISSUE THREAD

**Issue by idbentley** [webpy/webpy#226]
Web.py's web.input() method leaves some things to be desired compared to other modern web frameworks:
- web.input() returns a dict, instead of a multidict
  - querystrings, and postdata both allow keys to have multiple values.
  - advanced form libraries (like wtforms) expect multidicts instead of dicts, so hacks are required to work with these libraries.
- web.input() requires us to hint with kwargs at which keys are arrays.  This should be automatic

**Comment by iredmail** [comment]
No plan to fix it. Feel free to reopen this issue if it's required.
