### ISSUE TITLE
Wrong Documentation

### ISSUE THREAD

**Issue by zferentz** [webpy/webpy#234]
In the "home -> Serving Images" section I believe that there are multiple code-typo when specifying the Content-Type header : the content  type should include "image" and not "images".

images/png -> image/png
images/jpb -> image/jpg
...

Of course, in a production code i would also replace "cType[ext]" with "cType[ext.lower()]" and deal with KeyErrors... (other image type...)

Good luck !!

**Comment by iredmail** [comment]
Fixed in https://github.com/webpy/webpy.github.com/commit/67b3298a6a9b34de13fbf9b85f75fe10a7676ec1.
