### ISSUE TITLE
Error with unicode and web.db.sqlquote

### ISSUE THREAD

**Issue by odinjv** [webpy/webpy#236]
I was working on a search system that needed to process some unicode strings, and I chose to use sqlquote to add the quotes. The search failed to bring anything back and I noticed that when the test value used was "test_á" in the query the value appeared as "test_\xc3\xa1" which didn't match on the MySQL database.

After tracking down the error, I found this sentence in db.py in line 334 :
if isinstance(obj, unicode): obj = obj.encode('utf8')
return repr(obj)

This appear to transform the string "test_á" into "test_\xc3\xa1" that is not recognized by MySQL as the same string.

**Comment by iredmail** [comment]
Is this still an issue?
