### ISSUE TITLE
No regex pattern matching when delegating to sub applications

### ISSUE THREAD

**Issue by Larpon** [webpy/webpy#267]
I think there might be an undesirable feature in the way paths are matched in the code that decides if a path should be delegated to a sub application.

The value is matched with ".startswith(pat)" which causes the delegation to choose the first sub application that handles a path similar to other sub application registered paths .

An example:
sub_app1 handles "/theme"
sub_app2 handles "/themes"

when I request "/themes" in my browser it's sub_app1's code that will handle it because  .startswith(pat) will match "/theme" before "/themes" - thus giving me an undesired result.

**Comment by iredmail** [comment]
You should move the pattern which matches `/themes` before `/theme`. This is not an web.py issue, but the regular expression "issue".

**Comment by Larpon** [comment]
Thanks for answering a 6 year old issue. Now I can finally get on with my project!
