### ISSUE TITLE
add "cookie path" to documentation (or solve bug?)

### ISSUE THREAD

**Issue by shula** [webpy/webpy#282]
i had a different behavior between using apache and web.py's own server - 
i strongly suggest mentioning it in the docs, so users would consider using the cookie path in such occasions:
- http://webpy.org/cookbook/sessions

The problem:
For the same website code, the cookies were NOT set in Apache. Maybe because i had in apache a rewrite rule:

RedirectMatch  ^/$ /static/
RewriteRule ^something/(.*)$ some-dir/webpy.py/something/$1

Solution:
i gave the cookie path "/", it was ok.

here are the details:

http://stackoverflow.com/questions/22076781/web-py-sessions-renew-every-reload-under-apache-cgi-wsgi/22092817?noredirect=1#22092817

**Comment by iredmail** [comment]
Document updated: https://github.com/webpy/webpy.github.com/commit/e16085afaf19068e50939fcad6dd99c971c54289
