### ISSUE TITLE
webpy use hotshot for profiling which has bugs that python core dev "won't fix"

### ISSUE THREAD

**Issue by LBdN** [webpy/webpy#294]
Hotshot is deprecated and the python core dev don't considers its bugs important.

Among them, one is quite common : crash when a profiled function returns via en Exception.
see http://bugs.python.org/issue900092

It makes the web.http.profiler unusable. 
And replacing hotshot by the current profiler is the only solution I can think off.

**Comment by iredmail** [comment]
No hotshot in latest git version of web.py. Issue closed.
