### ISSUE TITLE
Web.py seems to leak sockets when receiving a particular request, eventually resulting in silent death of python process

### ISSUE THREAD

**Issue by larsendt** [webpy/webpy#301]
I have a small scale web service running on a Linode vps. It's a bog-standard web.py app running behind nginx using fcgi for communication. I have an arduino making very simple requests to the web server (once every 30 seconds), which then logs the request to a database and optionally sends an email. It also will serve a basic web page with the latest status.

The request from the arduino looks like this:

```
GET /update?north=1&west=1&front=1 HTTP/1.1
Host: wellmonitor.larsendt.com
Connection: close
```

Right after I brought the web service up and got things working, I noticed that the web service would crash after about 8.5 hours. No exceptions thrown, no errors logged, the process would just silently die. 

At first I figured it was a memory leak or something, so I started logging that, but the process only got up to 50 MB or so before dying. 

I also did a stress test with a script just spamming the server with bog-standard HTTP requests, but the server did not exhibit the problem. It only seems to be an issue with the above request from the arduino.

Anyway, I did a little digging and discovered (thanks to lsof), that after about an hour of operation, this was happening (30008 is the pid of the primary web.py process):

```
$ lsof | grep 30008 | grep sock
... # lots of lines elided
python    30008 30013       dane   62u     sock                0,6      0t0 11023667 can't identify protocol
...
$ lsof | grep 30008 | grep sock | wc -l
5328
```

The number of sockets keeps growing until (I assume) the process hits some limit and dies silently. 

I'm running Python 2.7.6 with web.py 0.37 on Ubuntu 14.04. I can make the problem appear on any running web.py service (not just the one dedicated to the arduino) by making the HTTP request shown above. 

If there's any other debugging info you need from me, don't hesitate to let me know.

Thanks,
Dane Larsen

**Comment by anandology** [comment]
I noticed this issue somewhere else too. Apparently the issue doesn't happend with lighttpd+fastcgi, but happens with nginx+fastcgi. 

The following patch seems to have fixed the issue.
<pre>
$ git diff web/wsgi.py
diff --git a/web/wsgi.py b/web/wsgi.py
index abea923..f87df86 100644
--- a/web/wsgi.py
+++ b/web/wsgi.py
@@ -14,7 +14,7 @@ import httpserver
 def runfcgi(func, addr=('localhost', 8000)):
     """Runs a WSGI function as a FastCGI server."""
     import flup.server.fcgi as flups
-    return flups.WSGIServer(func, multiplexed=True, bindAddress=addr, debug=False).run()
+    return flups.WSGIServer(func, multiplexed=False, bindAddress=addr, debug=False).run()

 def runscgi(func, addr=('localhost', 4000)):
     """Runs a WSGI function as an SCGI server."""
</pre>

Ideally, there should be an easier way to disable multiplexed. 

Could you please try this and let me know if it helps?
