### ISSUE TITLE
How can I use on layout in each page which located at their own folder? :-)

### ISSUE THREAD

**Issue by Quanjiang** [webpy/webpy#305]
I try to create the MVC model in my own project. So I need put all temples file into one folder named "view". Question is how can I tell web.py the static folder is renamed "view".

As you know, I need put all module only use one layout file which located at view folder. But each module has it's own folder in view folder for contian all of it temples file like "pp.html admin.html ..." When I try to use this code :
render = web.template.render('static/pluge-in/ReportFish',base='../../layout')
There are some resource file in layout who call them. When I use this method , I find that the page can't load resource file in layout in right way. It looks like put the layout file in it current folder where the resource file is not in there where I need them be.

So could any body help me for giving me some adviced about this problem?

By the way, I need write the web with demand auto run some script writed by python with timer. I need manager many different demand ( with different cycle timer ) in a moudle. How can I design this module ? Could someone have a good idear ? 

Thanks for all of your help & advice ~

Have a good day ~

**Comment by iredmail** [comment]
Better use Jinja2 template engine instead: http://webpy.org/cookbook/template_jinja
