### ISSUE TITLE
Custom HTTP headers without X- prefix are stripped

### ISSUE THREAD

**Issue by thelvey** [webpy/webpy#306]
Historically, the `X-` prefix was (and still) used for custom headers. This has been considered deprecated as best practice in [RFC 6648](http://tools.ietf.org/html/rfc6648/).

I'd like to see custom headers without the prefix maintained (while maintaining backwards compatibility with existing use of the prefix).

I ran across this when implementing an OAuth2 provider within web.py.

The OAuth2 spec uses `Authorization: Bearer token-here` which will may not be used in webpy unless it is changed to `X-Authorization: Bearer token-here` (and breaking OAuth2 spec).

**Comment by anandology** [comment]
I'm able to see `HTTP_X_AUTHORIZATION` and `HTTP_AUTHORIZATION` in `web.ctx.environ`. Are you not able to see them?
