### ISSUE TITLE
Website Docs page truncated !!

### ISSUE THREAD

**Issue by JTURKI** [webpy/webpy#307]
Hello,

The web page "http://webpy.org/docs/0.3/api" is truncated at "class Template(self, text, filename='" .

So, can't reach later sections like (web.webopenid) 
However, viewing the source code, the HTML content is there. The problems seems to be caused by the template Tag just after (see html).

Regards

**Comment by pbuckner** [comment]
+1

**Comment by benyassine** [comment]
+1

**Comment by JTURKI** [comment]
Why no one tries to correct this simple yet IMPORTANT issue !?
Hello !! Is there anyone up-there ?

**Comment by suhashpatil** [comment]
From my past experience, If you know how to fix it, you can push the fix to
the tree and it will be rolled in.
I had one bug which made my life miserable, I found the problem, fixed it
and uploaded the fix which was rolled in.

Suhas


Suhas Patil
http://www.linkedin.com/in/suhashpatil
http://www.slideshare.net/suhashpatil/nuevosoft-test-manager-overview
Skype: suhaspatil
Phone (M): +91-982 284 2031

**Comment by JTURKI** [comment]
I know how to solve it, but the problem is in the website and not the sources of web.py !
And I don't see the website project in GITHub.
Anyway, for those who may edit that web page "http://webpy.org/docs/0.3/api" , 
please just replace : 
           "class Template(self, text, filename='&lt;template&gt;' "
by :
      "class Template(self, text, filename='<span>&amp;</span><span>lt</span>;template<span>&amp;</span><span>gt</span>;' "

That's it!

**Comment by iamFIREcracker** [comment]
@JTURKI maybe this the project you were looking for: https://github.com/webpy/webpy.github.com

**Comment by JTURKI** [comment]
Thanks @iamFIREcracker, just done this.
Pull request: https://github.com/webpy/webpy.github.com/pull/103

**Comment by cigumo** [comment]
+1

**Comment by lanyuliuyun** [comment]
+1

**Comment by lanyuliuyun** [comment]
@JTURKI ' patch works. But the page at http://webpy.org/docs/0.3/api is still NOT updated yet and Docs content is STILL TRUNCATED !!
