### ISSUE TITLE
web.seeother

### ISSUE THREAD

**Issue by suziguai** [webpy/webpy#311]
When I use the code "Basic wiki in 0.3" I get from the "http://webpy.org/src/wiki/0.3", I find when I use the method  "raise web.seeother('/' + form.d.url)" in the class New in wiki ,I will go to (/new/+"url") instead of (/"url"),Why? Does the method seeother just designed for this?

**Comment by imnofox** [comment]
The example doesn't have a trailing slash on the URL i.e `'/new/', 'New',`, it instead has no slash i.e `'/new', 'New',`, which sounds like it's your problem.

I realise this is old, though others nay have the same problem :p
