### ISSUE TITLE
feature suggestion - add/append form elements also after __init__

### ISSUE THREAD

**Issue by shula** [webpy/webpy#318]
trying to add form elements after creating the form wil fail, since "inputs" is a tuple.

Why:

Without that change, there's no way to systematically append fields from other sources.

so, instead of tuple, just use a list

```
class Form(object):
    def __init__(self, *inputs, **kw):
        #self.inputs = inputs
        self.inputs = list(inputs)
```

and use e.g.   

```
myform.inputs.append(  Textbox(auto_var, ...) )
```

better yet, 
i suggest adding a method to accept additional inputs.

**Comment by iamFIREcracker** [comment]
> Without that change, there's no way to systematically append fields from other sources.

May I ask you why can't you just create a new form if you need to add those fields _systematically_?

**Comment by shula** [comment]
i'm not sure we understand each other.

My task:

How to add fields from an external source, e.g. from a dictionary.

    d = {  'f1': 'DeFault1' }
    d = {  'f2': 3 }
    d = {  'f3': 4.5 }
    (and probably more)
    Form( ?? )

in the suggested way:

    form = Form()
    for key in d:
        form.inputs.append( Textbox( key, value=d[key] ) )

**Comment by shula** [comment]
same way: an easy way to fill in previously entered values:

        inputs = web.input()
        for name in fields.keys():
            textbox = form.Textbox(name, value=inputs.get(name) )
            form.inputs.append( textbox )

**Comment by iamFIREcracker** [comment]
Sorry, but I don't understand what are you trying to accomplish with this: are you trying to _extend_ an existing form by adding few fields, or just populating the form with some values?

In my apps, I first _define_ forms:

    add = form.Form(form.Hidden('facebook_id', form.notnull),
                    form.Textbox('first_name', form.notnull),
                    form.Textbox('last_name', form.notnull),
                    form.Textbox('name', form.notnull))

And then use them like this:

    form = add()
    if form.validates(**params):
      print 'success'
    else:
      print 'failure'

Does this help you?

**Comment by shula** [comment]
in your example, you know during programming time what are your fields.

What if - the field list is unknown in advance , and it is given only during run time? 

(in my first example, I get "d" from a web service, or a DB query, config file, etc.)

**Comment by iamFIREcracker** [comment]
Well, imho the Form thing might not be the right tool for your needs, if that is your use case.  You definitely need something more dynamic, and as far as I can tell Forms were not meant to be used in scenarios where the set of fields to check was not known in advance.

Is the set of possible fields known in advance?  If so, you could have validators implemented in such a way that the business validation is executed only if the input value is not None; kind of hacky, but could work..

**Comment by iredmail** [comment]
No plan for this, sorry.
