### ISSUE TITLE
Quote column names when generating SQL

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#32]
Bug reported on Launchpad by [Martin Janda](https://launchpad.net/~info-martinjanda) on 2010-06-30.

https://bugs.launchpad.net/webpy/+bug/600164

&nbsp;

web.db for postgresql writes the column names in SQL as:

```
INSERT INTO log_changes (action, user, time) VALUES ...
```

But what if the column name is from the keyword as a column 'user' in the example?

Solution is to add double quotes around column name. For example:

```
INSERT INTO log_changes ("action", "user", "time") VALUES ...
```

Yes, I know, now it can be solved by using web.db.query method.

**Comment by iredmail** [comment]
Do you guys still have this issue? I personally didn't experience this issue at all with the latest web.py-0.39.

Please share some code snippet to help reproduce this issue.
