### ISSUE TITLE
Serve custom '/static/' folder

### ISSUE THREAD

**Issue by layus** [webpy/webpy#321]
With the current implementation, web.py serves static files from $(pwd)/static.
This is dependent from the current directory.

It is annoying when packaging a web application as the packaged static files will be located in /usr/local/lib/pythonX.Y/site-packages/foo/static.

If I have custom files for the application in /srv/foo and want to run the web app in that folder, the only solution I see is to symlink the static folder.

Note that this problem impacts only the mockup server used for tests.
With Apache, we can serve any directory under '/static/'.
The problem is not trivial to fix as web.py uses the SimpleHTTPRequestHandler that only serves files in the current working repository. (https://github.com/webpy/webpy/blob/master/web/httpserver.py#L95-96)

This is how I serve the correct static folder https://github.com/layus/INGInious/blob/723ec5ad444060b587ec7e8a6c14491ee069d30a/app_frontend.py#L80-82
Note that it may break relative paths specified in configuration.json.

Related issues : #130 (#123 ?)

**Comment by sreejithkesavan** [comment]
It's a little annoying/silly that you have to `cd` to the package's root directory to run the app to serve the static pages. There should be an easy configurable option in web.py to address this.

**Comment by layus** [comment]
Yep ! That's why I opened the issue, and also because I have no time at the moment to make a pull request :-).

**Comment by iredmail** [comment]
No plan for this, sorry.
