### ISSUE TITLE
form.Dropbox validation turns value into string, causing no value to be selected on render

### ISSUE THREAD

**Issue by dolfandringa** [webpy/webpy#325]
I have a problem in form.Dropbox. Upon validation, the value from web.inputs() is taken, which always contain string values. This value is saved in the dropbox.value. Upon render of the input, it then doesn't select the correct option of the dropbox when the values are integers instead of strings.
Some code illustrating the problem. Note that after the second render() call, the correct value in the dropbox is not selected.

```
dd=form.Dropdown('foo',[(1,'a'),(2,'b'),(3,'c')])
dd.render()
#u'<select id="foo" name="foo">\n  <option value="1">a</option>\n  <option value="2">b</option>\n  <option value="3">c</option>\n</select>\n'
dd.value=2
dd.render()
#u'<select id="foo" name="foo">\n  <option value="1">a</option>\n  <option selected="selected" value="2">b</option>\n  <option value="3">c</option>\n</select>\n'
f=form.Form(dd)
f.validates(source={u'foo':u'2'})
#True
dd.render()
#u'<select id="foo" name="foo">\n  <option value="1">a</option>\n  <option value="2">b</option>\n  <option value="3">c</option>\n</select>\n'
f.validates(source={u'foo':2})
#True
dd.render()
#u'<select id="foo" name="foo">\n  <option value="1">a</option>\n  <option selected="selected" value="2">b</option>\n  <option value="3">c</option>\n</select>\n'
```

**Comment by jimgregory** [comment]
I think you need to pass strings instead of integers as the first arguments to the tuples in your list.

**Comment by iredmail** [comment]
The value `foo=2` is correctly rendered with latest git version of web.py.
Issue closed.
