### ISSUE TITLE
Impossible to do the step "Hello world bob"

### ISSUE THREAD

**Issue by adrianobrum** [webpy/webpy#329]
<type 'exceptions.TypeError'> at /
**template**() takes no arguments (1 given)

Python  /home/pi/code.py in GET, line 11
Web GET http://192.168.1.76:8080/
Traceback (innermost first)

/home/pi/code.py in GET
        print render.index(name) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/web/application.py in handle_class
            return tocall(*args) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/web/application.py in _delegate
            return handle_class(cls) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/web/application.py in handle
        return self._delegate(fn, self.fvars, args) ...
▶ Local vars
/usr/local/lib/python2.7/dist-packages/web/application.py in process
                    return self.handle() ...
▶ Local vars
Response so far

HEADERS
Variable    Value
Content-Type  
'text/html; charset=utf-8'
BODY
Request information

INPUT
No data.
COOKIES
Variable    Value
__utma  
'57076202.1562217511.1429704642.1429704642.1429718689.2'
__utmc  
'57076202'
__utmz  
'57076202.1429704642.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
META
Variable    Value
app_stack  
[<web.application.application instance at 0x1a936e8>]
fullpath  
u'/'
headers 
[('Content-Type', 'text/html; charset=utf-8')]
home  
u'http://192.168.1.76:8080'
homedomain  
u'http://192.168.1.76:8080'
homepath  
u''
host  
u'192.168.1.76:8080'
ip  
u'192.168.1.72'
method  
u'GET'
output  
u''
path  
u'/'
protocol  
u'http'
query  
u''
realhome  
u'http://192.168.1.76:8080'
status  
'200 OK'
ENVIRONMENT
Variable    Value
ACTUAL_SERVER_PROTOCOL  
'HTTP/1.1'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8'
HTTP_ACCEPT_ENCODING  
'gzip, deflate, sdch'
HTTP_ACCEPT_LANGUAGE  
'pt-PT,pt;q=0.8,en-US;q=0.6,en;q=0.4,de;q=0.2,es;q=0.2,it;q=0.2'
HTTP_CACHE_CONTROL  
'max-age=0'
HTTP_CONNECTION 
'keep-alive'
HTTP_COOKIE 
'__utma=57076202.1562217511.1429704642.1429704642.1429718689.2; __utmc=57076202; __utmz=57076202.1429704642.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
HTTP_HOST  
'192.168.1.76:8080'
HTTP_USER_AGENT 
'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36'
PATH_INFO  
'/'
QUERY_STRING  
''
REMOTE_ADDR 
'192.168.1.72'
REMOTE_PORT 
'60556'
REQUEST_METHOD  
'GET'
REQUEST_URI 
'/'
SCRIPT_NAME 
''
SERVER_NAME 
'localhost'
SERVER_PORT 
'8080'
SERVER_PROTOCOL 
'HTTP/1.1'
SERVER_SOFTWARE 
'CherryPy/3.2.0 Server'
wsgi.errors 
<open file '<stderr>', mode 'w' at 0xb6cea0d0>
wsgi.input  
<web.wsgiserver.KnownLengthRFile object at 0x1af5650>
wsgi.multiprocess  
False
wsgi.multithread  
True
wsgi.run_once  
False
wsgi.url_scheme 
'http'
wsgi.version  
(1, 0)
You're seeing this error because you have web.config.debug set to True. Set that to False if you don't want to see this.

**Comment by alburthoffman** [comment]
would you mind to show ur code?

**Comment by imnofox** [comment]
Looks like you haven't defined any variables in your template.
Make sure your first line has a parameter set: `$def with(name)`
