### ISSUE TITLE
How to add asterisk to required fields in a form

### ISSUE THREAD

**Issue by sumanth232** [webpy/webpy#332]
$:form.render_css() is what I do to render html for the form.
How to add red asterisk on the label ?

**Comment by imnofox** [comment]
Currently, the closest you can get is by adding a normal coloured asterisk to the input description.
`form.Textbox("username", description="Username *")`

**Comment by jimgregory** [comment]
You can put the asterick before (or after) the input (but not the label) by adding a special class to any inputs that are required, then add the character and any styling you want via CSS. e.g.,

form.Textbox("username", class_="required")

then in your stylesheet or <style> block at the top of your template:
```css
.required:before {
    content:'*";
    color:red;
}
```

**Comment by iredmail** [comment]
No plan for this, sorry.
