### ISSUE TITLE
Memory Error in db.py

### ISSUE THREAD

**Issue by merlink01** [webpy/webpy#334]
Huge DB-Requests lead to an Memory Error while doing "print >> debug" in line 603.

Webpy Version:
Latest Git Version

Systems:
Win7 64 Bit/ 64Bit Python
Arch Linux with newest updates

If I disable line 603 everything runs fine.

Traceback:
File "...\web\db.py", line 659, in query
    self._db_execute(db_cursor, sql_query)

  File ...\web\db.py", line 603, in _db_execute
    print >> debug, '%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query))

  File "...\web\db.py", line 249, in **str**
    return safestr(self._str())

  File "...\web\db.py", line 244, in _str
    return self.query() % tuple([sqlify(x) for x in self.values()])

MemoryError

**Comment by iredmail** [comment]
Dear @merlink01 

- Did you set `web.config.debug_sql = True` for your application to print the SQL commands?
- Do you still have this issue with the latest git version of web.py?
