### ISSUE TITLE
Multiple queries using db.query() raises a ProgrammingError

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#34]
Reported on Launchpad by by [Brian J Ewing](https://launchpad.net/~brianewing-gmail) on 2010-11-08.

https://bugs.launchpad.net/webpy/+bug/672538

&nbsp;

```
db.query("INSERT INTO table1 (field1, field2) VALUES ('value', 'value');" +
    " UPDATE table2 SET foo='bar'")
```

This works fine, however a `_mysql_exceptions.ProgrammingError` is raised:

```
_mysql_exceptions.ProgrammingError: (2014, 
    "Commands out of sync; you can't run this command now") 
in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x>>
```

db.query tries to return the result from the last query without first freeing the result of the first, and MySQLdb raises this exception

**Comment by iredmail** [comment]
@anandology is this still an issue?

**Comment by iredmail** [comment]
No plan to fix this "issue".
