### ISSUE TITLE
Documentation for api not loading to the end

### ISSUE THREAD

**Issue by MalcolmSlaney** [webpy/webpy#343]
When I load the page
    http://webpy.org/docs/0.3/api
using either Chrome or Safari on my Macintosh, I don't get the entire page.  It looks like it ends somewhere just after the start of the web.template library

:-(

-- Malcolm
![image](https://cloud.githubusercontent.com/assets/959911/9979158/173a55d4-5f11-11e5-88f8-8838601501a4.png)

**Comment by neko1990** [comment]
[Here](https://github.com/webpy/webpy.github.com/blob/master/docs/0.3/api.md) is the corresponding Markdown file. There is a **<template**> right after  **filename ='**   [@line1924](https://github.com/webpy/webpy.github.com/blame/master/docs/0.3/api.md#L1924). Maybe **<template**> is a keyword in jekyll and it breaks the page  generating.

**Comment by anandology** [comment]
Fixed now.

**Comment by jzellman** [comment]
Thanks! :bow:
