### ISSUE TITLE
HttpErrors seems to ignore content for custom message 

### ISSUE THREAD

**Issue by krithik** [webpy/webpy#349]
```
return web.badrequest("insert custom message here")
```

A POST request  to trigger that function call with curl responds with below.
- Rebuilt URL to: http://192.168.1.135:9999/
- Hostname was NOT found in DNS cache
-   Trying 192.168.1.135...
- Connected to 192.168.1.135 (192.168.1.135) port 9999 (#0)
  > POST / HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: 192.168.1.135:9999
  > Accept: _/_
  > Content-Type: application/json
  > Content-Length: 77
  > 
- upload completely sent off: 77 out of 77 bytes
  < HTTP/1.1 400 Bad Request
  < Content-Type: text/html
  < Transfer-Encoding: chunked
  < Date: Sat, 05 Dec 2015 01:44:43 GMT
- Server localhost is not blacklisted
  < Server: localhost
  < 
- Connection #0 to host 192.168.1.135 left intact

**Comment by iredmail** [comment]
With latest git version of web.py, custom message works fine.
