### ISSUE TITLE
content-type of static file header 

### ISSUE THREAD

**Issue by yitao** [webpy/webpy#353]
My env is window7 x64 &python2.7 
 I only want  to build my webapp with web.py . but i don't want use apache or nginx .
Then the content-type is "application/x-css" in response header when i request a css file .
It worked on ie8 but not on chrome-45 and firefox-43 . 
So i change this code of httpserver.py in the 216 line(class StaticApp, func send_header , the 1 line):
--code like this--
self.headers.append((name, value)) ---> self.headers.append((name, "application/octet-stream"))
-- end --
So, Anybody can tell me why it worked.? Does it mean we can set the content-type also is "application/octet-stream"? and let the browser does other thing like parse file content-type ?
thanks

**Comment by yitao** [comment]
myfalut,
--code like this--
self.headers.append((name, value)) ---> 
if name == "content-type":
			self.headers.append((name, "application/octet-stream" if value=="application/x-css" else value))
		else:
			self.headers.append((name, value))
-- end --

**Comment by denglj** [comment]
“text/css”

**Comment by yitao** [comment]
"application/x-css " to "text/css"?
i only want to know original design

**Comment by iredmail** [comment]
Closed: seems not a webpy issue and no further update from reporter.
