### ISSUE TITLE
hello. python 3.5 error

### ISSUE THREAD

**Issue by heiheiheibj** [webpy/webpy#354]
C:\Users\hater\Desktop\webpy-python3\webpy-python3>python setup.py install
running install
running build
running build_py
running install_lib
byte-compiling C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-pa
ckages\web\browser.py to browser.cpython-35.pyc
  File "C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-packages\
web\browser.py", line 49
    print 'requesting', req.get_method(), req.get_full_url()
                     ^
SyntaxError: invalid syntax

byte-compiling C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-pa
ckages\web\wsgiserver\ssl_builtin.py to ssl_builtin.cpython-35.pyc
  File "C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-packages\
web\wsgiserver\ssl_builtin.py", line 43
    except ssl.SSLError, e:
                       ^
SyntaxError: invalid syntax

byte-compiling C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-pa
ckages\web\wsgiserver\ssl_pyopenssl.py to ssl_pyopenssl.cpython-35.pyc
  File "C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-packages\
web\wsgiserver\ssl_pyopenssl.py", line 70
    except SSL.SysCallError, e:
                           ^
SyntaxError: invalid syntax

byte-compiling C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-pa
ckages\web\wsgiserver__init__.py to **init**.cpython-35.pyc
  File "C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-packages\
web\wsgiserver__init__.py", line 616
    except ValueError, ex:
                     ^
SyntaxError: invalid syntax

running install_egg_info
Removing C:\Users\hater\AppData\Local\Programs\Python\Python35\Lib\site-packages

**Comment by liuaifu** [comment]
Resently, i test web in python3.5.1. When i import web, the interpreter reported a error, see the following message:

    >>> import web
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Python35-32\Lib\site-packages\web\__init__.py", line 14, in <module>
        import utils, db, net, wsgi, http, webapi, httpserver, debugerror
    ImportError: No module named 'utils'
    >>>

however, the utils.py is exist in C:\Python35-32\Lib\site-packages\web.

**Comment by jeffsilverm** [comment]
It looks as if several python files were not updated to work with Python 3.x.
ssl_pyopenssl.py is one of them.
wsgiserver/__init__.py is another
ssl_builtin.py is another
browser.py is another.

I'm going to see if I can fix these files reasonably easily.

**Comment by jeffsilverm** [comment]
After running 2to3 on these files, I can install web.py.

**Comment by jeffsilverm** [comment]
But that wasn't enough.  A lot of the tests failed.  I need to be more patient.  I'm sorry.

**Comment by William-An** [comment]
@liuaifu you can use pip2 to install webpy to avoid this kind of err
