### ISSUE TITLE
Every request generating a session when using Session, how to exclude some of the URL

### ISSUE THREAD

**Issue by 1u4nx** [webpy/webpy#362]
I have a web application, this web application has two functions, REST API and normal WEB Applications, and enabled Session function.

The urls like this:

```
urls = (
    '/', 'Index',
    '/login', 'Login',
    ....

    # API
    '/api/book', 'Book',
    ....
    )
```

I would like to / login enabled Session, so:

```
if web.config.get('_session') is None:
    session = web.session.Session(app,
                                  web.session.DiskStore('sessions'),
                                  initializer={'loginin': False})
    web.config._session = session
```

but, every request `/api/book`, generating a session file in sessions directory, so will soon have a lot of files, I hope that does not generate a file, how to solve? thanks.

**Comment by akash0x53** [comment]
@1u4nx AFAIK you can't control when session should initiate based on URLs.  

You could run separate instances of application in different modes. Provide mode switch using command line arguments.` --web` `--api` for example.
- one for REST APIs on some different port say 5000 without initiating `Session`.
- second instance will have Session enabled.

**Comment by 1u4nx** [comment]
@akash0x53

Thank you, I read session.py of web.py, indeed can not be achieved, but API and application need run the same time, so, I can add exclude URLs feature to Session class or running on some dirrerent port.

**Comment by mox1** [comment]
I'm fairly certain you can do what you want with "sub-applications" see- http://webpy.org/cookbook/subapp

**Comment by shahrk** [comment]
@1u4nx  

What you can do is have a separate app for login, suppose it is login.py so you'd import login and map '/login' to login.app ( here app is login.py's app=web.application(urls,global()) ).
Now, sessions won't get saved on every request to '/api/book'

If this solves your issue. Please close the issue.

**Comment by iredmail** [comment]
Closed due to no further update from reporter.
