### ISSUE TITLE
database update

### ISSUE THREAD

**Issue by FreeManZH** [webpy/webpy#369]
webpy the update function return value is the number of rows changed, but I want when the where conditions do not exist, can return a special value, or throw an exception，how can I do?

**Comment by anandology** [comment]
web.py doesn't support anything like that. You'll have to do it yourself by looking at the returned value.

Please use the [mailing list][1] or stackoverflow for asking questions and reserve github issues only for bugs and feature requests.

[1]: https://groups.google.com/forum/#!forum/webpy
