### ISSUE TITLE
Template sandboxing is not working in Python 3

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#372]
web.py template engine doesn't allow unsafe code in the template by making sure blacklisted nodes are not present in the AST. 

This feature is not working in Python 3 as the `compiler` module that is used by template has been removed in Python 3.

**Comment by anandology** [comment]
The `ast` modules seems to have a parse method, but that seems to be returning a completely different object.

**Comment by Zashas** [comment]
I made a fix for this (cf commit mentioned here above).  The nodes' names changed a bit between the compiler and ast modules, a lot of new ones were added, and I was too lazy to add them all, so I made instead a disallow list. I maybe forgot one or two important node type, so I'd appreciate if someone can double-check this !

**Comment by anandology** [comment]
Having a whitelist of nodes instead of blacklist of nodes was a design decision. I don't think it is a good idea to change that.
