### ISSUE TITLE
Postgres database allows using binary and fails

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#373]
Here is what I tried.

```
import web
db = web.database(dbn="postgres", db="webpy")

id = db.insert("test", name="\u0c05".encode('utf-8'))
rows = db.where("test", id=id).list()
print(rows)
```

And the output was:

```
0.0 (1): SELECT c.relname FROM pg_class c WHERE c.relkind = 'S'
0.0 (2): INSERT INTO test (name) VALUES (b'\xe0\xb0\x85'); SELECT currval('test_id_seq')
0.0 (3): SELECT * FROM test WHERE id = 7
[<Storage {'id': 7, 'name': '\\xe0b085'}>]
```

I think it shouldn't have allowed using bytes in the first place.

**Comment by anandology** [comment]
Also, if I try a select query with name, it fails with the following error.

    >>> db.where('test', name="\u0c05".encode('utf-8')).list()
    ERR: SELECT * FROM test WHERE name = b'\xe0\xb0\x85'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/anand/github/webpy/webpy/web/db.py", line 723, in where
        where=where)
      File "/Users/anand/github/webpy/webpy/web/db.py", line 705, in select
        return self.query(qout, processed=True)
      File "/Users/anand/github/webpy/webpy/web/db.py", line 665, in query
        self._db_execute(db_cursor, sql_query)
      File "/Users/anand/github/webpy/webpy/web/db.py", line 596, in _db_execute
        out = cur.execute(query, params)
    psycopg2.ProgrammingError: operator does not exist: text = bytea
    LINE 1: SELECT * FROM test WHERE name = '\xe0b085'::bytea
                                      ^
    HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

**Comment by Zashas** [comment]
Indeed, I don't think it has much sense to pass bytes parameters to these functions. Anyway, the DB API, on which rely all the backends, always use strings, and not bytes. 

We could raise a TypeError when bytes are passed to help the user, but I wouldn't qualify this as a bug neither.

**Comment by anandology** [comment]
It is possible that it is a bug in the psycopg2 library. If that is the
case, then we shouldn't worry and just report the bug to them.

**Comment by iredmail** [comment]
Consider not a bug of web.py, issue closed.
