### ISSUE TITLE
py3 pip install shows a warning

### ISSUE THREAD

**Issue by Zashas** [webpy/webpy#382]
When installing the 0.40dev release with Python 3, the following warning appears : 

```
Extracting web.py-0.40_dev0-py3.4.egg to /bla/bla/bla/lib/python3.4/site-packages
  File
"/bla/bla/bla/lib/python3.4/site-packages/web.py-0.40_dev0-py3.4.egg/web/wsgiserver/wsgiserver2.py",
line 1019
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
```

The concerned file comes from cherrypy. They recently adressed this issue : https://github.com/cherrypy/cherrypy/tree/e9d3e3a4d73a0eda64277c3a72b410d28c6263fb/cherrypy/wsgiserver

If nobody else wants to fix this, I'll submit a PR next week.

**Comment by surajsharma** [comment]
`C:\Users\suraj.sharma>py -m pip install web.py
Collecting web.py
  Using cached web.py-0.38.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SURAJ~1.SHA\AppData\Local\Temp\pip-build-mezmuo7c\web.py\setup.py", line 6, in <module>
        from web import __version__
      File "C:\Users\SURAJ~1.SHA\AppData\Local\Temp\pip-build-mezmuo7c\web.py\web\__init__.py", line 14, in <module>
        import utils, db, net, wsgi, http, webapi, httpserver, debugerror
      File "C:\Users\suraj.sharma\AppData\Local\Programs\Python\Python35-32\lib\site-packages\db\__init__.py", line 69
        print "var", var
                  ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SURAJ~1.SHA\AppData\Local\Temp\pip-build-mezmuo7c\web.py\
`

this is what is happening at my end, any way out?

**Comment by William-An** [comment]
@surajsharma You should use python2.7 to install web.py as in py3.5, the print method is print(**args)

**Comment by iredmail** [comment]
No more such error with the latest git version. Please try again and reopen this issue if it doesn't work for you.
