### ISSUE TITLE
Add support for RDS versions of Postgresql and MySQL

### ISSUE THREAD

**Issue by bpluly** [webpy/webpy#383]
AWS has hosted versions of an increasing number of database and data stores which simplify the business of managing such things at the cost of a small amount of lock in to their API.

The API for RDS is very thin though and equivalent in a lot of ways to the web.db api. The only real additional work needed is to accept the AWS key parameters on the db object creation and use boto.py to connect to the data source. Once the object is returned it can be used in exactly the same way as any other web.db implementation.

Are there any plans for this kind of functionality at the moment, and if not would a patch be accepted (not that I have one at the moment)?

**Comment by anandology** [comment]
I don't think it is a good idea to make web.py dependent on boto. What do you think of creating a new project webpy-RDS?

**Comment by bpluly** [comment]
I think you may well be right unless it was generalised so that other
authentication schemes could be used as well as AWS keys.

So a webpy-RDS project is feasible forking the db.

S

**Comment by iredmail** [comment]
No plan for this. Sorry.
