### ISSUE TITLE
template.py -- Google App Engine

### ISSUE THREAD

**Issue by WeaverStever** [webpy/webpy#384]
Trying to get a running app moved to Google App Engine - Python 2.7.

I did finally get the GAE cookbook example at http://webpy.org/cookbook/google_app_engine working, but only after I scoured the net, and found that the /web directory from the repo is required in the app directory.   

However, when I took the version directly (/web) from the downloaded repo, template.py throws an error.  

```
 File "web/template.py", line 47, in <module>
    from .utils import storage, safeunicode, safestr, re_compile
ValueError: Attempted relative import in non-package
```

Looking at the error above, I grabbed the /web directory from the installed version (/usr/lib/python2.7/dist-packages) instead of the repo.  This works as expected.

A line item about it on the cookbook page might be helpful for future users.

**Comment by eslizn** [comment]
maybe you should use:
`python -m web.template --compile templates`
