### ISSUE TITLE
why my python code don't run,when i delete `if __name__="__main":`  ？

### ISSUE THREAD

**Issue by oahcy** [webpy/webpy#385]
* like this code
``` python
import web
        
urls = (
    '/(.*)', 'hello'
)
app = web.application(urls, globals())

class hello:        
    def GET(self, name):
        if not name: 
            name = 'World'
        return 'Hello, ' + name + '!'

#if __name__ == "__main__":
app.run()
```
#### when i run the code ,i can't open the website,and the code print two line:
> http://0.0.0.0:8080/
> http://0.0.0.0:8080/

#### why i can't open the website? why the code print more line?
my pyhon version is 2.7.6

**Comment by kjmph** [comment]
I believe the way webpy works under the covers, it is parsing the file wrapping the `hello` class in a new thread. As such, that causes it to double execute the app.run() command, and never return from the import. It would be advised to move the `hello` class to its own file. You can do so in two ways. Either like so:

```
from helloFile import helloClass
urls = (
       '/(.*)', 'helloClass'
)
```

Or, like so:

```
urls = (
       '/(.*)', 'helloFile.helloClass'
)
```

The advantages of the first choice means all import statements in the helloFile are parsed upon start of the server. The advantages of the second choice means all import statements are lazy loaded at request time. At least, this is my intuition.

**Comment by anandology** [comment]
On Mon, 12 Sep 2016 at 18:46 oahcy <notifications@github.com> wrote:

>
>    - like this code
>
> import web
>
> urls = (
>     '/(.*)', 'hello'
> )
> app = web.application(urls, globals())
> class hello:
>     def GET(self, name):
>         if not name:
>             name = 'World'
>         return 'Hello, ' + name + '!'
> #if __name__ == "__main__":
> app.run()
>
> when i run the code ,i can't open the website,and the code print two line:
>
> http://0.0.0.0:8080/
> http://0.0.0.0:8080/
>
> why i can't open the website? why the code print more line?

When web.py is run using the dev server, the debug mode is enabled and it
starts the reloader, which reloads the main module once again as a regular
module. If you add the `if __name__ == ..` condition that it'll work as
expected.

If you won't want to do that, then disable debug mode, by adding the
following line before creating the app.

web.config.debug = False

Anand

>

**Comment by anandology** [comment]
If you have any more questions about web.py, please join the [web.py mailing list][1].

[1]: https://groups.google.com/group/webpy
