### ISSUE TITLE
web.py + html + css 

### ISSUE THREAD

**Issue by dgoldwx2112** [webpy/webpy#388]
OK I hate to post something like this to a git forum but I'm kinda desperate. I'm attempting to deploy my very first website using the web.py framework under ubuntu 16.04 with apache2. I've got a directory structure like this:

/var/www/mysite.com
-bin
-html
-static

I've got the python app in bin (bin/myapp.py), the html files in /html and my css files in static/

Long story short, when I enter my URL into a browser, it successfully serves up the html code itself:

`$def with (title,name,content) $var title:$title
Hello!

$content[0]

$content[1]`

However, no styling is being applied to the contents, nor are the values of the "content" variable being displayed. Something closer to the final product - albeit again with no styling applied from the accompanying .css file - is found by viewing base.html (link provided below). I'm doing something wrong but I am at a loss as to what that could be. I did successfully deploy this on my localhost prior to attempting to publish to the www.

There is a link to the 'static' directory within the <head> tags at the top (/static/index.css) and I am using a base template file. I further modified the /etc/apache2/conf file according to instructions in http://webpy.org/cookbook/mod_wsgi-apache-ubuntu and http://webpy.org/cookbook/staticfiles. I've viewed every other resource there is but nothing has really helped.

Any help would be much appreciated. I've got my files available for viewing at:

<a href="https://www.dropbox.com/s/v5bind605zmhqma/goldwx.py?dl=0">python app</a>
<a href="https://www.dropbox.com/s/r44zncpc6mus4jk/base.html?dl=0">base.html</a>
<a href="https://www.dropbox.com/s/m2py40d2iiw4lqj/index.html?dl=0">index.html</a>
<a href="https://www.dropbox.com/s/qmgo36pwr0t91is/base.css?dl=0">base.css</a>
<a href="https://www.dropbox.com/s/qmgo36pwr0t91is/index.css?dl=0">index.css</a>
<a href="https://www.dropbox.com/s/5215pofpb8v2o5r/goldweatherservices.com.conf?dl=0">apache config file</a>

**Comment by jzellman** [comment]
@anandology could you please close this. @dgoldwx2112 an approach that will get more eyes would be to post all your files to a gist and ask this question to the mailing list. As a first step you may want to search the group since your question or a similar one that will help you through this may have already been answered.

**Comment by anandology** [comment]
Please ask questions in the mailing list.
