### ISSUE TITLE
web.py runtime error - dictionary changed size during iteration

### ISSUE THREAD

**Issue by Avapo22** [webpy/webpy#393]
Hello,
the following simple program returns runtime error.

---------------------------------------------------------------------------------------------
import os
import web
import pandas

urls = (
  '/', 'index'
)

class index:
    def GET(self):
        return "POST.."

class index:
    def POST(self):
        web.header('Content-Type', 'application/json')
        return {}

if __name__ == "__main__":
    os.environ["PORT"] = "9000"
    app = web.application(urls, globals())
    app.run()

---------------------------------------------------------------------------------------------

TypeError('write() argument must be str, not bytes',)
Traceback (most recent call last):
  File "C:\Users\Radim\Anaconda3\lib\site-packages\web.py-0.40.dev0-py3.5.egg\web\application.py", line 255, in process
    return p(lambda: process(processors))
  File "C:\Users\Radim\Anaconda3\lib\site-packages\web.py-0.40.dev0-py3.5.egg\web\application.py", line 642, in processor
    h()
  File "C:\Users\Radim\Anaconda3\lib\site-packages\web.py-0.40.dev0-py3.5.egg\web\application.py", line 737, in __call__
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

----------------------------------------------------------------------------

It works correctly without importing pandas module.

Can you please help me to solve the problem?

Many thanks

Radim

**Comment by anandology** [comment]
I noticed that too, but didn't pay much attention to it. I'll look into it.

**Comment by gh-webpy** [comment]
This also happened to me, when I called `requests.get(url)` inside a `web.py` POST. There is something wrong with the autoloader and the autoloader is active, when `debug` is not `False`.

This works for me:
```
    web.config['debug'] = False # before application.__init__()!
    app = web.application(urls, globals())
```

**Comment by tonyplee** [comment]
The following fixed the issue for me: 

 git diff
diff --git a/web/application.py b/web/application.py
index a85b031..72b3eaa 100644
--- a/web/application.py
+++ b/web/application.py
@@ -734,7 +734,8 @@ class Reloader:
         self.mtimes = {}
 
     def __call__(self):
-        for mod in sys.modules.values():
+        l = sys.modules.values()
+        for mod in l:
             self.check(mod)
 
     def check(self, mod):

**Comment by ethanyhzhang** [comment]
I tried as follows:
      **l = sys.modules.values()
              for mod in l:**
but it didn't work for me.
.....violently, just pass it....no check....not a good choice anyway

**Comment by sibande** [comment]
I also encountered this issue, I tried similar modification to the `application.py` file and all of them didn't work, I then came across this hard reloading solution https://groups.google.com/forum/#!topic/webpy/EOJV4lEXQbI

@anandology in the thread from the link above you mention that you were tempted to include this in web.py, please consider it again.

**Comment by lijiayi123456** [comment]
737    for mod in sys.modules.values():
          for mod in list(sys.modules.values()):

**Comment by iredmail** [comment]
Do you guys still have this issue with the latest git version of web.py?

**Comment by lxyyukiko** [comment]
yes，I  still got it with 0.40.0 version. what' s the possible reason for that? Is it because of pandas?

**Comment by cclauss** [comment]
__for mod in list(sys.modules.values()):__
