### ISSUE TITLE
HTTPS Redirection on seeother

### ISSUE THREAD

**Issue by harshanarayana** [webpy/webpy#394]
Hi, 

I am new to web.py and I was trying to deploy a web.py based application on Cloudfoundry and ran into a strange issue with regards to `seeother` function call. 

When I redirect the Webpage using the `seeother`, the application is redirected back to an http url instead of an HTTPS url. 

Can someone please help me the right way to get the HTTPS redirection working  ?

**Comment by sconeyard** [comment]
Please check your ctx enviroment. Check whats inside ctx.home. It seems on seeother the url is composed of ctx.home. So you may be able to fix this issue by overwriting ctx.home.

**Comment by iredmail** [comment]
Closed due to no further update from reporter.
