### ISSUE TITLE
Pip install fails on Python 3 with "No module named 'utils'"

### ISSUE THREAD

**Issue by andy-maier** [webpy/webpy#396]
On Python 3.4 (in a Python virtual environment, on RHEL 7.2):

```
(zhmc34) [...]$ pip install web.py
Collecting web.py
  Downloading web.py-0.38.tar.gz (91kB)
    100% |████████████████████████████████| 92kB 1.3MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-wcnq4q29/web.py/setup.py", line 6, in <module>
        from web import __version__
      File "/tmp/pip-build-wcnq4q29/web.py/web/__init__.py", line 14, in <module>
        import utils, db, net, wsgi, http, webapi, httpserver, debugerror
    ImportError: No module named 'utils'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-wcnq4q29/web.py/
```

The reason seems to be that `web/__init__.py` relies on relative path resolution. I wonder how this ever can have worked under Python 3?

**Comment by RoryKelly** [comment]
+1

**Comment by jzellman** [comment]
I don't believe 0.38 supports python 3, see .travis.yml from tag: https://github.com/webpy/webpy/blob/webpy-0.38/.travis.yml

However,  master does support 3.5, so maybe 3.4 will also work?   https://github.com/webpy/webpy/blob/master/.travis.yml

You can try installing master via: 
pip install -e git://github.com/webpy/webpy.git#egg=webpy-master

**Comment by RoryKelly** [comment]
master works any idea when we can expect a release from master?

**Comment by codingHahn** [comment]
With pip: `pip install web.py==0.40.dev0`

**Comment by captain4554** [comment]
@codingHahn You're Awesome Thank You

**Comment by codingHahn** [comment]
Np.

**Comment by cmahjoubi** [comment]
Thank you

**Comment by JoeJoeyMa** [comment]
Thank

**Comment by rajesh121kanna** [comment]
ImportError: No module named web
2018-03-02 10:13:05,210 3753 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
Warn: Can't find .pfb for face 'Times-Roman'
2018-03-02 10:13:05,299 3753 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf


 i wanna answer plz this error and i dont know plz

**Comment by anandology** [comment]
If you want to install for Python3, use:

```
pip install web.py==0.40-dev1
```

As you can see, python3 version is not completely ready.

[The website](https://webpy.org) has been updated with this information.
