### ISSUE TITLE
do calculation

### ISSUE THREAD

**Issue by thesauband** [webpy/webpy#399]
how do i do the following simple calculation in web.py 
in python 
s=s+5 is possible but 
In web.py I use $s=$s +5 and $s = s +5 at the next attempt but both are incorrect
how can overcome this issue

**Comment by suhashpatil** [comment]
One uses $ for only use within templates (html files). The python code is
regular python code and does not need $. Or am I missing something obvious?


Suhas Patil - Linked In <http://www.linkedin.com/in/suhashpatil>
*Khojpal - Connect Locally! *
Facebook <https://www.facebook.com/khojpal/> :: Web
<http://www.khojpal.com/> :: Android
<https://play.google.com/store/apps/details?id=com.affingo.khojpal> :: iOS
<https://itunes.apple.com/us/app/id1035269012>
Press: Economic Times
<http://economictimes.indiatimes.com/small-biz/startups/from-finding-blood-donors-to-renting-sherwani-new-apps-make-local-connection-easier/articleshow/53705557.cms>,
Times of India
<http://timesofindia.indiatimes.com/city/pune/New-to-the-town-These-apps-help-you-find-a-friend/articleshow/52059326.cms>
Mobile: +91-982 284 2031
Skype: suhaspatil

**Comment by thesauband** [comment]
dear suhaspatil 
thank you for your response i got this difficulty on web.py templates , actually I need to know how should I declare the variables in web.py templates, I am new to web.py

**Comment by anandology** [comment]
@thesauband The template engine is white space sensitive. You'll have to do the following for assignment.

    $ s = s + 5

Please use the [mailing list][1] or stackoverflow for asking questions and reserve github issues only for bugs and feature requests.

[1]: https://groups.google.com/forum/#!forum/webpy

**Comment by thesauband** [comment]
thanks anand
