### ISSUE TITLE
Automatic form rendering creates tables

### ISSUE THREAD

**Issue by despens** [webpy/webpy#40]
Automatic forms should create a more CSS friendly and contemporary HTML. For example `<li>`-Elements with `<label>`s and `<input>`-Elements.

Another interesting feature could be automatic ids generated from the input's name, like

```
<li id="prefix-username">
    <label for="username_generated_element">Name of the User</label>
    <input id="username_generated_element" type="text" name="username">
</li>
```

With an optional prefix this could greatly ease CSS styling.

**Comment by iredmail** [comment]
No plan to fix this issue. Feel free to reopen this issue if required.
