### ISSUE TITLE
cherrypy.wsgiserver -> cheroot

### ISSUE THREAD

**Issue by webknjaz** [webpy/webpy#401]
Hi,

I'm a contributor of [`cherrypy`](https://github.com/cherrypy/cherrypy). I've noticed you use copy-pasted version of `cherrypy.wsgiserver`. It's now moved into a separate project [`cheroot`](https://github.com/cherrypy/cheroot).

I guess you may now depend on it directly (via install_requires, or via git submodule/subtree) w/o having to cut it off cherrypy.

Have fun :)

**Comment by jzellman** [comment]
Thanks @webknjaz for the info. @anandology any preference on git magic vs setup.py install_requires?

**Comment by anandology** [comment]
Since it is already available as a third-party module, there is no point to
include it in web.py.

The question now is, should web.py depend on it or use it if available and
switch to something like wsgiref when it is not available?

**Comment by webknjaz** [comment]
You may use `extras` to declare optional features and their dependencies

**Comment by anandology** [comment]
We've moved to cheroot now. Thanks @webknjaz and @jzellman.
