### ISSUE TITLE
travis build - pip unable to install packages MySQLdb, pgdb, pymysql, psycopg

### ISSUE THREAD

**Issue by varunpurohit76** [webpy/webpy#408]
Travis log
https://travis-ci.org/webpy/webpy/jobs/202901118
lines 156 - 159

**Comment by anandology** [comment]
I think pip stops if one of the packages listed fails to build. `MySQLdb` doesn't works Python3, so it should only be in `test/requirements2.txt`, not `test/requirements.txt`.

**Comment by anandology** [comment]
One thing I don't understand is why didn't the build fail when pip failed to install the packages. That looks like more serious issue.

**Comment by anandology** [comment]
Seems to be installing the right packages now after fixing test/requirements.txt.

https://travis-ci.org/webpy/webpy/jobs/205558505

**Comment by anandology** [comment]
Even though that fixed the build for Python 3.5, the build is now broken (for not installing the required packages) for Python 2. 

https://travis-ci.org/webpy/webpy/jobs/205558503

The `TRAVIS_PYTHON_VERSION` doesn't seem to be working.

**Comment by anandology** [comment]
The silent errors issues seems to be fixed with the above commit.

https://travis-ci.org/anandology/webpy/jobs/205565111

Notice that the python-2.6 build has failed now.

**Comment by anandology** [comment]
Fixed now. 

https://travis-ci.org/webpy/webpy/jobs/205568530

Thanks @varunpurohit76 for bringing this up.
