### ISSUE TITLE
how to use render in subapplications?

### ISSUE THREAD

**Issue by haoyong** [webpy/webpy#417]
render = web.template.render('templates/', globals={'context': session, 'static': '/static'})

in main.py
app = web.application(urls, locals())
session = web.session.Session(app, web.session.DiskStore('sessions'), initializer={'count': 0})
render = web.template.render('templates/', globals={'context': session, 'static': '/static'})

how use 'render' in index.py?

**Comment by anandology** [comment]
You can import the module where you have defined `render` in `index.py` and use it.
