### ISSUE TITLE
Does the project still work on?

### ISSUE THREAD

**Issue by Hubert51** [webpy/webpy#418]
I am wonder whether web.py compatible with python3

**Comment by anandology** [comment]
Yes. You need to install the 0.40.dev0 version to use it.

    pip install web.py==0.40.dev0

Please use [web.py mailing list][1] for asking questions. Issues for reporting bugs and requesting features. 

[1]: https://groups.google.com/forum/#!forum/webpy

**Comment by Hubert51** [comment]
Thanks！
