### ISSUE TITLE
Recently read something about it on ACG forums

### ISSUE THREAD

**Issue by boblao0714** [webpy/webpy#420]
It seems like that Kobayashi in Miss Kobayashi's Dragon Maid is working on this project......
BUT WHY ON EARTH I WOULD CONCERN WHAT PROJECT THEY WORK ON?
Damn it

**Comment by Azure0044** [comment]
I have the same confusion....or maybe it's just a habit><?

**Comment by boblao0714** [comment]
I dunno and in fact that Kobayashi's job is a programmer is why I go watch this anime

**Comment by jzellman** [comment]
Can't tell if this is spam. 

@anandology could you please close?
