### ISSUE TITLE
static files serving issues

### ISSUE THREAD

**Issue by creekwax** [webpy/webpy#422]
I'm using web.py to serve a webapp with some static files(css/javascript) within the `static` folder. Nginx is used to forward requests to the port at which my webapp is listening.
Here comes the problem that static files can't be served one or two days after the webapp starts. According to the output from my `nohup.out` file, it's working quite well during the first a few hours, but reporting `404 not found` responding to static file requests from some moment on.

**Comment by ohadperry** [comment]
+1

**Comment by jzellman** [comment]
Typically when nginx is used with a web.py applcation, static files are not served by the web.py app but are instead served by nginx. Nginx acts as a proxy and forwards non static requests to the web.py application which is running on another port. For example if you followed the cookbook example here: http://webpy.org/cookbook/fastcgi-nginx static files would be served directly by nginx. If you did follow the cookbook example, part of the issue may be that it is out of date. 

@creekwax @ohadperry could either of you provide more details about the environment (nginx version, uwsgi being used?, os version, are you using gunicorn, etc?) and your nginx configuration along with a stripped down version of your web app file?

**Comment by ohadperry** [comment]
-1.false alarm my issue was serving a pdf file 
here is the solution for me 
```
        pdf_file = open(temp_file, 'rb')
        web.header('Content-Type','application/pdf', unique=True)
        web.header('Content-Disposition', 'attachment; filename="'+file_name_downloaded+'"', unique=True)

        return pdf_file
```
