### ISSUE TITLE
Pyinstaller not working for Web.py projects.

### ISSUE THREAD

**Issue by PatrickFlaherty** [webpy/webpy#429]
Pyinstaller not working for Web.py projects. It builds ok, and even spawns but errors when first web request is sent. I get the following error:
http://0.0.0.0:8080/
Traceback (most recent call last):
  File "site-packages\web\application.py", line 237, in process
  File "site-packages\web\application.py", line 607, in processor
  File "site-packages\web\application.py", line 77, in reload_mapping
ImportError: No module named WebExample
127.0.0.1:59708 - - [12/Jul/2017 17:06:30] "HTTP/1.1 POST /myclass" - 500 Internal Server Error
Here's the project:

""" Basic todo list using webpy 0.3 """
import web

# Url mappings
urls = (
    '/myclass', 'classHandler'
)

class classHandler:

    def GET(self):
        """ Get method """
        print 'Hello World Get'

    def POST(self):
        """ Post method """
        print 'Hello World Post'

app = web.application(urls, globals())

if __name__ == '__main__':
    app.run()

**Comment by qiaofei32** [comment]
pyinstaller -F WebExample.py  --hidden-import=WebExample

**Comment by jzellman** [comment]
@PatrickFlaherty did @qiaofei32 comment help? If so, can you please close?
