### ISSUE TITLE
web.py available in conda-forge

### ISSUE THREAD

**Issue by sebastian-luna-valero** [webpy/webpy#433]
Hello,

Just wanted to say that I have added `web.py` in `conda-forge`:
https://github.com/conda-forge/web.py-feedstock

Please let me know if anyone wants to be a maintainer of the recipe in `conda-forge`

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
I should also emphasize that I have used version `0.40.dev0`, which according to the tests in `conda-forge` works for either Python 2 and 3 and it is available for Linux, Mac and Windows.

**Comment by anandology** [comment]
Awesome! Thank you so much.

Could you please update the version of web.py on conda to `0.40.dev1`?
