### ISSUE TITLE
web.form returns value with Textbox but not Textarea

### ISSUE THREAD

**Issue by bsugerman** [webpy/webpy#434]
I'm using a very simple application of this fabulous code as shown here:

https://kooneiform.wordpress.com/2010/02/28/python-and-ajax-for-beginners-with-webpy-and-jquery/

to read in user input in a form and then run it through a python app. I needed to use a larger Textarea rather than Textbox, but when I swap "Textarea" for "Textbox" in the app.py file's call

my_form = web.form.Form(web.form.Textbox(...))

the object my_form has no data stored in it after being run through validates(). It works perfectly with Textbox however. Makes me wonder whether form.Textbox is written/functioning with a bug?

-ben

**Comment by anandology** [comment]
Could you please share a small code snippet to reproduce the issue?

**Comment by bsugerman** [comment]
It was my problem, not webpy's. I didn't change the appropriate term in my html code from 'input' to 'textarea.' If there is a way to delete this whole issue request, we probably should do so.
