### ISSUE TITLE
Got trouble when using db.select for MSSQL in session.py

### ISSUE THREAD

**Issue by Petersonjoe** [webpy/webpy#435]
OS: Windows 7 Enterprise Edition x64
Python: python 64-bit 2.7
web.py: 0.40.dev0
pymssql: 2.1.3
MSSQL: SQL Server 12.0.2 (Version No.: 2014)

Just tried the cookbook sample in "Using session with reloader" with my database enviroment. The server actually startup, and when I first type the url request - "http://localhost:8080/count", it works well and return "1" in the page. However, when I refresh the page, I got this error message:

`<type 'exceptions.ValueError'> at /count
__len__() should return >= 0`

The TraceBack displays the error occurs in session.py
C:\Python27\lib\site-packages\web.py-0.40.dev0-py2.7.egg\web\session.py in __contains__

    `def __init__(self, db, table_name):
        self.db = db
        self.table = table_name
    
    def __contains__(self, key):
        data = self.db.select(self.table, where="session_id=$key", vars=locals())
        **return bool(list(data))** 
    def __getitem__(self, key):
        now = datetime.datetime.now()
        try:
            s = self.db.select(self.table, where="session_id=$key", vars=locals())[0]
            self.db.update(self.table, where="session_id=$key", atime=now, vars=locals())`

Everytime when I refresh the page, it will raise the error above. I tested like this  

   `def tryselect1(db):
        data = db.select('sessions', where="session_id='978f82232841f4fff264f7fedc7febd447bfd23c'")
        return bool(list(data))` 
 
'>>> aa = tryselect1(db)
0.01 (7): SELECT * FROM sessions WHERE session_id='978f82232841f4fff264f7fedc7febd447bfd23c'
**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in tryselect1
ValueError: __len__() should return >= 0**'

Seems the query was successfully concatenated, well when using 'bool(list(data)'), it got this error (but it will successfully return 'False' when using 'bool(data.list())'). Not konw if anyone had ever got this problem and any solution? 

My scripts listed below:

`
# -*- coding: utf-8 -*-
import os
import web
import pymssql
import readConfig
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

#web.config.debug = False
urls = (
    "/count", "count",
    "/reset", "reset"
)
app = web.application(urls, globals())

filename = "db.config"
section = "dbConfig"
configinfo = readConfig.DecodeConfig(filename)
DB_TYPE = configinfo.getConfig(section, "DB_TYPE")  #sql server 2014
HOST = configinfo.getConfig(section, "HOST")
PORT = configinfo.getConfig(section, "PORT")
DB_NAME = configinfo.getConfig(section, "DB_NAME")
USER = configinfo.getConfig(section, "USER")
PASSWORD = configinfo.getConfig(section, "PASSWORD")
db = web.database(dbn=DB_TYPE, host=HOST, port=PORT, db=DB_NAME, user=USER, pw=PASSWORD)
store = web.session.DBStore(db, "sessions")

web.config.session_parameters['cookie_name'] = 'webpy_session_id'
web.config.session_parameters['cookie_domain'] = None
web.config.session_parameters['timeout'] = 86400, #24 * 60 * 60, # 24 hours   in seconds
web.config.session_parameters['ignore_expiry'] = False
web.config.session_parameters['ignore_change_ip'] = True
web.config.session_parameters['secret_key'] = 'fLjUfxqXtfNoIldA0A0J'
web.config.session_parameters['expired_message'] = 'Session expired'

if web.config.get('_session') is None:
    session = web.session.Session(app, store, initializer={'count': 0})
    web.config._session = session
else:
    session = web.config._session

class count:
    def GET(self):
        session.count += 1
        return str(session.count)

class reset:
    def GET(self):
        session.kill()
        return ""

if __name__ == "__main__":
     app.run()
`

**Comment by jzellman** [comment]
Never seen this before. Maybe the length of the result set (data) is too long to fit into an int and thus fails bool conversion? Maybe this helps? https://stackoverflow.com/questions/2128989/python-len-and-size-of-ints 

Do you still see the error after adding limit=1 in tryselect?: 
```
data = db.select('sessions', where="session_id='978f82232841f4fff264f7fedc7febd447bfd23c'", limit=1)
```

**Comment by Petersonjoe** [comment]
Thanks, Jzellman. I didn't overcome this, so I just bypassed this error. Will back to it when I have a specific solution.
