### ISSUE TITLE
ModuleNotFoundError: No module named 'BaseHTTPServer'

### ISSUE THREAD

**Issue by Manishgupta95** [webpy/webpy#436]
import web

urls = {
    '/(.*)', 'index'
}

app = web.application(urls, globals())

class index:
    def GET(self, name):
        return "Hello " + name + ". How are u?"

if __name__ == "__main__":
    app.run()

running python latest version

**Comment by palnabarun** [comment]
It works fine. Can you post here the complete error stack trace?

**Comment by hucruz** [comment]
@Manishgupta95
Can you provide more information about the version of python and web.py you are using?
Some logs about the error can be useful.

I have tested the code you provide with python 3.6.2 and web.py == 0.40.dev0 and it works fine

**Comment by udaykumarbhanu** [comment]
Hi @Manishgupta95 <https://github.com/manishgupta95>,

I never worked in webpy. But in my past I have worked on Django.

Don't you think, your code having this line, if *name* == "*main*":
is supposed to be,

*if __name__ == "__main__":*


Thanks,
Uday

**Comment by anandology** [comment]
@Manishgupta95 Your `urls` are wrong. You are using a set to specify the urls instead of a tuple. Please replace that with the following to make this work.

```
urls = (
    '/(.*)', 'index'
)
```
