### ISSUE TITLE
Processor after request

### ISSUE THREAD

**Issue by jinnymus** [webpy/webpy#437]
Hi! Can i write code with processor after request? Its something do immediately upon response.
Request -> Response -> Async Request
If no i can fork and write

**Comment by krishnasagar14** [comment]
@jinnymus It is possible to write processor with unloadhook on app after a request served. The same processor will work for you (i.e. async request) after serving a request. 
look for more : http://webpy.org/cookbook/application_processors

**Comment by anandology** [comment]
Looks like the question is answered. Closing the issue.
