### ISSUE TITLE
db_multiple_insert returns wrong IDs for mysql

### ISSUE THREAD

**Issue by nlaurens** [webpy/webpy#446]
db.multiple_insert() assumes that the returned id is equal to the last in the list. This is not always the case (mysql). There is a pull request that wants to flip this but that ignores would fix it for some and break it for other dbs ([pull request #263 ](https://github.com/webpy/webpy/pull/263)). Will propose a fix in a new pull request for dbs I can test - for all others the pull request does not alter the behaviour of db.multiple_insert.

Behaviour for different dbs that I tested with the pull request:
* postgres -> gives the last id of multiple inserted rows.
* myslq -> gives the first id of multiple inserted rows. (see: [mysql-docs](https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_last-insert-id)).
* sqlite -> gives the last id of the multiple inserted rows. (see: [sqlite-docs](https://sqlite.org/c3ref/last_insert_rowid.html)).

**Comment by nlaurens** [comment]
P.s. here is a quick 'fix' to correct the incorrect ids returned by db.multiple_insert:

`if isinstance(db, web.db.MySQLDB):
    ids = range(ids[-1], ids[-1]+len(ids)`

**Comment by iredmail** [comment]
Fixed in #529
