### ISSUE TITLE
No 0.39 tag

### ISSUE THREAD

**Issue by jacmet** [webpy/webpy#449]
0.39 is released on pypi, but the git repo was not tagged / the tag not pushed. Could you tag 0.39 (presumably commit https://github.com/webpy/webpy/commit/6df75fe581e0e838d28334d5c53f52421560d38b) please?

**Comment by anandology** [comment]
Fixed. See tag [webpy-0.39](https://github.com/webpy/webpy/tree/webpy-0.39).

**Comment by jacmet** [comment]
Thanks!
