### ISSUE TITLE
Error: gevent==1.1.0, but you'll have gevent 1.1.2  && gevent>=1.1.2, but you'll have gevent 1.1.0

### ISSUE THREAD

**Issue by avatar-lavventura** [webpy/webpy#454]
`pip install web3`

Gives following error:
`pyethapp 1.5.0 has requirement gevent==1.1.0, but you'll have gevent 1.1.2 which is incompatible.`

But when I install gevent==1.1.0 than it gives following error:
`ethereum-tester-client 1.2.5 has requirement gevent>=1.1.2, but you'll have gevent 1.1.0 which is incompatible.`

I am not sure how to handle this problem.

**Comment by anandology** [comment]
not sure what is web3. If you want to install web.py for python 3 use:

```pip install web.py>0.40-dev```
