### ISSUE TITLE
httpserver.py:191 class StaticApp fails to encode headers as required by PEP333

### ISSUE THREAD

**Issue by lepeuvedic** [webpy/webpy#455]
Web.py crashes when given an URL beginning with `/static` and pointing to a non-existing file. The failure is initiated in Python's `server.py` and is detected in `wsgiserver3.py`, but the faulty code is actually in Web.py's file `httpserver.py`. The fault sequence is:
- `StaticApp` calls `send_head()`
- `send_head()` for some reason (e.g. 404 - Not Found) adds a 'Content-Length' header and passes the value as an `int`, rather than a string
- Web.py passes the headers' names and values as they come to `start_response`, failing to properly encode them as strict latin-1 strings.
- The WSGI server checks header values types and raises an exception when it finds the `int`.

`StaticApp` extends Python's `SimpleHTTPRequestHandler`.
It overloads method `send_header()`, whose role is to accumulate headers as they are generated. Some headers are generated by the Python lib during the call to parent class `send_head()`, line 232. The accumulated headers are then immediately sent to the WSGI compliant HTTP server (WSGICherryPy) using the `start_response()` function provided by that server. 

Unfortunately, Python's `server.py` counts on `send_header()` to convert to string and encode properly the headers, and while WSGICherryPy does check that they are indeed strings, it does not check that they are properly encoded (in latin-1, strict per PEP 333, see `wsgiserver3.py` line 2015). 

Python's send_header implementation is:

```
def send_header(self, keyword, value):
        """Send a MIME header to the headers buffer."""
        if self.request_version != 'HTTP/0.9':
            if not hasattr(self, '_headers_buffer'):
                self._headers_buffer = []
            self._headers_buffer.append(
                ("%s: %s\r\n" % (keyword, value)).encode('latin-1', 'strict'))

        if keyword.lower() == 'connection':
            if value.lower() == 'close':
                self.close_connection = True
            elif value.lower() == 'keep-alive':
                self.close_connection = False

```
whereas Web.py just accumulates (keyword, value) in a list. It also does not handle the `connection` header in the same way as the overloaded method.
A better implementation might be:
```
def send_header(self, keyword, value):
        if self.request_version != 'HTTP/0.9':
            self.headers.append(("%s" % keyword, ("%s" % value).encode('latin-1', 'strict')))

        if keyword.lower() == 'connection':
            if value.lower() == 'close':
                self.close_connection = True
            elif value.lower() == 'keep-alive':
                self.close_connection = False
```
The bug was also reported in Python lib (undocumented semantics, because it's not obvious that the `value` argument to `send_header` might be something else than a string).

**Comment by iredmail** [comment]
Hi @lepeuvedic 

Do you still have this issue? Could you try the latest git version of web.py?

**Comment by iredmail** [comment]
I can not reproduce this issue with latest git version of web.py. Consider this issue as invalid.

```
import web

urls = (
    '/staticsite', 'hello'
)
app = web.application(urls, globals())

class hello:
    def GET(self):
        return 'Hello'

if __name__ == "__main__":
    app.run()
```
