### ISSUE TITLE
session.py:209 uses Py3 deprecated base64.decodestring and fails when loading session from DB

### ISSUE THREAD

**Issue by lepeuvedic** [webpy/webpy#456]
In class `Store`, the method `decode` is implemented as:
```
    def decode(self, session_data):
        """decodes the data to get back the session dict """
        pickled = base64.decodestring(session_data)
        return pickle.loads(pickled)
```
This method is inherited by class `DBStore`.
In `base64`, the implementation of `decodestring` relies on `decodebytes`:
```
def decodestring(s):
    """Legacy alias of decodebytes()."""
    import warnings
    warnings.warn("decodestring() is a deprecated alias since Python 3.1, "
                  "use decodebytes()",
                  DeprecationWarning, 2)
    return decodebytes(s)
```
When loading a session to process a request, using `self.db.select`, the type of the `data` field in the returned `Store` instance is `str`. `base64.decodebytes` fails on objects of type `str`. It only works on bytestrings.

On the other hand, the method `read` in `class DiskStore` returns a `b'ytestring'`. This is why disk storage of session works, and DB storage of sessions fails.

There are several ways to fix this problem. The simplest one is to encode the data in ASCII:
In `session.py:296`, `class DBStore(Store)`: 
```
    def __getitem__(self, key):
        now = datetime.datetime.now()
        try:
            s = self.db.select(self.table, where="session_id=$key", vars=locals())[0]
            self.db.update(self.table, where="session_id=$key", atime=now, vars=locals())
            s = s.encode('ascii')  # May raise UnicodeEncodeError if data is corrupted.
        except IndexError:
            raise KeyError(key)
        else:
            return self.decode(s.data)
```

**Comment by iredmail** [comment]
@cclauss could you help check this issue?

**Comment by cclauss** [comment]
We need the following:
1. One or more test cases in our automated testing that fail on this issue.
2. A pull request that implements a solution that fixes the failing tests.

I would usually write this as:
```python
    def decode(self, session_data):
        """decodes the data to get back the session dict """
        if isinstance(session_data, bytes):
            try:  # bytes on Python 3
                pickled = base64.decodebytes(s)
            except NameError:  # bytes and str the same thing in Python 2
                pickled = base64.decodestring(session_data)
        else:
            # ??? str on Python 3
        return pickle.loads(pickled)
```
but I am not ever sure how to handle the last case that we have a __str__ in Python 3.

**Comment by iredmail** [comment]
hi @lepeuvedic 

Could you help verify whether this commit fixes your issue?
https://github.com/webpy/webpy/commit/8351e9cbd7185991a7785fa0309dc4dfe3532f1e
