### ISSUE TITLE
python3 utf8 characters in url get mangled

### ISSUE THREAD

**Issue by schneidersoft** [webpy/webpy#461]
Using python3
The following client built using requests

```
import requests
import urllib

if __name__ == '__main__':
    s = requests.Session()
    url = 'http://localhost:4040/' + urllib.parse.quote("Ω")
    print(url)
    r = s.get(url)
    print(r)
    print('What we expect:')
    print('Ω == Ω')
    print('What we got:')
    print(r.content.decode('utf8'))
```
When run against the following server:

```
import web

class allofit:
   def GET(self, arg1):
       	if (arg1 != 'Ω'):
           return 'Ω != '+arg1
        return 'Ω == '+arg1+' YAY!'

urls = ('/([^/]+)', 'allofit',)

app = web.application(urls, globals(), autoreload=True)

if __name__ == '__main__':
    app.run()
```

Produces:
```
http://localhost:4040/%E2%84%A6
<Response [200]>
What we expect:
Ω == Ω
What we got:
Ω != â
      ¦
```

Notice that the % escaped utf8 character is not preserved. Bug?

**Comment by schneidersoft** [comment]
You can also use a browser and browse to http://localhost:4040/%E2%84%A6
 or http://localhost:4040/Ω and have the same effect.

Anyone know how to fix this problem?

**Comment by krishnasagar14** [comment]
@schneidersoft Can you check types of both arguments in if clause? The arg1 may be unicode type.

**Comment by schneidersoft** [comment]
Both arguments are of type <class 'str'>
I did some digging and found in web/wsgiserver/wsgiserver3.py
```
class WSGIGateway_10(WSGIGateway):
   ...
    'PATH_INFO': req.path.decode('ISO-8859-1'),
```

changing ISO-8859-1 to utf8 solves the problem. But I don't know if this is a good thing to do.
I'm not sure what the http standards say about the encoding of this stuff.

It makes perfect sense though. because when the bytes as utf8 come in decoding them as ISO is going to break them.

**Comment by pbuckner** [comment]
problem under uwsgi is in application.py:432

`ctx.path = env.get('PATH_INFO')` 
should be
`ctx.path = bytes(env.get('PATH_INFO'), 'latin1').decode('utf-8')`

(if you're using standalone wsgiserver, then @schneidersoft would appear to have the same answer).

See, for example http://lists.unbit.it/pipermail/uwsgi/2011-March/001623.html 
uWSGI encodes strings as latin1, per PEP3333. I guess for most of the environment, the encoding doesn't matter (ip address is ascii, request method is ascii, etc.).

**Comment by schneidersoft** [comment]
I've created a pull request with a test case and fix.
#516
