### ISSUE TITLE
A major bug in Utils.py class and Solution of Stop Iteration Error

### ISSUE THREAD

**Issue by iammohdzaki** [webpy/webpy#466]
There is a bug in this experimental 3.7 python 
while running the app it shows the stopiteration error
In utils.py
replace the (line 512)
yield next(seq)
with:
try:
    yield next
except StopIteration:
    return

Hope This Works!

**Comment by fidrada** [comment]
yeah, am tracking this problem on similar stack thread : https://stackoverflow.com/questions/51700960/runtimeerror-generator-raised-stopiteration-everytime-i-try-to-run-app

But actually, this doesn't seem to solve the problem entirely.
I return now a syntax error once replacing (line 512) : 

` def take(seq, n):
        for i in range(n):
        yield next(seq)`

became : 

`  def take(seq, n):
        for i in range(n):
            yield next(seq)
            except StopIteration:
                return` 

and all i got is : 
` except StopIteration:
         ^
SyntaxError: invalid syntax`

any update on Web.py install for Python 3.7 ?

**Comment by fidrada** [comment]
indentation may twist the plot btw

**Comment by fidrada** [comment]
already solved problem my bad :  get this version and i'ts all done : https://github.com/webpy/webpy/blob/9d9eeef75dc34f62572c68e90093574a44207e1f/web/utils.py

**Comment by iammohdzaki** [comment]
thanks but one more problem the files are not loading to webpage when starting server.

**Comment by anandology** [comment]
fixed now.
