### ISSUE TITLE
all kinds of errors when using comments or strings of bytes

### ISSUE THREAD

**Issue by themaddoctor** [webpy/webpy#474]
If I add a comment with a nonascii character IN A COMMENT it throws an error.

Code:

#!/usr/bin/env python
from sys import setdefaultencoding
setdefaultencoding('utf8')
# ü

error:

<type 'exceptions.SyntaxError'> at /
Non-ASCII character '\xc3' in file /home/0000/server.py on line 22, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details (server.py, line 22)
Python | /usr/lib/python2.7/site-packages/web/application.py in check, line 721
-- | --
GET http://localhost:8080/

Also the damn thing is executing modules THAT HAVE BEEN COMMENTED OUT and then throwing more errors about strings. Those modules work just fine OUTSIDE web.py apps.

**Comment by themaddoctor** [comment]
Seriously, WTF?!?

<type 'exceptions.UnicodeDecodeError'> at /
'ascii' codec can't decode byte 0xa8 in position 9: ordinal not in range(128)

Python | /home/0000/server.py in validate, line 9
-- | --
GET http://localhost:8080/

Traceback (innermost first)

    /home/0000/server.py in validate
            system('validate ' + key + ' ' + hmac + ' ' + x + ' > output.txt')

**Comment by themaddoctor** [comment]
My code runs just fine without web.py. Not with web.py.

<type 'exceptions.UnicodeDecodeError'> at /
'ascii' codec can't decode byte 0x9e in position 0: ordinal not in range(128)


Python | /home/0000/server.py in hmac_sha1, line 87
-- | --
GET http://localhost:8080/

Traceback (innermost first)

    /home/0000/server.py in hmac_sha1
            return sha1(outer_key_pad + '{:040x}'.format(sha1(inner_key_pad + message)).decode('hex'))

**Comment by cclauss** [comment]
Are you running on Python or on legacy Python?

__sys.setdefaultencoding()__ was removed in Python 3 because all __str__ are Unicode utf-8.

**Comment by cclauss** [comment]
If you are on legacy Python then you have  obliged by PEP 263 to put __# coding: utf-8__ at the top of your file before adding Unicode characters to a Python source file.  Thank God there are only 248 daze until Python 2 EOL....
