### ISSUE TITLE
Error with Ubuntu/web.py Exception in thread when using cherryPy

### ISSUE THREAD

**Issue by bbarnes-fpi** [webpy/webpy#488]
web.py throws Exception in thread error. Configured to use cherryPy based off of cookbook example for version 0.37. Currently running version 0.39. Error is sporadic and eventually prevents the web server from responding.

Environment: 
Ubuntu 18.04.1 LTS 
Python 2.7.15rc1 
web.py: 0.39

```
import web
from web.wsgiserver import CherryPyWSGIServer

# GLOBALS
CherryPyWSGIServer.ssl_certificate = "/.ssl/fpi.crt"
CherryPyWSGIServer.ssl_private_key = "/.ssl/server.key"

urls = (
    '/(.*)', 'Hello',
    )

app = web.application(urls, globals())

class Hello:
    def GET(self, name):
        return 'Hello World'

if __name__ == "__main__":
    app.run()
```

Error:

> 73.220.196.76:63982 - - [27/Nov/2018 06:56:50] "HTTP/1.1 GET /" - 200 OK
> 73.220.196.76:63982 - - [27/Nov/2018 06:56:50] "HTTP/1.1 GET /favicon.ico" - 200 OK
> Exception in thread CP Server Thread-9:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/__init__.py", line 1375, in run
>     conn.communicate()
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/__init__.py", line 1269, in communicate
>     format_exc())
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/__init__.py", line 811, in simple_response
>     self.conn.wfile.sendall("".join(buf))
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/ssl_pyopenssl.py", line 111, in sendall
>     *args, **kwargs)
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/ssl_pyopenssl.py", line 61, in _safe_call
>     return call(*args, **kwargs)
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/__init__.py", line 913, in sendall
>     bytes_sent = self.send(data)
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/ssl_pyopenssl.py", line 115, in send
>     *args, **kwargs)
>   File "/home/brian_barnes/.local/lib/python2.7/site-packages/web/wsgiserver/ssl_pyopenssl.py", line 77, in _safe_call
>     raise socket.error(errnum)
> error: -1

**Comment by cclauss** [comment]
This PR was released against a non-production version of Python (Python 2.7.15rc1).  Please re-verify with a production release.
