### ISSUE TITLE
when i use gunicorn ,i lost stdout and stderr of webpy

### ISSUE THREAD

**Issue by zhubijia** [webpy/webpy#499]
when i use gunicorn start webpy,i lost stdout and stderr of webpy,such as the access log of webpy and the output of db part
does any one know it?thanks

**Comment by iredmail** [comment]
Please show us related info for troubleshooting:

- code snippet to reproduce the issue
- full command you used to run gunicorn

**Comment by iredmail** [comment]
Closed due to no sample code snippet to reproduce the issue and no further reply.
