### ISSUE TITLE
render_genshi ignores type='html'

### ISSUE THREAD

**Issue by drewp** [webpy/webpy#50]
web/contrib/template.py has this logic:

```
    if self._type == "text":
        ...
    else:
        cls = None
        type = None ##

    ...
        if type:
            return stream.render(type)
```

On the line where I put the ##, it should say type=self._type. Currently, calling render_genshi(type='html') and render_genshi(type='xhtml') do the exact same thing, which seems like a mistake. (For the record, the current code is always picking xhtml.)

**Comment by iredmail** [comment]
No plan to fix it recently. Feel free to reopen this issue if it's required.
