### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#504]
Current maintainer Anand is looking for webpy maintaineer(s):
https://groups.google.com/forum/#!topic/webpy/kN9DimTTEh0

Quote below:

> It was more than a decade ago[1] when I took over the maintenance of web.py from Aaron Swartz. web.py has changed a lot a since then and I'm really thankful for all the support from the community.
> 
> Of late there hasn't been much activity on web.py. The next version with Python 3 support is pending for long time.The website and documentation requires a fresh look.
> 
> While I'm quite interested to see web.py in much better shape and I still continue to use it regularly, I don't think I'm able to dedicate the kind of time I used to spend on it earlier. I think it is time to find other maintainers.
> 
> Please reply to this thread if you are interested and have the commitment to take web.py forward.
>
> [1]: https://groups.google.com/d/msg/webpy/ODisiYqdjWs/97KxslE-YkIJ

**Comment by xinthose** [comment]
So are you still maintaining the project then?

**Comment by cclauss** [comment]
This week's release: https://github.com/webpy/webpy/blob/master/ChangeLog.txt

**Comment by iredmail** [comment]
@xinthose i WAS not the maintainer when i posted this issue. I posted here to attractive people, but seems failed. so i tried.

New maintainers / contributors are always welcome. :)

**Comment by liuming-dev** [comment]
I will do it in my spare time.

**Comment by iredmail** [comment]
👍 @liuming-dev 欢迎
