### ISSUE TITLE
Is it time to make webpy py3-only?

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#509]
py2 will end of life in few months, seems no reason to support py2 anymore. A py3-only webpy release will remove a lot legacy code.

**Comment by 52lemon** [comment]
yes, now we only use py3 , when  shall we can use webpy in py3?

**Comment by Dan-in-CA** [comment]
If someone really wants to support Py2 they can always grab an old release from GitHub.

**Comment by iredmail** [comment]
I don't have enough time to make it happen, hope someone can take over.
Anand is looking for maintainer: https://github.com/webpy/webpy/issues/504

**Comment by vvdanila** [comment]
I am interested in contributing.

Thanks,
Victor

**Comment by iredmail** [comment]
Hi @vvdanila,

Feel free to send PR.  :)

**Comment by iredmail** [comment]
We will try to release a stable version with both py2+py3 supported, then switch to py3 only after Jan 1, 2020.

**Comment by anandology** [comment]
I think it would be good to support python2.7  and python3.6+. There is lot of legacy code to support python2.4 or 2.3. All that can be deleted.

**Comment by rafaelshin** [comment]
i am waiting for the stable version for python3 surpport

**Comment by iredmail** [comment]
@rafaelshin Latest git version of web.py should work fine with py3. Please try it and report issues in the issue tracker.

**Comment by cclauss** [comment]
__stable__ means a non-Dev version published in PyPI.

**Comment by iredmail** [comment]
@cclauss sure i understand that, just asking to try with the git version for testing purpose and report back.

**Comment by rafaelshin** [comment]
@iredmail  i'll try with py3 and report issues if i found any problem

**Comment by iredmail** [comment]
@rafaelshin Thanks. I'm working hard to solve existing issues and PRs.
