### ISSUE TITLE
When should we make the next release to PyPI?

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#517]
https://pypi.org/project/web.py#history  The last production release to PyPI was made in February 2018 and it does not fully support Python 3.  Given that the current code in this repo does support Python 3 and given that Python 2 end of life is in 110 days, it seems like a good time for us to make a new production release to PyPI so that projects that depend on web.py can use a production release.

1. Are there any objections to making such a release?
2. Are there any open issues or PRs that are _showstoppers_ to making such a release?
3. Do we have a documented process for how to make a release to PyPI?
4. Do we have the access rights (logins, passwords, certs, etc.) to make are release to PyPI?

**Comment by iredmail** [comment]
1: Agree to tag a new release and publish on pypi.
2: seems just some minor issues left, they should not impact much.
3: i don't know yet since what i have is just the git read+write privileges. We need to contact previous maintainer Anand @anandology to figure it out.
4: same as 3, we need to contact Anand.

**Comment by iredmail** [comment]
We're free to tag a new version and publish on github "Release" page, but not pypi.
Maybe we should tag `0.40.dev2` or `0.40` directly, document the changes since `0.40.dev`, then announce it in mailing list.

**Comment by anandology** [comment]
I agree that publishing a github release is a way to go. we already have 0.40.dev1 published on [pypi](https://pypi.org/project/web.py/#history). My preference is to go with `0.40.dev2`.

**Comment by anandology** [comment]
Would it be a good idea to have a milestone for 0.40 release so that we can tag all the bugs there?

**Comment by iredmail** [comment]
Tag 0.40 is ok. But how to publish a stable release on PyPI?

**Comment by iredmail** [comment]
Dear all,

I updated old milestone `Python3` to `0.40 + Python3`, and set the due date to Oct 1, 2019.
Since most big py3 issues have been fixed, we should have enough time to roll it out.

Thoughts?

**Comment by iredmail** [comment]
hi @anandology 

Since you're online right now, could you share the info about publishing new version on pypi?

**Comment by iredmail** [comment]
hi @cclauss @anandology 

- Only 2 issues/PR left in milestone `0.40 + Python-3`, i'm ok to release a stable version (`0.40`). Your opinions?
- I hope next version to be named `1.0` directly. `0.x` usually means "beta", "toy project" to some people, so let's make them happy and publicly announce that web.py is back to active development.

**Comment by iredmail** [comment]
@cclauss @anandology 

- Any comment?
- When should we release `0.40`?
- Any critical issues we need to solve in `0.40`? :)
- Plan for next stable release after `0.40`?

**Comment by cclauss** [comment]
We are ready for a ___production___ release now.

**Comment by iredmail** [comment]
Tagged `0.40`.

@anandology Could you help publish a pypi release?
In the future, how can other maintainers publish a pypi release without your attention?

**Comment by anandology** [comment]
The len issue in db results is pending. I should be able to push that fix
in couple of hours.

I think we should mark a pre-release ask people to try it out before
pushing a final release. What do you think?

**Comment by iredmail** [comment]
We can tag new bug fix release like `0.41`, `0.42`, `0.50`, etc.
We need help to publish on pypi.

**Comment by anandology** [comment]
Do you want to release without the len fix? I think that is very important
issue.

**Comment by iredmail** [comment]
I will wait for your fix, then we either re-tag `0.40`, or tag new `0.41`.
Then publish to pypi and announce it. We need some more attention to attract more contributions.

**Comment by cclauss** [comment]
@iredmail You should go through the tutorial https://packaging.python.org/tutorials/packaging-projects/ and load a test package up to the test server.

Once you have done that successfully, you can take on the production server. Caution: they are two separate servers that do not share account info so you need to create accounts on both.

**Comment by iredmail** [comment]
@cclauss Thanks for the info.
Not sure whether i can push a new release to pypi.org/project/web.py/.

**Comment by cclauss** [comment]
Learn the mechanics and create the IDs so that permissions can be transferred to those IDs.

**Comment by iredmail** [comment]
@cclauss Thank you very much. I didn't publish any package on pypi before. Kind of stupid. :(

**Comment by cclauss** [comment]
I have never done it either but I went thru the tutorial 48 hours ago for https://github.com/nodejs/tap2junit and the process is kinda cool.

**Comment by iredmail** [comment]
@anandology Re-tagged `0.40` with your last 2 fixes. You can post announcement now, and push to pypi.

**Comment by cclauss** [comment]
https://pypi.org/user/iredmail/ --> _We looked everywhere but couldn't find this page_

**Comment by iredmail** [comment]
@cclauss i didn't create account yet. Since @anandology is active, i prefer letting him do this since every web.py user know him.

**Comment by anandology** [comment]
On Fri, Sep 27, 2019 at 12:32 PM iRedMail <notifications@github.com> wrote:

> @anandology <https://github.com/anandology> Re-tagged 0.40 with your last
> 2 fixes. You can post announcement now, and push to pypi.
>
Pushed. Thanks @iRedMail and @cclauss for making this release possible.
I'll drop a mail in the list with change log.

**Comment by iredmail** [comment]
Super. Thanks.

We should discuss the plan for next (big) release now (maybe a new issue for this).
I prefer making it py3 only.

**Comment by anandology** [comment]
We need to update the website too.  @iRedMail can you please start working
on that?

I've already requested @sbp to make changes to DNS and that should be done
in a day.

**Comment by iredmail** [comment]
- Sorry, what does the "update the website" exactly mean?
- Is it possible to take over the domain name ownership? Seems @sbp is not active for a long time?

**Comment by anandology** [comment]
On Fri, Sep 27, 2019 at 1:21 PM iRedMail <notifications@github.com> wrote:

>
>    - Sorry, what does the "update the website" exactly mean?
>
> The website instructions still talk about 0.40-dev1. Need to update the
home page with latest version. I'll send a pull request with newly
generated API.


>
>    - Is it possible to take over the domain name ownership? Seems @sbp
>    <https://github.com/sbp> is not active for a long time?
>
> He is managing all the digital assets of @aaronsw and he is usually
responds back very quickly. He replied to my request to change the DNS and
it will be done in a day.

**Comment by iredmail** [comment]
- All version numbers in `webpy.github.com` repo has been updated to `0.40`.
- With fast reply from @sbp, then i'm fine. :)

**Comment by cclauss** [comment]
> He is managing all the digital assets of @aaronsw

Given that @iredmail is reluctant to signup for PyPI, would it be a good idea for https://pypi.org/user/sbp or I (https://pypi.org/user/cclauss) be added as a maintainer for [bus factor](https://en.wikipedia.org/wiki/Bus_factor) reasons?

**Comment by iredmail** [comment]
@anandology please add both me and @cclauss as the maintainer of pypi package.

**Comment by iredmail** [comment]
Contacted FreeBSD and OpenBSD port tree maintainer of webpy:

- OpenBSD port will be updated next week (i know this guy in personal and asked a favor, haha)
- Need to wait for (email) reply from FreeBSD maintainer.

Please help contact CentOS/Debian/Ubuntu package maintainer if possible.

**Comment by iredmail** [comment]
Mailed Debian package maintainer, hope he/she can help update web.py in Debian/Ubuntu soon.
