### ISSUE TITLE
Make sure all web/*.py files match PEP8 coding style

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#519]
Make sure all web/*.py files match PEP8 coding style

- [x] `__init__.py`
- [x] application.py
- [x] browser.py
- [x] db.py
- [x] debugerror.py
- [x] form.py
- [x] http.py
- [x] httpserver.py
- [x] net.py
- [x] py3helpers.py
- [x] session.py
- [x] template.py
- [x] test.py
- [x] utils.py
- [x] webapi.py
- [x] webopenid.py
- [x] wsgi.py

**Comment by cclauss** [comment]
Let’s jus run Th Python Software Foundation’s Black on the whole repo.  I will submit a PR in a few hours.

**Comment by iredmail** [comment]
@cclauss Maybe stored the black config file in webpy git repo, so that we have same setting.

**Comment by cclauss** [comment]
Black does not take configuration.  This is done on _purpose_.  Everyone gets the same defaults —You can have any color you want as long as it is black.

**Comment by iredmail** [comment]
Quote from its [document](https://black.readthedocs.io/en/stable/pyproject_toml.html):

> Black is able to read project-specific default values for its command line options from a pyproject.toml file.

I suppose you mean we just use all Black's default settings. I'm ok with this, but better mention this in README file or somewhere else.

**Comment by cclauss** [comment]
We will have a pre-commit file so that flake8 tests and black formatting can be auto-run locally in the commit process.

**Comment by iredmail** [comment]
Cool. I will wait for the changes. :)

**Comment by iredmail** [comment]
BTW, i personally dislike Black style function arguments (either definition or calling) like this:

```
            conn.delete(
                "settings",
                vars={"account": account, "params": _params},
                where="account=$account AND k IN $params",
            )
```

Preferred one is one argument per line like below, easier to read:

```
            conn.delete("settings",
                        vars={"account": account, "params": _params},
                        where="account=$account AND k IN $params")
```

Kind of struggling.

**Comment by iredmail** [comment]
@cclauss do we have other options besides Black?

**Comment by cclauss** [comment]
Please read the readme for Black.  This formatting encourages fewer parameters which makes for safer code.  The idea behind Black is to surrender your personal pet peeves in favor of a single standard.  gofmt has worked wonders for Golang and the PSF is pushing for similar unity.  We have more important things to worry about.
