### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#522]
Should discuss black, flake8, and pre-commit.

**Comment by iredmail** [comment]
I'm ok with most Black formats, but not few of them due to readability concern:

## the `urls = ()` reformat

List pattern and the class/func on same line will be easier to figure out which url pattern is delegated to which class/func.

Example:

```
# current
urls = (
    '/profile/domain/(general)/(%s$)' % d, 'controllers.ldap.domain.Profile',
    '/profile/domain/(admins)/(%s$)' % d, 'controllers.ldap.domain.Profile',
    '/profile/domain/(aliases)/(%s$)' % d, 'controllers.ldap.domain.Profile',
    '/profile/domain/(relay)/(%s$)' % d, 'controllers.ldap.domain.Profile',
    '/profile/domain/(bcc)/(%s$)' % d, 'controllers.ldap.domain.Profile',
)

# after Black
urls = (
    "/profile/domain/(general)/(%s$)" % d,
    "controllers.ldap.domain.Profile",
    "/profile/domain/(admins)/(%s$)" % d,
    "controllers.ldap.domain.Profile",
    "/profile/domain/(aliases)/(%s$)" % d,
    "controllers.ldap.domain.Profile",
    "/profile/domain/(relay)/(%s$)" % d,
    "controllers.ldap.domain.Profile",
    "/profile/domain/(bcc)/(%s$)" % d,
    "controllers.ldap.domain.Profile",
)
```

## the function arguments

You can not avoid functions with arguments which can not be placed in same line as function name, so the readability is top priority.

```
def my_func(my_arg_1, my_arg_2, my_arg_3=None, my_arg_4=None, my_arg_5=None, my_arg_6=None):
    pass
```

After format:

```
def my_func(
    my_arg_1, my_arg_2, my_arg_3=None, my_arg_4=None, my_arg_5=None, my_arg_6=None
):
    pass
```

I prefer either one below, so that i can easily figure out the argument names at the same indent instead of checking full line to figure it out:
```
def my_func_name(
    my_arg_1,
    my_arg_2,
    my_arg_3=None,
    my_arg_4=None,
    my_arg_5=None,
    my_arg_6=None,
):
    pass

def my_func_name(my_arg_1,
                 my_arg_2,
                 my_arg_3=None,
                 my_arg_4=None,
                 my_arg_5=None,
                 my_arg_6=None,
):
    pass
```

**Comment by iredmail** [comment]
After did some more research with Google, i would say let's just stick to Black and stop the discussion (about the code formatter) and move on.

**Comment by m1yag1** [comment]
I'd like to help with this. What would be the Acceptance Criteria for this as a PR? Should we run the set of changes through black during the travis build or only include instructions on how to install pre-commit? I currently use both with all my projects.

**Comment by iredmail** [comment]
Currently “black” is ran by Travis ci, is code doesn’t pass “black” check, the CI will fail. So I’d say we’re fine with “black” right now.

**Comment by iredmail** [comment]
Since `black` and `flake8` are enabled in GitHub Actions and Travis CI by default, issue closed.
