### ISSUE TITLE
Help enable doctest in .travis.yml

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#525]
hi @cclauss 

Could you help enable doctest in `.travis.yml`?

**Comment by iredmail** [comment]
Command `pytest --doctest-modules xxx.py` will perform the doctest, but i'm not sure how to handle the py2/py3 issue. For example:

```
1448         >>> d.extend([u'hello', u'world'])
1449         >>> d
Expected:
    <TemplateResult: {'__body__': 'helloworld'}>
Got:
    <TemplateResult: {'__body__': u'helloworld'}>
```

With py2, it expects a unicode string `u'xxx'`, but py3 expects string `'xxx'`.

**Comment by cclauss** [comment]
Closing based on https://github.com/webpy/webpy/pull/536#issuecomment-532474482

**Comment by iredmail** [comment]
Dear @cclauss 

Could you help enable doctests for py2 only?
I just realized there're more tests in doctests of `web/*.py` than `tests/test_*.py`. It would be great if we can enable them for just py2 right now.

After switched to py3, we can update doctests to completely support py3 (py2 support is not important at that time IMO).
