### ISSUE TITLE
debugerror.py causing errors

### ISSUE THREAD

**Issue by gjdv** [webpy/webpy#538]
When running the main of debugerror.py (Python 3.7)
`  File "...\web\http.py", line 18, in <module>
    from . import net, utils
ImportError: attempted relative import with no known parent package`
(Python2.7):
`  File ".../web/debugerror.py", line 18, in <module>
    from .template import Template
ValueError: Attempted relative import in non-package`

When raising an Exception in any render function (both Python 2.7 and 3.7):
`  File "...\web\debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax`

**Comment by iredmail** [comment]
What do you mean `running the main of debugerror.py`? Just run `python3 debugerror.py`?

**Comment by gjdv** [comment]
The first two errors reported are indeed generated in that way.
The last one is triggered when raising an Exception inside any render function when running the frontend-application

**Comment by cclauss** [comment]
Given the doctests comments and the import comments perhaps we should revert my doctest pull request.  Do you know how to do that?  I am about to board an airplane.

**Comment by iredmail** [comment]
hi @cclauss 

You can try to revert to old revision, there's no new commit after your commit, so it should be quite easy and safe to revert it. :)

**Comment by iredmail** [comment]
@cclauss would you like to revert the doctest commits? I can do this for you. Just give me a confirm.

**Comment by cclauss** [comment]
Done.  Can you please retest to make sure that we can close this issue.

**Comment by iredmail** [comment]
Fixed by #556.
