### ISSUE TITLE
Where is the sudo module used in experimental/pwt.py ?

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#543]
#541 allows Travis CI to run the doctests but it explicitly excludes [__experimental/pwt.py__](https://github.com/webpy/webpy/blob/master/experimental/pwt.py) because that file imports a sudoku module named __sudo__?  Should we find that module or should we remove that dependancy?

**Comment by iredmail** [comment]
@anandology Mind sending a PR to remove it?
