### ISSUE TITLE
Tasks for `0.40` stable release

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#544]
- [ ] Should we remove `web/webopenid.py`? PR is ready: #549 
- [x] What does `tools/{_makedoc.py,makedoc.py}` used for? ~Can we remove them?~
- [x] Remove `experiment/` completely
- [x] Fix existing doctests in `web/*.py` for either py2 or py3, and enable it in Travis CI.

After solved above tasks, we tag `0.40` stable release and publish announcement.

@anandology @cclauss would you like to write and post the announcement to web.py mailing list? Maybe some other social networks like Facebook, Reddit, etc.

**Comment by anandology** [comment]
The makedoc.py were used to generate the API docs. It was created before Sphinx even came into existence. It would be a good idea to switch to Sphinx docs. Would you like to do that now or after the 0.40 release @iredmail ?

**Comment by iredmail** [comment]
@anandology i have no plan to modify or replace `makedoc.py` recently.

**Comment by cclauss** [comment]
Let’s do it just after 0.40.  We should not add any new functionality to 0.40 because before the Py2 EOL we need a stable release in PyPI that supports Python 3.

**Comment by iredmail** [comment]
ok. How about `web/webopenid.py`?

**Comment by cclauss** [comment]
My vote is to remove __web/webopenid.py__

**Comment by iredmail** [comment]
+1 for remove it. 2 reasons:

1. openid is widely used, but it's unnecessary to be part of web.py.
2. currently used openid module is 9 years old.

Latest version of the `python-openid` module was released on Jun 19, 2010:
https://pypi.org/project/python-openid/#history

There's better openid module available in pypi, for example, `python-openid2`, last release is Jul 26, 2019, with py2.7 and py3.4+ support:
https://pypi.org/project/python-openid2/#description

@anandology your comment? Or send a PR to remove it directly? :)

**Comment by iredmail** [comment]
PR is ready for removing `web/webopenid.py`: #549

**Comment by cclauss** [comment]
Let's please use https://github.com/webpy/webpy/releases ...  That did not happen for the dev releases but it is a good idea.
