### ISSUE TITLE
len doesn't work on query result

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#547]
With web.py current master, using `len` on db results is not working.
```
$ git log -n 1 --oneline
e90573e (HEAD -> master, origin/master, origin/HEAD, anandology/master) Reformat with Black :(

$ python
Python 3.7.4 (v3.7.4:e09359112e, Jul  8 2019, 14:54:52)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import web

>>>
>>> db = web.database(dbn="postgres", db="webpy")
>>>
>>> len(db.query("SELECT 1"))
0.0 (1): SELECT 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'IterBetter' has no len()
```

 There is already a test for this as part of the test suite, but not sure how Travis is letting it go.

**Comment by anandology** [comment]
The issue is with old-style and new-style classes. The current implementation adds `__len__` function to the iterbetter object and that doesn't work with new-style classes. In addition to this that `__len__` is removed for sqlite as it doesn't support length.

I'm working on a fix for this.

**Comment by cclauss** [comment]
What is __len(list(db.query("SELECT 1")))__ because one of the main features of Python 3 is that it usually returns iterators instead of lists.

**Comment by cclauss** [comment]
TypeError: object of type 'IterBetter' has no len()

**Comment by iredmail** [comment]
Is it better to drop `IterBetter` while we switch to py3 (only)?

**Comment by cclauss** [comment]
No.  Plenty of other data structures like filter(), map(), range(), dict.items(), dict.keys(), dict.values() are iterators in Py3 but not Py2.  It is a huge optimization.  So let’s not resist iterators but instead embrace them.  When we need the len() or a specific item then wrap the iterator inside list().  If you study code that has been ported from 2to3, you will see that technique used where needed.

**Comment by iredmail** [comment]
Seems i didn't make it clear.

Sure we need iterators, what i mean is, the `IterBetter` is a custom class in web.py:

```
class IterBetter:
    Returns an object that can be used as an iterator
    but can also be used via __getitem__ (although it
    cannot go backwards -- that is, you cannot request
    `iterbetter[0]` after requesting `iterbetter[1]`).
```

The difference is it "can also be used via `__getitem__`", seems we don't have similar (builtin) thing in py3.

**Comment by cclauss** [comment]
Thanks.  How broadly is it used? Do we have test cases for it?

**Comment by iredmail** [comment]
Checked my web.py application (45655 lines in total), i'm surprised that i didn't use code like `len(db.query(...))` actually.

**Comment by cclauss** [comment]
How often does it use __IterBetter__ directly?

**Comment by iredmail** [comment]
I don't use `IterBetter` directly, but web.py uses it in `web/db.py` to return SQL query result:

1. line 748: https://github.com/webpy/webpy/blob/master/web/db.py#L748
2. line 1237: https://github.com/webpy/webpy/blob/master/web/db.py#L1237

Only one module (`web/db.py`) and 2 lines use this `IterBetter`, that's why i asked whether we should drop it after switched to py3 (comment in this thread: https://github.com/webpy/webpy/issues/547#issuecomment-534838636)

**Comment by iredmail** [comment]
@anandology Maybe we don't need `len()` support for query result. If user needs `len()` support, it's easy to convert to list then do the `len()`:

```
qr = db.query(...)
rows = list(qr)
len(rows)
for row in rows:
    print(row)
```

py2 and py3 don't offer an (official) way to get length on `iter()` object.

**Comment by iredmail** [comment]
Let's close this and tag+release+announce 0.40. :)

**Comment by anandology** [comment]
I think is very important issue. I've sent a Pull request, please consider it for this release. 

Also, the postgres tests are not running in Travis. I'm looking into it. I think that is also important not to ignore. I understand that making a release is important, but not at the expense of quality.

**Comment by anandology** [comment]
> @anandology Maybe we don't need `len()` support for query result. If user needs `len()` support, it's easy to convert to list then do the `len()`:
> [...]

web.py db module tries to expose whatever is available in the underlying db object. The length is present in the database result and it would not be appropriate to hide that just for convenience. 

https://www.python.org/dev/peps/pep-0249/#rowcount

**Comment by anandology** [comment]
> Also, the postgres tests are not running in Travis. I'm looking into it. I think that is also important not to ignore. I understand that making a release is important, but not at the expense of quality.

Sorry, false alarm.
