### ISSUE TITLE
Proposal: Move `web/db.py` to separate repo as a standalone ORM package

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#548]
[After `0.40` release]

The "ORM" offered by `web/db.py` is really awesome, simple and clear enough, easy to use and understand. How about move to a separate git repo and publish it on pypi as a standalone "ORM" package? It will benefit more people.

**Comment by daivlin** [comment]
Yeay，that is very good，I like the webpy/db.py and hope use it at other work

**Comment by anandology** [comment]
That is very good idea. It also give us a chance to get rid of the
dependency on thread-local state for storing connections.

**Comment by anandology** [comment]
On Thu, Mar 5, 2020 at 10:25 AM Anand Chitipothu <anandology@gmail.com>
wrote:

> That is very good idea. It also give us a chance to get rid of the
> dependency on thread-local state for storing connections.
>

In fact, I've attempted to do that long back, but never managed finished
it.
https://github.com/anandology/sqlpy

**Comment by iredmail** [comment]
Hi @anandology ,

Help fix this if you have some time:
https://github.com/webpy/webpy/issues/587

It’s committed by you, so you may have better understanding of why you made such change, fix it or revert it. :)

**Comment by cclauss** [comment]
Nice!  I see no downside to doing this.

**Comment by iredmail** [comment]
Duplicate in #564
