### ISSUE TITLE
sendmail needs to be refactored

### ISSUE THREAD

**Issue by aaronsw** [webpy/webpy#55]
The send logic should be pulled out so it can be applied to a message from anywhere. And if _EmailMessage is going to have all those features they ought to be public. (Or was it just copied from the Email module?)

**Comment by userlerueda** [comment]
@aaronsw is this still an issue?

**Comment by ni-code** [comment]
@userlerueda, Unfortunately the person you pinged is resting in peace.
https://en.wikipedia.org/wiki/Aaron_Swartz
