### ISSUE TITLE
CNAME DNS record of webpy.org is required by Github Pages

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#550]
To @anandology 

Please help create a CNAME DNS record for `webpy.org`, it should point to `webpy.github.io`.

Reference: https://help.github.com/en/articles/setting-up-a-custom-subdomain#configuring-a-cname-record-with-your-dns-provider

This should fix #518

**Comment by anandology** [comment]
The top level domain name can't have a CNAME. We can either use
www.webpy.org or find a work around.

**Comment by iredmail** [comment]
I think we can fix it by simply adding a CNAME for `www.webpy.org` which points to webpy.github.io.
`webpy.org` remains what it is right now.

**Comment by anandology** [comment]
Looks like GitHub now supports A Record for DNS.

https://help.github.com/en/articles/setting-up-an-apex-domain

With this we can continue to use webpy.org

**Comment by iredmail** [comment]
- Please help fix it. I got one warning email for every commit to the `webpy.github.com` repo.
- How about rename the repo name to `website` for short?
- Any plan to rewrite the tutorial? e.g. use version 0.40 instead.

**Comment by iredmail** [comment]
Seems fixed.
