### ISSUE TITLE
Re-organize code samples and move to (separated) github repo

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#557]
There're few code samples here: http://webpy.org/src/
Maybe we can re-organize them, test with the latest `0.40` and move to web.py git repo directly?

**Comment by cclauss** [comment]
@pkrumins The `redditriver.com` bits might be of interest to you.

**Comment by cclauss** [comment]
@iredmail We should not bloat the code of https://pypi.org/project/web.py with too many code samples.  

My strong preference would be that:
1. We leave as many of these code samples in the repos that they are in. --or--
2. We bring them into _separate repos_ under https://github.com/webpy

**Comment by iredmail** [comment]
A separated repo is better. :)

**Comment by cclauss** [comment]
To get us started, if you __create a new repo__ at https://github.com/webpy/webpy-sample-code then I will populate it with:
```
    Skeleton code. The very basics required to get started.
    Todo-list. The simplest database-driven app possible.
    Blog. A very simple blog, showing basic CRUD functionality.
    wiki. A very basic wiki engine.
```
from http://webpy.org/src/

**Comment by iredmail** [comment]
I tried, but don’t have privilege to create new repo.

@anandology could you grant the privilege?

**Comment by anandology** [comment]
On Fri, Sep 27, 2019 at 3:10 PM iRedMail <notifications@github.com> wrote:

> I tried, but don’t have privilege to create new repo.
>
> @anandology <https://github.com/anandology> could you grant the privilege?
>
Done. Please check and confirm?

Wouldn't it be better to name the repo as webpy-examples?

**Comment by iredmail** [comment]
“webpy-examples” is very good. 
the point is we need a repo for code samples. :)

**Comment by cclauss** [comment]
I created https://github.com/webpy/webpy-examples

**Comment by iredmail** [comment]
@cclauss Could you help move this sample app to the https://github.com/webpy/webpy-examples/ repo?
http://webpy.org/src/lecker.html

**Comment by cclauss** [comment]
@wuestholz Are you OK with this or would you rather host this code on a repo of your own?

**Comment by wuestholz** [comment]
@cclauss Thanks for checking with me. It must be ages since I wrote that code... :) Please feel free to move it there.

**Comment by cclauss** [comment]
Thanks.  I am closing so that all new issues related to sample code will be opened on https://github.com/webpy/webpy-examples/
