### ISSUE TITLE
Write new tutorial for upcoming (py3 only) release 

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#558]
This tutorial for Flask (in Chinese) is very good, the content it covers is more than enough to help you create a production web application:
https://read.helloflask.com/

I plan to write one (in English) for web.py when the py3-only release is in RC stage. 

Let me know if you think there’s some tech details should/must  be covered in such tutorial.

**Comment by nestor-alonso** [comment]
We should make documentation Dash compatible, so we can also use it offline.

https://kapeli.com/docsets

**Comment by iredmail** [comment]
Generating offline copy is not priority, we need a tutorial (for upcoming py3-only release) first.

**Comment by iredmail** [comment]
Turns out I don’t have enough time for this. So issue closed. :(
