### ISSUE TITLE
Python 2.7: do not show log in console

### ISSUE THREAD

**Issue by sokol07** [webpy/webpy#559]
Hi,
I'm writing an offline app with interface based on web.py.
I want to hide the logs in the console (GET and POST info) which is running my app but still have the ability to use the `print()` function (I'm printing some technical details in the console).
I'm using Python 2.7 and SUSE Linux Enterprise Server 12 SP3.
I tried to use the solution from cookbook with `toprint = False`, but it didn't do anything.
Am I missing something or is the logging to console compulsory?

**Comment by cclauss** [comment]
I do not know the answer but this would be a nice __test case__ to add to our automated testing.

**Comment by iredmail** [comment]
Didn’t check the “toprint” yet, but maybe a simple “grep” command will do the trick?

**Comment by anandology** [comment]
On Fri, Sep 27, 2019 at 3:01 PM Tomasz Sokołowski <notifications@github.com>
wrote:

> Hi,
> I'm writing an offline app with interface based on web.py.
> I want to hide the logs in the console (GET and POST info) which is
> running my app but still have the ability to use the print() function
> (I'm printing some technical details in the console).
> I'm using Python 2.7 and SUSE Linux Enterprise Server 12 SP3.
>
I don't think web.py does anything special to hide the print output. I'm
assuming that your are using the development server that comes with web.py
and the access log is being printed. Is that correct?

> I tried to use the solution from cookbook with toprint = False, but it
> didn't do anything.
>
Could you please share link to that cookbook article so that we can review
that and fix if required?

**Comment by sokol07** [comment]
> I don't think web.py does anything special to hide the print output. I'm
assuming that your are using the development server that comes with web.py
and the access log is being printed. Is that correct?
Yes, exactly.

> Could you please share link to that cookbook article so that we can review
that and fix if required?
http://webpy.org/cookbook/logging
I don’t say it’s wrong, maybe I miss something. Generally speaking I found such solution in a few articles on reddit and generally speaking it seemed that following the cookbook is a right way to turn off the logging (or at least printing it).

**Comment by iredmail** [comment]
No plan to "fix" this "issue" since the tutorial uses third-party module `wsgilog`, i consider it not a webpy issue. Maybe remove that tutorial too.

**Comment by cclauss** [comment]
@sokol07 Would you be willing fix the tutorial to use Python's builtin __logging__ module instead of __wsgilog__?  It is quite useful to log problems instead of always printing them.

**Comment by sokol07** [comment]
@cclauss I can think about that when I have some spare time but I can't promise when this will be - for the next few weeks I've got quite many things to do and the unnecesary output got rather low priority for now. The second thing is that I don't feel familiar enough with both logging and wsgilog modules to rework the tutorial, I have to read more about them.

**Comment by sokol07** [comment]
@cclauss I had some time today to look into the web.py code and I think I have a clue what's going on.
The logging is handled in `httpserver.py` by function `log(self, status, environ)` in class `LogMiddleware`.
The logging is performed by `print(utils.safestr(msg), file=outfile)` in line 322. However, the "file" parameter in "print" is available only in Python 3 and I'm working in Python 2.7 at the moment.
One solution would be to modify this function to let the user choose whether the log should be printed to console and/or to file (but with file.open etc for Python 2).
Other, simplier solution, letting to turn off the whole logging, which can be done very simply.
The server is started with `runsimple` method, which takes `(func, server_address=("0.0.0.0", 8080))`.
If we modify this and add additional parameter `logging`, we can prevent the logging to be called. To implement the second solution we can modify the lines 156-166 of `httpserver.py` from:
(omitting comments)
```
def runsimple(func, server_address=("0.0.0.0", 8080)):
    """..."""
    global server
    func = StaticMiddleware(func)
    func = LogMiddleware(func)
```
to
```
def runsimple(func, server_address=("0.0.0.0", 8080), logging = True):
    """..."""
    global server
    func = StaticMiddleware(func)
    if logging == True:
        func = LogMiddleware(func)
```

Therefore, in the main application the server would be started with for example:
`web.httpserver.runsimple(app.wsgifunc(), ("127.0.0.1", 6060), False)`

As for the first solution it requires more work but I think it could be called the same way, for example with providing a `log` parameter in `runsimple` with four values: 0 = no log, 1 = log to console, 2 = log to file, 3 = log to file and console. However, at the moment I'm not sure what way of passing this parameter to `LogMiddleware` would be the best.
