### ISSUE TITLE
Discussion: Roadmap of next big release `1.0`

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#562]
Hi @cclauss @anandology 

I guess it's the right time to discuss the roadmap of our next big release, i personally hope it will be named `1.0`, but, whatever.

Thoughts:

- Make it Python 3 only. After removed code for Py2 support, web.py will be even more micro.
  - Make sure all unit tests (`tests/`) works with py3.
- Any new features?
- Any existing issues we must solve?
- License? https://github.com/webpy/webpy/pulls?q=is%3Apr+is%3Aopen+label%3ALICENSE
- Documentation:
  - Any documents we should update or rewrite from scratch?
  - A new, complete tutorial? Maybe a short "Book"? It will be helpful to attractive people to use web.py.
  - Move all documents to something like [GitBook.io](https://www.gitbook.com/) (it's free for open source and non-profit teams) or [Read The Docs](https://readthedocs.org/)?
- website:
  - Re-organize web pages?
  - Re-design the web UI?

**Comment by cclauss** [comment]
We should not focus on removing 2.7 support until after we have [OpenLIbrary](https://archive.org/about/) working on both.  https://www.aaronswartzday.org/open-library/

**Comment by iredmail** [comment]
I suppose that's `0.40`?

I'm ok to continue py2.7 + py3 support in a new branch / release like `0.50`, but it should focus on fixing issues and better py3 support, not implementing new features.

py2 has only 100+ days left before abandoned by PSF, we better move faster.

btw, what's the OpenLibary team's plan to move to py3?

**Comment by cclauss** [comment]
I have been working hard and many others on the OpenLibrary community also have similar PRs...
https://github.com/internetarchive/openlibrary/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed
https://github.com/internetarchive/infogami/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed

We are close
https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Theme%3A+Upgrade+to+Python+3%22
* https://github.com/internetarchive/infogami/pulls

As long as we support Python 3, the PSF will love us.

**Comment by iredmail** [comment]
Any other comments?

**Comment by nestor-alonso** [comment]
Maybe we should create some Dockerfiles, one with webpy and sqlite, other with PostgreSQL, and some with the examples. I'll try to do something like that, and I'd like to share it. Also, we can offer a container with all examples, so developers can be up and running in no-time. Any ideas on this topic.

**Comment by iredmail** [comment]
@nestor-alonso sounds cool, but what's the purpose of docker + web.py?

**Comment by nestor-alonso** [comment]
It is useful because you are giving something that runs, and developers can use our images to build their own images on top of that, so we become part if their CI/CD process . I'm thinking on becoming a framework for microservices: webpy is lightweight, has a great and simple syntax and stays out of the way of developers.

**Comment by anandology** [comment]
Here is my wishlist for 1.0.

- Brand web.py as "RESTful web framework in Python". Even after so many web
frameworks out there, nothing comes close to web.py interms of RESTfulness.
The program structure speaks the API.
- Make web.db a separate library
- Drop support for sessions [1]
- Replace Templetor with Jinja - I'm the one who write most of the current
templator code, but I strongly think there were some initial design
mistakes like using indentation for grouping etc. which makes it very hard
to use. In practice that doesn't well with HTML and often becomes very hard
to troubleshoot. Jinja is very well designed and it is even used in places
outside web frameworks like Ansible. I think it would be good for web.py to
switch to Jinja.
- Replace forms with a better alternative. The forms library has lot of
quirks and there are many libraries out there for form validation. web.py
can drop the current form support and document how to work with each of the
popular libraries.
- Better reloader
- Better documentation
- Profile web.py code, identify any bottlenecks that are present and make
it as fast as possible
- Stay lean as always

[1]: Why sessions are bad -- Aaron Swartz in the web.py mailing list
https://groups.google.com/forum/#!topic/webpy/KHCDcwLpDfA

**Comment by iredmail** [comment]
- The builtin Templetor is handy if you need to write some simple web app with just few pages. But yes Jinja2 is more popular and powerful. I'm ok to replace it.
- I don't use the form module at all. While writing web app, the html code generated by form module is not good enough for CSS styling.
- I personally don't want to drop session module. If you're going to, make sure offering an easy alternative for existing users who're using session, so that they can easily migrate their code.

I think we already collected enough tasks for `1.0`.

**Comment by iredmail** [comment]
I wish the builtin templator could get some improvements and stay.
