### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by kjmph** [webpy/webpy#574]
web.py release: 0.40
Python release: 3.7.3 (Debian buster)

While porting a project from Python 2 to Python 3 (thanks for the 0.40 release!), I immediately encountered a bug in `web.input()`. Apparently, when a POST is sent by `requests` (as opposed to a web browser), web.py emits an error:

```TypeError: write() argument must be str, not bytes```

If debug is enabled, the default, then a stream of errors occur with the a similar error. See this issue for more information https://github.com/webpy/webpy/issues/448.

Sure enough, setting `web.config.debug = False` will prevent the stream of errors, yet the originating error still exists. (Also, I want error handling, I'll address that later).

The source of the error is in `cgi.py`, as it tries and copy the BytesIO object web.py created into a TemporaryFile that was created without `wb+`.

Here is the cgi.py write error:
https://github.com/python/cpython/blob/ef4ec6ed12d6c6200a85068f60483723298b6ff4/Lib/cgi.py#L704

Here is the web.py BytesIO creation:
https://github.com/webpy/webpy/blob/fa27cc510e39af9c32e015c8daf51023a6e80007/web/webapi.py#L443-L444

I am able fix this by monkey patching `cgi.py`, as the source of the error is `make_file`:
https://github.com/python/cpython/blob/ef4ec6ed12d6c6200a85068f60483723298b6ff4/Lib/cgi.py#L814-L842

Here is a test case:
```python
import cgi
import web
import json
import tempfile

urls = (
    '/', 'index'
)

class index:
    def POST(self):
        inputs = web.input()
        data = json.loads(web.data())
        print(inputs, data)
        return "Hello, world!"

def make_file(self):
    return tempfile.TemporaryFile("wb+")

# Comment out this line to reproduce the error                                                                                                                               
cgi.FieldStorage.make_file = make_file

if __name__ == "__main__":
    # Comment this line to see the stream of errors. Note, make_file
    # also needs to be the default, not patched, version.
    web.config.debug = False
    app = web.application(urls, globals())
    app.run()
```

You may test this with httpie:
```shell
$ http -v POST localhost:8080 a=b
```

One last comment, when monkey patching cgi.py, the debugging error page works again.

Is there anything else I can submit to help solve this?

**Comment by cclauss** [comment]
Python 2 makes no destiction between bytes and str but Python 3 strictly enforces that distinction:
```
$ python2 -c "print(bytes == str)"  # True
$ python3 -c "print(bytes == str)"  # False
```
These two utility functions can help:
```python
def to_utf8(s):
    return s if isinstance(s, str) else s.decode('utf-8')

def to_bytes(s):
    return s if isinstance(s, bytes) else s.encode('utf-8')
```
* If s is bytes/str in Python 2 then these functions just return it unmodified.
* if s is bytes in Python 3 then to_utf8() returns it as a str and to_bytes() just returns it unmodified.
* if s is str in Python 3 then to_bytes() returns it as a bytes and to_utf8() just returns it unmodified.

**Comment by kjmph** [comment]
Hello @cclauss, I appreciate the comment, I agree that those utility functions can help. If we look closer at my example, we can see that I am not doing anything outside the tutorial example on http://webpy.org/.

I don't believe this is an issue with a user mishandling encoding, this is inside web.py.

**Comment by kjmph** [comment]
If it is helpful, here is an example that is just a POST:

```python
import web

urls = (
    '/', 'index'
)

class index:
    def POST(self):
        # web.input() throws an error
        inputs = web.input()
        return "Hello, world!"

if __name__ == "__main__":
    app = web.application(urls, globals())
    app.run()
```

Again, trigger the  web.input()` error and the cascading error with the debug page:
```shell
$ http -v POST localhost:8080 a=b
```

**Comment by cclauss** [comment]
@kjmph I was not saying that these functions were the answer to this issue.  I just wanted to make sure that the source was clear.

__six__ has even more comprehensive functions.
https://github.com/benjaminp/six/blob/master/six.py#L854-L909

My issue is line 441 which only does a d.encode("utf-8") on PY2.  Don't we want it to do that decode on both PY2 and PY3?
https://github.com/webpy/webpy/blob/master/web/webapi.py#L441-L444

**Comment by kjmph** [comment]
Ah, I see your point. If we look here at `cgi.py` we see that the actual source of the problem is that `_binary_file` is set to `False`:

https://github.com/python/cpython/blob/ef4ec6ed12d6c6200a85068f60483723298b6ff4/Lib/cgi.py#L444

In other words, are you suggesting that `webapi.py` should be passing in a StringIO?

**Comment by cclauss** [comment]
I read that as `if there is a file then it is a binary file.`

The code easier to scan if it leveraged `dict.get()`:
```
        self.name = pdict.get('name', None)
        self.filename = pdict.get('filename', None)
        self._binary_file = self.filename is not None  # if there is a file then `self._binary_file` is True
```

**Comment by kjmph** [comment]
Ah, I see, `True`. I scanned too quickly. Also, there is this line:

https://github.com/python/cpython/blob/ef4ec6ed12d6c6200a85068f60483723298b6ff4/Lib/cgi.py#L697-L699

So, we know cgi.py expects to receive bytes from the caller.

**Comment by cclauss** [comment]
That makes sense to me.  We should be reading and writing __bytes__.  That means that __BytesIO__ is correct.  I still think that line 441 needs to lose the PY2 qualifier.  We want to convert text_type data to bytes on both PY2 and PY3.

**Comment by kjmph** [comment]
You and I are in agreement, on rereading. We just had a different way of expressing it. It appears `_binary_file` is set to `False` in this case. There is no filename (nor any content-disposition) in the example. Thus, the TemporaryFile is created with `w+` flags. This is why the `self.file.write` fails.

**Comment by cclauss** [comment]
Now I understand.  So we either decode the bytes before writing to the TemporaryFile or we open the TemporaryFile in binary mode.

**Comment by kjmph** [comment]
That is correct, yet if we decode the bytes, `cgi.py` will warn because it expects bytes.

**Comment by kjmph** [comment]
It seems like subclassing FieldStorage, and overriding make_file is the best way to fix this. (better than monkey patching?) Then, this would have to be pushed upstream to CPython.

**Comment by kjmph** [comment]
Is that pull request what you have in mind @cclauss?

**Comment by cclauss** [comment]
```python
>>> import cgi
>>> form = cgi.FieldStorage(encoding="utf-8")
```
From https://docs.python.org/3/library/cgi.html#using-the-cgi-module
> If the form contains non-ASCII characters, use the encoding keyword parameter set to the value of the encoding defined for the document. It is usually contained in the META tag in the HEAD section of the HTML document or by the Content-Type header).

**Comment by kjmph** [comment]
I tested it both ways, and it still failed. This is supported by reading the code, as read_binary will only expect bytes, and TemporaryFile isn't created with bytes. There is no encoding being processed in this case. (Note, I fixed the Pull request to work with Python 2, as make_file args had changed).

**Comment by anandology** [comment]
I'm trying to see if the issue can be reproduced without using web.py at all. 

```
$ cat wsgi.py
import cgi

def app(environ, start_response):
    """Simplest possible application object"""
    fp = environ['wsgi.input']

    print(cgi.FieldStorage(fp=fp, environ=environ))

    status = '200 OK'
    response_headers = [('Content-type', 'text/plain')]
    start_response(status, response_headers)
    return [b'Hello world!\n']

$ gunicorn wsgi:app
[2019-11-02 18:50:57 +0000] [25736] [INFO] Starting gunicorn 19.9.0
[2019-11-02 18:50:57 +0000] [25736] [INFO] Listening at: http://127.0.0.1:8000 (25736)
```

And requesting it fails.

```
$ curl -i -H 'content-type: application/json' -d '{}' http://localhost:8000/
HTTP/1.1 500 Internal Server Error
...
```

And the trackback is:
```
Traceback (most recent call last):
  File "/home/anand/webpy/err/testenv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/anand/webpy/err/testenv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/anand/webpy/err/wsgi.py", line 7, in app
    print(cgi.FieldStorage(fp=fp, environ=environ))
  File "/usr/lib/python3.6/cgi.py", line 566, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 757, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 779, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
``` 

It looks like the issue is with cgi module.

**Comment by kjmph** [comment]
Thanks for that test case @anandology, I agree this should be pushed upstream. I've never used bugs.python.org, is there someone better to represent?

In the meantime, pull request #575, if accepted, would allow web.py to function while waiting for an upstream fix.
