### ISSUE TITLE
RuntimeError('generator raised StopIteration')

### ISSUE THREAD

**Issue by kjmph** [webpy/webpy#576]
web.py version: 0.40
cheroot version: 8.2.1
Python version: 3.7.3 (Debian buster)

To reiterate, thanks again for porting web.py to Python 3. This has been very helpful.

When serving static assets, and the server wants to respond with `304 Not Modified`, web.py raises StopIteration. Now, in most cases, StopIteration is used as an internal exception to tell the web.py to prevent execution of the request handling. In this particular case, it is bubbling up to Cheroot. Here is the stack frame:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/web/httpserver.py", line 239, in __iter__
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1280, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/dist-packages/cheroot/wsgi.py", line 145, in respond
    for chunk in filter(None, response):
RuntimeError: generator raised StopIteration
RuntimeError('generator raised StopIteration')
RuntimeError('generator raised StopIteration')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/web/httpserver.py", line 239, in __iter__
    raise StopIteration()
StopIteration
```

Here is where it is raised in web.py:

https://github.com/webpy/webpy/blob/master/web/httpserver.py#L239

Here is where it is received by cheroot:

https://github.com/cherrypy/cheroot/blob/e175ae41c53930adf2a62fb094537cfbd6000352/cheroot/wsgi.py#L145

Since the function in web.py is a generator, replacing `raise StopIteration()` with a `return` would fix this problem. Would you accept a pull request changing this line? All other `raise StopIteration()` uses in web.py look valid.

**Comment by iredmail** [comment]
> Would you accept a pull request changing this line?

It’s always welcome to create a PR. please also add unit tests for your change.

**Comment by kjmph** [comment]
It is an interesting request for adding a unit test. I tried. There doesn't appear to be a way to serve static files from within unit tests, any advice you can give here? By testing 304s with request handlers, it won't trigger the problem in the `web.httpserver.StaticApp` class. While maybe I could construct my own middleware and replicate StaticApp, it wouldn't be a valuable test in that it would prevent regressions in the future.

Note, as an aside, the tests don't run out of the box on Python 3.7.4. `thread.isAlive` should be `thread.is_alive` in `tests/test_application.py` and `web/session.py` should call `base64.encodebytes` instead of `base64.encodestring`, mirror that with `base64.decodebytes` and `base64.decodestring`.

How about showing this reported issue with pure Python?

```python
def good():
    yield 'hello'
    return

def bad():
    yield 'world'
    raise StopIteration()

for i in good():
    print(i)

for i in bad():
    print(i)
```

Or, recreating this by creating a file in `static/`:

```
$ mkdir static
$ touch static/problem.png
$ cat > app.py
import web

app = web.application((), globals())
app.run()
```

And running this against the application:

```
$ http :8080/static/problem.png
HTTP/1.1 200 
Content-Length: 0
Content-type: image/png
Date: Thu, 07 Nov 2019 01:49:22 GMT
ETag: "1573091358.8372533"
Last-Modified: Thu, 07 Nov 2019 01:49:18 GMT
Server: localhost
$ http :8080/static/problem.png If-None-Match:\"1573091358.8372533\"
HTTP/1.1 304 Not Modified
Date: Thu, 07 Nov 2019 01:49:43 GMT
ETag: "1573091358.8372533"
Server: localhost
$ 
```

You should see the following from the application:

```
$ python3 app.py
http://0.0.0.0:8080/
127.0.0.1:52678 - - [06/Nov/2019 20:49:22] "HTTP/1.1 GET /static/problem.png" - 200 
127.0.0.1:52764 - - [06/Nov/2019 20:49:43] "HTTP/1.1 GET /static/problem.png" - 304 Not Modified
RuntimeError('generator raised StopIteration')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/web/httpserver.py", line 239, in __iter__
    raise StopIteration()
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cheroot/server.py", line 1280, in communicate
    req.respond()
  File "/usr/local/lib/python3.7/site-packages/cheroot/server.py", line 1083, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.7/site-packages/cheroot/wsgi.py", line 145, in respond
    for chunk in filter(None, response):
RuntimeError: generator raised StopIteration
```
