### ISSUE TITLE
Start webpy with raspberry pi

### ISSUE THREAD

**Issue by anhtu91** [webpy/webpy#582]
Hi everyone,

firstly, thank you very much for the very useful library but I still got a problem. I am trying to start my script, which uses webpy, everytime when my raspberry pi starts. Anyway the command window always returns this error:

>     import web
ImportError: No module named web

Any help would be really appreciated...
Thanks in advanced

**Comment by iredmail** [comment]
It means Python can not find web.py module.

Question: How did you install web.py?

**Comment by anhtu91** [comment]
> It means Python can not find web.py module.
> 
> Question: How did you install web.py?
I used the command: pip3 install web.py

**Comment by cclauss** [comment]
https://snarky.ca/why-you-should-use-python-m-pip

**Comment by iredmail** [comment]
hi @anhtu91, did you get your webpy app working?

**Comment by anhtu91** [comment]
> hi @anhtu91, did you get your webpy app working?
Thank you, guys. It is working now
