### ISSUE TITLE
Poor performance at new database libs.

### ISSUE THREAD

**Issue by rrguardo** [webpy/webpy#586]
This old libs combinations works perfect:

* python2.7
* web.py==0.37
* MySQL-python==1.2.5
* dbutils==1.1

If the database pool is enable in threaded (greenlets) services, the database libs works perfect, the service is able to process huge amount of request and connections without delays. The redis default cache pool usually fail before the database pool at those libs.

But with new libs like below, the database pool become slow, even with small service loads we can observe more than 2 seconds delays at database libs and with normal load more than 30 seconds delay at pool processing queries:

* python2.7 (not tested yet with python3.x but guess that could be the same slow?)
* webpy==0.40
* dbutils 1.1 or 1.3
* pymysql or mysql.connector 

[mysqlclient](https://pypi.org/project/mysqlclient/) get the best performance but yet we observe some bottleneck at db libs that was not present at old libs. (database pool maxconnections apparently is not working, maybe it is not compatible with webpy+dbutils combination)

**Comment by rrguardo** [comment]
Maybe if webpy add support to [*mysqlclient*](https://pypi.org/project/mysqlclient/) database driver the new or future libs could rescue the performance lost?

**Comment by anandology** [comment]
@rrguardo  can you provide a sample code to reproduce this issue?

**Comment by rrguardo** [comment]
@anandology Just now read the message, will provide the code in next 24-48 hours.
I can't provide the real code because it is private. But I guess that any other small implementation using same libs will fail/reproduce same errors, I will be working in build a new sample from zero.

**Comment by rrguardo** [comment]
Was working in distinct scripts to test the problem and until now, I am not able to replicate the it locally in ubuntu OS using similar services (gevent StreamServer).

Part of the team believe that problem could be at online servers libs that use FreeBSD.
But problem could be too at a wrapper we use for web.db that somehow is not efficient with new webpy versions.

We are yet researching and busy with other tasks.

**Comment by iredmail** [comment]
Close due to no sample code to reproduce the issue. Feel free to reopen with sample code.
