### ISSUE TITLE
session.py in my windows10, DiskStore [class os.rename(tname, path) ] will trigger exception: IOError [WinError 183]

### ISSUE THREAD

**Issue by qujianbiao** [webpy/webpy#589]
def __setitem__(self, key, value):
        path = self._get_path(key)
        pickled = self.encode(value)
        try:
            tname = path + "." + threading.current_thread().getName()
            f = open(tname, "wb")
            try:
                f.write(pickled)
            finally:
                f.close()
                os.rename(tname, path)  # will trigger exception: IOError [WinError 183]
        except IOError:
            pass

**Comment by cclauss** [comment]
```python
    except IOError as e:
            print(e, str(e))
```

**Comment by qujianbiao** [comment]
IOError [WinError 183] Cannot create a file when that file already exists '.sessions\\ae60004d0026a57faeeeaf537a8ac7e6c6fd7a0b.CP Server Thread-1' -> '.sessions\\ae60004d0026a57faeeeaf537a8ac7e6c6fd7a0b'

**Comment by qujianbiao** [comment]
my python version:
C:\Users\bill>c:\Python35\python.exe --version
Python 3.5.4

**Comment by shanshangzhiren** [comment]
I have the same question, windows7X64,python2.7.17x86,web.py0.40

**Comment by liusp913xx** [comment]
me too
windows 10, python 2.7.17, web.py 0.40

**Comment by cclauss** [comment]
Python 2 is end of life.  https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by iredmail** [comment]
- replacing “os.rename” by “shutil.move” should fix this issue and is more robust.
- although py2 is dead and we are dropping it, this change is still required for py3.
- “shutil” is a builtin module in py3.

**Comment by iredmail** [comment]
Dear @qujianbiao @shanshangzhiren @liusp913xx 

Could you help test my proposal (replacing `os.rename` by `shutil.move`, mentioned in previous reply)? with either web.py 0.40 or 0.50.

I don't have a Windows machine for testing.

**Comment by liusp913xx** [comment]
well done, it really works~
tks



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"iRedMail"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月25日(星期三) 上午9:08
收件人:&nbsp;"webpy/webpy"<webpy@noreply.github.com&gt;;
抄送:&nbsp;"31872132"<31872132@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [webpy/webpy] session.py in my windows10, DiskStore [class os.rename(tname, path) ] will trigger exception: IOError [WinError 183] (#589)





 
Dear @qujianbiao @shanshangzhiren @liusp913xx
 
Could you help test my proposal (replacing os.rename by shutil.move, mentioned in previous reply)? with either web.py 0.40 or 0.50.
 
I don't have a Windows machine for testing.
