### ISSUE TITLE
"None" Value Not Supported in SameSite Directive in setcookie()

### ISSUE THREAD

**Issue by pycarus** [webpy/webpy#592]
Hello,

The SameSite cookie directive has three option: Strict, Lax and None:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies
https://tools.ietf.org/id/draft-ietf-httpbis-rfc6265bis-03.html#rfc.section.5.3.7

Web.py's setcookie() function ignore the "None" value and regards it as equivalent to not setting a value:
https://github.com/webpy/webpy/blob/master/web/webapi.py#L530

As browsers migrate to SameSite=Lax by default (Chrome from Feb 4, 2020), setting SameSite to  "None" is now the only way to support cookies in cross-site requests.

https://www.chromestatus.com/feature/5088147346030592 

Line 530 in webapi.py (https://github.com/webpy/webpy/blob/master/web/webapi.py#L530)

should be changed to:

    if samesite and samesite.lower() in ("strict", "lax", "none"):

**Comment by iredmail** [comment]
Dear @pycarus 

Fix committed, could you please help verify it?

**Comment by pycarus** [comment]
@iredmail Excellent, thanks.

**Comment by iredmail** [comment]
@pycarus Did you test it? Works for you?

**Comment by pycarus** [comment]
@iredmail I did test the fix, it works as expected with Chrome 79 and the relevant flag enabled (chrome://flags/#same-site-by-default-cookies) to simulate how Chrome 80 will handle SameSite="None". The current version of Firefox ignores SameSite="None".
