### ISSUE TITLE
Test cases fail on pypy3

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#598]
https://www.pypy.org can be turned on in GitHub Actions, Travis CI, etc. and then our tests fail on the Python `print()` function.

**Comment by iredmail** [comment]
Please enable pypy3 again and let’s try to fix it.

**Comment by iredmail** [comment]
@anandology Could you help take a look at this pypy3 issue?

Function `print` is correctly disabled in template with py2 + py3, but not pypy3.

**Comment by aisk** [comment]
The [pypy document](https://doc.pypy.org/en/latest/cpython_differences.html#miscellaneous) said:

> the `__builtins__` name is always referencing the `__builtin__` module, never a dictionary as it sometimes is in CPython. Assigning to `__builtins__` has no effect. (For usages of tools like RestrictedPython, see [issue #2653](https://foss.heptapod.net/pypy/pypy/issues/2653/).)

So it's caused by the `__builtins__` can't be overrided in `exec` function. I found there was a workaround for this: shadow the builtins in globals by a function which will raise a `NameError`.
