### ISSUE TITLE
Discuss: drop Travis CI, pgdb and py2, tag new release.

### ISSUE THREAD

**Issue by iredmail** [webpy/webpy#601]
- Replace Travis CI by GitHub Action.
- [x] The only one `pgdb` driver on pypi is not same as the original one, pgdb support is broken for a long time and was not tested in CI. #606 
- [x] Tag and announce a new release? then entirely drop py2 support. Anything else before a new release?

**Comment by iredmail** [comment]
Any comment about a new release? @cclauss @anandology

**Comment by cclauss** [comment]
This [release](https://github.com/webpy/webpy/releases) will support legacy Python?  Let’s call it v0.50.

The release after will only support Python 3.5 and later?  Let’s call it v1.0.

**Comment by iredmail** [comment]
Yes this new release still supports py2.
