### ISSUE TITLE
Should web.py enable Constant and DictComp by default?

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#609]
https://stackoverflow.com/questions/58518448/how-to-fix-execution-of-constant-statements-is-denied-error

**Comment by iredmail** [comment]
It was fixed already:
- `Constant`: https://github.com/webpy/webpy/blob/master/web/template.py#L1270
- `DictComp`: https://github.com/webpy/webpy/blob/master/web/template.py#L1290`
