### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [webpy/webpy#613]
Could you tag a new release? I want to package it for gentoo but the last release fails tests.

**Comment by iredmail** [comment]
cc @anandology @cclauss 

If there's no urgent issues left, it's time to tag a new release.

**Comment by cclauss** [comment]
I would also like to start testing it on https://github.com/internetarchive/openlibrary

**Comment by Alessandro-Barbieri** [comment]
Even a minor release is fine

**Comment by cclauss** [comment]
Does gentoo still need to support Python 2 or has it gone Python 3-only?

**Comment by Alessandro-Barbieri** [comment]
Gentoo is removing all py2 only packages, the interpreter is still around but will be removed (I hope soon)

**Comment by cclauss** [comment]
Why are our GitHub Actions failing?

**Comment by iredmail** [comment]
> Why are our GitHub Actions failing?

@cclauss Fixed in #614

**Comment by cclauss** [comment]
I think we are ready for the new release.

**Comment by iredmail** [comment]
> I think we are ready for the new release.

Just do it. :)

**Comment by cclauss** [comment]
;-). I am not a [PyPI maintainer](https://pypi.org/project/web.py/) of this package so I think that @anandology is the only one who has rights to publish a new version to PyPI.

**Comment by iredmail** [comment]
> ;-). I am not a [PyPI maintainer](https://pypi.org/project/web.py/) of this package

Me either.

@anandology could you please grant the permission on pypi too?

**Comment by iredmail** [comment]
New release tagged: `0.50`.
