### ISSUE TITLE
cheroot as optional dependency

### ISSUE THREAD

**Issue by stroeder** [webpy/webpy#624]
Is cheroot really required? I run my web apps via uwsgi without cheroot just fine. Thus I'd like to avoid having to install cheroot and its dependencies.

**Comment by iredmail** [comment]
cheroot is not required if you run your web.py application with other wsgi/cgi/fastcgi server like uwsgi, gunicorn, etc. But it's required if you run it with command `python your-app.py` directly, it's used as builtin wsgi server.

I personally prefer to remove cheroot, then no any dependent external packages.

**Comment by iredmail** [comment]
hi @cclauss @anandology 

What's your opinion about removing `cheroot`?

- No one run `pythonX app.py` (and/or proxy requests in Nginx) in production.
- We can document in `README.md` and ask users to install tools like `gunicorn` or `uwsgi` to run web.py app as wsgi application in development mode, also setup Nginx/Apache/... web servers to proxy the http requests.

**Comment by cclauss** [comment]
I have no opinion on this topic.

**Comment by iredmail** [comment]
> I have no opinion on this topic.

Does this mean either removing or keeping it is ok for you?

**Comment by cclauss** [comment]
For me, things are OK the way they are.  I believe that there is a lot to be said for "_It works out of the box".

If others feel passionately and can justify why multiple projects should change the way they install web.pyand are willing to modify our example code to work simply then I would listen to their reasons.
