### ISSUE TITLE
version 0.51 not in master branch

### ISSUE THREAD

**Issue by stroeder** [webpy/webpy#625]
Is it intentional that version 0.51 is only present in branch py2?

**Comment by stroeder** [comment]
Content of _ChangeLog.txt_ is very confusing regarding Python 2:
- it says in both branches: `0.40` is the last release which supports Python 2 but branch _py2_ contains version 0.50 and 0.51
- in branch _master_ there's an entry for version 1.0 prepared which explicitly mentions that Python 2 support was dropped but version 0.51 is missing therein

For me it's not clear whether support for Python 2 was really dropped.

Background for my nit-picking:
- Should downstream packagers assume that web.py 0.51 shall not be packaged for Python 2 anymore?
- Can  downstream packagers rely on 0.51 to be an officially released version?

**Comment by cclauss** [comment]
Anything before v1.0 should support legacy Python.
Anything >= v1.0 should __not__ support legacy Python.

**Comment by iredmail** [comment]
I'm sorry guys, i made a mistake yesterday.

I removed 0.50 on pypi and prepared a new package, but pypi doesn't allow uploading file with same version number. Had to tag 0.51 for this purpose and now leads to chaos. 😂

**Comment by anandology** [comment]
@iredmail, could you please create a branch for 0.51 and add the new changes that went to the 0.51 release? It important to retain a reference to every release.

You can release 0.52 one we figure out the setup.py/MANIFEST issues.

**Comment by iredmail** [comment]
@anandology You can switch to py2 branch instead: `git checkout py2`. It's reserved branch for py2 support if we have some bugs in 0.5x.
