### ISSUE TITLE
GitHub prevent push to master branch

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#632]
It is too easy to push directly to master.  We should force everyone (or at least me) to go through the pull request process before changes land on the master branch.
https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions

**Comment by iredmail** [comment]
I don't have such privilege, let's call @anandology :)

**Comment by iredmail** [comment]
Still no update from @anandology ... too sad.

@cclauss don't be afraid to push to master mistakenly, we can revert the commit.

**Comment by anandology** [comment]
On Tue, Jun 9, 2020 at 6:42 PM iRedMail <notifications@github.com> wrote:

> Still no update from @anandology <https://github.com/anandology> ... too
> sad.
>
> @cclauss <https://github.com/cclauss> don't be afraid to push to master
> mistakenly, we can revert the commit.
>
Sorry, some how I missed this one.

Done now.

Anand

**Comment by iredmail** [comment]
Thanks @anandology 

If you have some time, we have some issues pending on you. :)
