### ISSUE TITLE
PR #575 breaks multipart forms with long text parts

### ISSUE THREAD

**Issue by GuillaumeDerval** [webpy/webpy#635]
PR #575 (issue #574) attempts to circumvent an upstream issue with the CGI lib (https://bugs.python.org/issue27777, candidate patch: https://github.com/python/cpython/pull/11764), by forcing all "files" created by `cgi.FieldStorage` to be binary ones.

Sadly, this breaks multipart forms with very long text parts.

How to reproduce:
```
import web

urls = (
    '/', 'index'
)

class index:
    def GET(self):
        return """<form method="post" action="/" enctype="multipart/form-data">
<textarea name="lol"></textarea>
<button type="submit">submit</button>
</form>"""
    def POST(self):
        return str(web.input())

app = web.application(urls, globals())

if __name__ == "__main__":
    app.run()
```

Then start the app and give a very long text to the textarea (10 paragraphs of https://www.lipsum.com/ do the trick).

I think the PR #575 should be reverted, however I don't have any fix for the bug it "solves", apart from monkey-patching the cgi lib with the candidate upstream fix in the meantime...

**Comment by bpluly** [comment]
There's a PR on the cgi library issue https://github.com/python/cpython/pull/10771 though it needs improving (it uses readline rather than reading the content length), it is likely good enough for most cases. So, for me it makes more sense to take the patched cgi.lib than fix it in a dependent framework, where it can't really be fixed.

**Comment by tfmorris** [comment]
`cgi` is no longer used, so this may no longer be a problem. If it is, a good start would be a failing (automated) test case.

**Comment by cclauss** [comment]
Fixed in
* #773
