### ISSUE TITLE
No module named `flup.server.fcgi`

### ISSUE THREAD

**Issue by abitrolly** [webpy/webpy#638]
I am trying to run [this old code](https://github.com/osm-by/OpenStreetMap.by/blob/a2aa04d022f06bf8ee82f6de036cd61a37604907/index.py#L684-L687) and there is an error coming from the depths of 0.51 `web.py`
```
✗ python index.py                
Traceback (most recent call last):
  File "index.py", line 687, in <module>
    app.run()  # standalone run
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/web/application.py", line 375, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "index.py", line 685, in <lambda>
    web.wsgi.runwsgi = lambda func, addr=None: web.wsgi.runfcgi(func, addr)
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/web/wsgi.py", line 17, in runfcgi
    import flup.server.fcgi as flups
ImportError: No module named flup.server.fcgi
```

**Comment by cclauss** [comment]
[Which `flup`](https://pypi.org/search/?q=flup) is being installed?  `flup`, `flup6`, or `flup-py3`?

Given that Python 2 is end of life, have you tried running this on Python 3?

**Comment by abitrolly** [comment]
@cclauss the code I am trying to launch is not Python 3 ready. I have no idea which `flup` is needed - expected `pip install wep.py` to fetch all required dependencies automatically.

**Comment by abitrolly** [comment]
With `pip install flup` now the problems is different.
```
Traceback (most recent call last):
  File "index.py", line 687, in <module>
    app.run()  # standalone run
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/web/application.py", line 375, in run
    return wsgi.runwsgi(self.wsgifunc(*middleware))
  File "index.py", line 685, in <lambda>
    web.wsgi.runwsgi = lambda func, addr=None: web.wsgi.runfcgi(func, addr)
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/web/wsgi.py", line 17, in runfcgi
    import flup.server.fcgi as flups
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/flup/server/fcgi.py", line 54, in <module>
    from .fcgi_base import BaseFCGIServer, FCGI_RESPONDER
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/flup/server/fcgi_base.py", line 45, in <module>
    import _dummy_thread as thread
ImportError: No module named _dummy_thread
```

**Comment by cclauss** [comment]
https://stackoverflow.com/questions/8589008/python-2-7-import-flup-error

**Comment by abitrolly** [comment]
@cclauss yes, `pip install flup==1.0.2` helped. Now I've stuck with this. 
```
✗ python ./index.py        
WSGIServer: missing FastCGI param REQUEST_METHOD required by WSGI!
WSGIServer: missing FastCGI param SERVER_NAME required by WSGI!
WSGIServer: missing FastCGI param SERVER_PORT required by WSGI!
WSGIServer: missing FastCGI param SERVER_PROTOCOL required by WSGI!
Status: 404 Not Found
Content-Type: text/html; charset=utf-8

not found%                                             
```

**Comment by abitrolly** [comment]
[The code](https://github.com/osm-by/OpenStreetMap.by/blob/a2aa04d022f06bf8ee82f6de036cd61a37604907/index.py#L684-L687) that produces the error is dealing with starting `web.py` handlers for Apache in standalone mode.
```
...
if __name__ == "__main__":
    web.wsgi.runwsgi = lambda func, addr=None: web.wsgi.runfcgi(func, addr)
    app = web.application(urls, globals())
    app.run()  # standalone run

application = web.application(urls, globals()).wsgifunc()  # mod_wsgi
```

**Comment by abitrolly** [comment]
I removed this line from the snippet above, and `index.py` started successfully.
```
    web.wsgi.runwsgi = lambda func, addr=None: web.wsgi.runfcgi(func, addr)
```
No idea what it does. It was added as a part of this huge `formatting fix` https://github.com/osm-by/OpenStreetMap.by/blob/5b940417230aafca92b80c05e82efb31077d70db/index.py Could be a wrong debugging code.

There is another missing dependency though.
```
...
  File "./index.py", line 571, in face_main
    render = render_cheetah('templates/')
  File "/virtualenvs/OpenStreetMap.by-MOXOekcf/lib/python2.7/site-packages/web/contrib/template.py", line 20, in __init__
    from Cheetah.Template import Template
ImportError: No module named Cheetah.Template
```
Maybe add those missing dependencies as optional components to https://github.com/webpy/webpy/blob/master/requirements.txt ?

**Comment by cclauss** [comment]
https://github.com/webpy/webpy/search?q=Cheetah&type=Commits

**Comment by abitrolly** [comment]
@cclauss that's why it is `web.contrib.template`? I don't see why it could not be an optional dependency - just for people to be aware that there is such possibility.

**Comment by abitrolly** [comment]
After installing `cheetah` the web page finally rendered. But instead of static resources, `web.py` returns HTML. Perhaps removed line is connected to an attempt to fix that?

![image](https://user-images.githubusercontent.com/8781107/80099616-6af0f480-8577-11ea-8d9c-276cc6e6ed61.png)

**Comment by abitrolly** [comment]
Sounds like there is [no mechanism](https://webpy.org/cookbook/staticfiles) in `web.py` to serve static resources for development. But that's another problem.

I guess the issue with `flup` can be closed. Or I can send you a patch for optional dependencies to `requirements.txt` if you can explain me the use cases for `flup` in `web.py` code.

**Comment by iredmail** [comment]
Flup is mentioned on https://webpy.org/install:

> To run web.py with CGI, FastCGI or SCGI you will need to install flup.

Nowadays we prefer WSGI for better performance, in this purpose, package `cheroot` is used and already added in `setup.py` as dependence.

**Comment by abitrolly** [comment]
@iredmail can those `install` docs mention `flup` only in specific cases where it is needed?

**Comment by cclauss** [comment]
I think those docs need be modified to point to the [Python 3 version](https://pypi.org/project/flup-py3) so:
`python3 -m pip install flup-py3`

**Comment by abitrolly** [comment]
@cclauss what's the point pointing to package that is not used?

**Comment by cclauss** [comment]
Some users may _optionally choose_ to use flup which is why it is documented.  If they choose to do so, it would be better if they do not install the version designed to work with legacy Python.

**Comment by abitrolly** [comment]
@cclauss what is the reason for them to install `flup`? As a new user maybe I need that too.

**Comment by cclauss** [comment]
> what is the reason for them to install flup?

iredmail answered that above https://github.com/webpy/webpy/issues/638#issuecomment-618427885

> As a new user maybe I need that too.

You already did... https://github.com/webpy/webpy/issues/638#issuecomment-618279990

**Comment by abitrolly** [comment]
Missed that part. My bad. I guess it can be closed then. No need to keep it lingering.

Just in case, here is the info how to add optional dependencies to `requirements.txt`
https://stackoverflow.com/questions/3664478/optional-dependencies-in-a-pip-requirements-file
