### ISSUE TITLE
How to run standalone server on `localhost`?

### ISSUE THREAD

**Issue by abitrolly** [webpy/webpy#639]
I don't want to risk running `web.py` development server open to local network. What is the official way to modify the code below to run on `localhost` `127.0.0.1`?
```
...
if __name__ == "__main__":
    app = web.application(urls, globals())
    app.run()  # standalone run
```

**Comment by iredmail** [comment]
Easy, if you run webpy code directly, just specify the IP address and port on command line:

```
python code.py 127.0.0.1:808
```

If you run webpy code with a web server like Apache/Nginx, handle it in Apache/Nginx. :)

**Comment by abitrolly** [comment]
@iredmail I want to run `code.py` without additional command line parameters to make it secure by default.

**Comment by abitrolly** [comment]
@iredmail can I refer to this as to officially recommended hack for securely running `web.py`? :)
```
if __name__ == "__main__":
    if not sys.argv[1:]:
        sys.argv.append('127.0.0.1')
    app = web.application(urls, globals())
    app.run()
```
