### ISSUE TITLE
Reusing StaticApp for serving static files outside of `./static` dir

### ISSUE THREAD

**Issue by abitrolly** [webpy/webpy#640]
There are two reasons not to serve static files with `web.py`.

1. It is slow to pipe file through Python
2. It might be a security risk

Both of these points are not addressed in https://github.com/webpy/webpy.github.com/blob/master/cookbook/staticfiles.md leaving the user to guess.

For my purpose - debugging a legacy web app built with `web.py` - a knowledge how to serve static resources not only from `./static` dir, would help greatly. Like serving a single https://127.0.0.1/favicon.ico

I found two pieces of puzzle that might work togethre - [`StaticApp`](https://github.com/webpy/webpy/search?q=staticapp&unscoped_q=staticapp) and https://webpy.org/cookbook/subapp but I have no idea yet how to bind them together. Any hints how to reuse `StaticApp` for serving a single file would help.

**Comment by iredmail** [comment]
You can use the webpy builtin web server for development, then use a standalone web server in production.

**Comment by abitrolly** [comment]
@iredmail yes, this question is about `web.py` builtin web server.

**Comment by abitrolly** [comment]
I took https://github.com/webpy/webpy/blob/16de3147e61aa4dc735efa116c50603707fb0683/web/httpserver.py#L257 for the inspiration and came up with the middleware that services all files that exist under web site root directory.
 
It might be totally insecure for closed source and for somebody who store secrets in the directory with sources. However, I could not traverse to parent directory for some reason. :D

Perfectly fine for development. And for code sharing. )

```python
  if __name__ == "__main__":
      app = web.application(urls, globals())

      def root_static(app):
          class RootMiddlewire:
              def __call__(self, environ, start_response):
                  path = environ.get("PATH_INFO", "")
                  relpath = path[1:]  # strip leading "/" if exists
                  if os.path.isfile(relpath):
                      return web.httpserver.StaticApp(environ, start_response)
                  else:
                      return app(environ, start_response)
          return RootMiddlewire()

      app.run(root_static)
```

**Comment by abitrolly** [comment]
I changed the title to clarify what it is all about. Not sure if it is better, though. )
