### ISSUE TITLE
sql query results cannot be accessed using the dictionary key . 

### ISSUE THREAD

**Issue by abhijitnarvekar** [webpy/webpy#643]
hi,
I have a sample setup with a Postgresql DB. A table in the database is as below: 

```
create table cdt0001 (
email varchar(100) not null, 
salt bytea, 
passcode bytea, 
expires timestamp default now() + Interval '1 year' ) ; 
```

Further, I use web.query to read the table cdt0001 with the following code: 

`creds = db02.select(' cdt0001', vars ={'user': i.uname}, where="email = $user", what="salt, passcode" )`

Note: I have tried using  db02.query and the results are the same. 

Then, I try to access the dictionary creds as follows: 
```
    print(bytes(creds[0]['salt'])) 
    print(bytes(creds[0]['passcode'])) 
```

I receive an IndexError only for the second print statement. It is as follows: 
```
SyntaxError('invalid syntax', ('/home/abhijit/.local/lib/python3.6/site-packages/web/debugerror.py', 8, 12, '    def with (exception_type, exception_value, frames)\n'))
Traceback (most recent call last):
  File "/home/abhijit/.local/lib/python3.6/site-packages/web/application.py", line 290, in process
    return self.handle()
  File "/home/abhijit/.local/lib/python3.6/site-packages/web/application.py", line 281, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/abhijit/.local/lib/python3.6/site-packages/web/application.py", line 531, in _delegate
    return handle_class(cls)
  File "/home/abhijit/.local/lib/python3.6/site-packages/web/application.py", line 509, in handle_class
    return tocall(*args)
  **File "/home/abhijit/folder2/views.py", line 58, in POST
    print(bytes(creds[0]['passcode']))
  File "/home/abhijit/.local/lib/python3.6/site-packages/web/db.py", line 536, in __getitem__
    raise IndexError("already passed " + str(i))
IndexError: already passed 0**
```

To mitigate I use a for loop. And it works. 
```
    for a in creds:
      print(bytes(a['salt']))
      print(bytes(a['passcode']))
```

**Comment by iredmail** [comment]
FYI: https://webpy.org/cookbook/select

> The query result ... is __an iterator__ of dict-like storage items, you can access them like below:

If you want to access it with your code like below:

```
creds = db02.select(...)

print(bytes(creds[0]['salt']))
print(bytes(creds[0]['passcode']))
```

Convert the result to list first:

```
qr = db02.select(...)
creds = list(qr)
print(bytes(creds[0]['salt']))
print(bytes(creds[0]['passcode']))
```

**Comment by abhijitnarvekar** [comment]
thanks iredmail. Hopefully the page `https://webpy.org/cookbook/select   `  could be updated to include your remarks on how to utiize the results of an SQL query. I am referring to the section '_The query result (results in above example) is an iterator of dict-like storage items, you can access them like below:_ ' It does not refer to converting the iterator to a list. And I admit to following it lamely.

**Comment by iredmail** [comment]
Updated: https://webpy.org/cookbook/select
