### ISSUE TITLE
Cannot set session cookie to be a "Session" cookie

### ISSUE THREAD

**Issue by pbuckner** [webpy/webpy#655]
0.41 ignored session 'timeout', when setting session cookie & always set the cookie to expire with the browser session.

For some reason 0.50 sets the cookie to have a duration (always) and to set that duration to the value of session 'timeout'.

The problem is there is now no way to return to previous behavior and set a browser Session cookie. web.config.session_parameters['timeout'] must be numeric and must be > 0, as it is _always_ used as the value for session cookie timeout.

If I set session_timeout to 0, login will always fail (because session is too old).
If I set session_timeout to 10, a user who is idle for ten seconds will have their session killed.
If I set session_timeout to 2 days, a user who is idle for two days will have their session killed (I can deal with that), BUT, because the cookie isn't a Session Cookie, it also means if the browser is closed AND A DIFFERENT USER ACCESSES COMPUTER they're logged in as the previous user.

This does not implement a useful "remember-me" feature, though it appears that was the hope.

Needed: some way to force browser Session Cookie.

**Comment by pbuckner** [comment]
Possible solution:
1) add parameter to web.config.session_parameters (session.py line 33), call is "cookie_session_only": False
2) Remove expires=self._config.timeout from def _save() (session.py line 161) -- this isn't needed anywhere
3) Modify  web.setcookie() within def _setcookie() (session.py line 173) to be something like:
expires = '' if self._config.cookie_session_only else (expires or self._config.timeout)

... that's how I'll be modifying my copy & it seems to work fine for my purposes.

**Comment by bpluly** [comment]
If you create a pull request it seems a reasonable thing to merge on the face of it.
Though I avoid sessions and cookies so far as I'm able.

**Comment by iredmail** [comment]
Fixed in PR #684. Could you help test it?

**Comment by pbuckner** [comment]
Yes, changes made to session.py with #684 fix this issue.

**Comment by iredmail** [comment]
Thanks for the feedback. :)
