### ISSUE TITLE
Release version 0.60

### ISSUE THREAD

**Issue by anandology** [webpy/webpy#658]
Release version 0.60 with the current master. Also the document the process for making future releases.

**Comment by anandology** [comment]
Tasks for making a new release.
- [ ] Bump the version in `web/__init__.py`
- [ ] Update the ChangeLog.txt and mark the release date in ChangeLog.txt
- [ ] build dist of the package and publish on pypi
- [ ] Update the documentation on the website

**Comment by iredmail** [comment]
- [ ] Check `README.md` and update if necessary.

**Comment by anandology** [comment]
Pushed to the documentation changes to webpy.github.com directly mistake instead of creating a PR.

**Comment by anandology** [comment]
@iredmail did I miss anything?

**Comment by iredmail** [comment]
Document the detailed commands for task “ build dist of the package and publish on pypi”.

This issue is kind of checklist, but lack of tech details for some task(s).

See https://github.com/webpy/webpy/issues/629

**Comment by anandology** [comment]
Updated the checklist with command to upload to pypi.

**Comment by iredmail** [comment]
Not yet finished, see https://github.com/webpy/webpy/pull/628

We need to save this checklist and related commands/files in git repo, someday we may leave this project, we can simply ask further developers to check the document.

**Comment by cclauss** [comment]
I added a new bullet to the [top of the checklist](https://github.com/webpy/webpy/pull/662#issue-455942282) to cover that.  Are we still missing something?

**Comment by iredmail** [comment]
Seems quite complete. 👍
