### ISSUE TITLE
"Yank" release v0.60 from PyPI

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#665]
[Web.py v0.61 is now released on PyPI](https://pypi.org/project/web.py) via #662 adds `python_requires='>=3.5'` so this release will not install on Python<3.5.

Please go into the [PyPI web pages](https://pypi.org/project/web.py/0.60/#history) and ["_yank_"](https://pypi.org/help/#yanked) the previous v0.60 release so that `python2 -m pip install --upgrade web.py` no longer fails.  Yank is a reversible process, unlike PyPI delete.  My PyPI rights allow me to publish a release but not [yank](https://twitter.com/di_codes/status/1253166894158417926) one.

**Comment by cclauss** [comment]
@iredmail Do your PyPI rights allow you to yank release v0.60?

**Comment by anandology** [comment]
Done.
