### ISSUE TITLE
Support for Python's builtin breakpoint()

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#667]
https://docs.python.org/3/library/functions.html#breakpoint exists as a builtin function in Python >= 3.7 and would help to developers to step through the execution of code in templates.  Today I get `NameError: name 'breakpoint' is not defined` if I attempt to use it in a web.py template.

How would I enable the use of [__breakpoint()__](https://docs.python.org/3/library/functions.html#breakpoint) in web.py templates?  The following does _not_ seem to work.
```python
        try:  # Enable templates to call builtin breakpoint()
            breakpoint  # a builtin function in Python >= 3.7
            if "breakpoint" not in web.template.TEMPLATE_BUILTIN_NAMES:
                web.template.TEMPLATE_BUILTIN_NAMES.append('breakpoint')
        except NameError:
            pass
```

**Comment by anandology** [comment]
Try this:

```
globals = {'breakpoint': breakpoint}
render = web.template.render('templates', globals=globals)
```
