### ISSUE TITLE
ResourceWarning: unclosed file <_io.TextIOWrapper

### ISSUE THREAD

**Issue by stroeder** [webpy/webpy#670]
with-statement should be used when calling open() to avoid this warning (when running on Python 3.8):

/usr/lib/python3.8/site-packages/web/template.py:1090: ResourceWarning: unclosed file <_io.TextIOWrapper name='/opt/ae-dir/etc/ae-dir-pwd/templates/en/requestpw_action.html' mode='r' encoding='utf-8'>
   open(path, encoding="utf-8").read(), filename=path, **self._keywords
 ResourceWarning: Enable tracemalloc to get the object allocation traceback

**Comment by iredmail** [comment]
This PR should be closed by https://github.com/webpy/webpy/commit/76c5c7d23000b49d87318745b4bc9a9676f7e143
