### ISSUE TITLE
I got an error in python3.8

### ISSUE THREAD

**Issue by colinshin** [webpy/webpy#673]
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\web\application.py", line 278, in process
    return p(lambda: process(processors))
  File "C:\Python38\lib\site-packages\web\session.py", line 99, in _processor
    self._cleanup()
  File "C:\Python38\lib\site-packages\web\session.py", line 203, in _cleanup
    if current_time - self._last_cleanup_time > timeout:
TypeError: '>' not supported between instances of 'float' and 'tuple'

the error occurs in the following methods

    def _cleanup(self):
        """Cleanup the stored sessions"""
        current_time = time.time()
        timeout = self._config.timeout
        if current_time - self._last_cleanup_time > timeout:
            self.store.cleanup(timeout)
            self._last_cleanup_time = current_time

**Comment by colinshin** [comment]
Fix it  like below works. Webpy version is 0.61
if current_time - self._last_cleanup_time > timeout   ----->if current_time - self._last_cleanup_time > timeout[0]:

**Comment by iredmail** [comment]
Is it possible that you incorrectly set the session timeout value to a triple?

**Comment by cclauss** [comment]
https://github.com/webpy/webpy/blob/master/web/session.py#L36 should set it to an int.

**Comment by colinshin** [comment]
@cclauss  @iredmail  it's my fault. I set it wrong.
