### ISSUE TITLE
 The route matching request method should be lowercase

### ISSUE THREAD

**Issue by 52lemon** [webpy/webpy#674]
The route matching request method should be lowercase. Like "GET, POST, DELETE,PUT". It always prompt that the function name should be lowercase ，which does not conform to the pep8 specification

**Comment by cclauss** [comment]
That would seem like a breaking change to me.

**Comment by iredmail** [comment]
Yes it will break almost all existing webpy applications.

An alternative is adding an argument like `lowercase_http_methods=True` (defaults to `False`) while creating webpy application like this:

```
app = web.application(urls, globals(), lowercase_http_method=True)
```

Some other changes may be required.

Source code: https://github.com/webpy/webpy/blob/master/web/application.py#L52

**Comment by bpluly** [comment]
I wouldn't like to see this implemented. While a switch would make it fairly invisible to existing code it breaks all examples, ie documentation as well, and its functionally without benefit. Style should not impact function and in this case it would.

**Comment by iredmail** [comment]
No plan to implement this. Issue closed.
