### ISSUE TITLE
NotADirectory Error

### ISSUE THREAD

**Issue by frostback13** [webpy/webpy#680]
When a session has expired and web.py creates a new session. the code that attempts to cleanup (i.e., delete) the old session file generates a NotADirectory error.  The cause of the error is the use of shutil.rmtree(path) to remove a file.  It only works if the argument is a directory.  To correct this, change the line to os.remove(path).

Note: I am not (yet) set up to work properly with git and do a pull request.  Since this change is trivial, I hope that you will accept a simple snippet of code showing the change.  Also, I am new to this code base so it is possible that I am missing something in how the code operates, so please confirm that this is the correct change.  Looks good to me and is working for me.  But what do I know anyway.

The change is in sessions.py

248 class Diskstore(Store):
<snip>
310    def cleanup(self, timeout):
311        if not os.path.isdir(self.root):
312            return
313
314        now = time.time()
315        for f in os.listdir(self.root):
316            path = self._get_path(f)
317            atime = os.stat(path).st_atime
318            if now - atime > timeout:
319                shutil.rmtree(path)  ---> Change this line to os.remove(path)

**Comment by iredmail** [comment]
hi @frostback13, could you help test the fix in PR #681?

**Comment by frostback13** [comment]
The code looks correct to me and it works (for my use case) in my application.

**Comment by danieldean** [comment]
I have just encountered this same issue and cloning the repo and installing from there works for me too.

Thanks for fixing.

**Comment by iredmail** [comment]
@danieldean Thanks for the feedback.
