### ISSUE TITLE
can't empty session storage list

### ISSUE THREAD

**Issue by rbckman** [webpy/webpy#683]
This has been working flawlessly in the past version but since I upgraded to new version 0.61 I can't set a session storage value to None or 0 once it has had another value other than that.

Pretty bad since I use it to store shopping cart items, now I need to kill session if I want to empty the cart.

**Comment by iredmail** [comment]
I will try to check source code and figure it out, but if you can help find it, that would be better for me. :)

**Comment by iredmail** [comment]
Do you have some code to help us reproduce the issue? It will help a lot otherwise I have to check source code “blindly”.

**Comment by rbckman** [comment]
Hey, I can help find, will check source later today.

But basically I think u can reproduce it by giving a value to a session storage object, eg. 1 and then try to give it 0. 

Tisdag den 20 oktober 2020 skrev iRedMail:

**Comment by rbckman** [comment]
ok, so haven't had time to go check source code but wrote a minimalistic code to reproduce this bug, https://tarina.org/webpybughunt/files.html

will have time to go into web.py source tomorrow.

**Comment by iredmail** [comment]
I can not reproduce the issue with your sample code. Tested on FreeBSD 12.1-p10, Python 3.8.6, web.py-0.61 (stable release, not the git clone edition).

**Comment by rbckman** [comment]
ok, I havent been clear enough. Updated the repo to be much clearer. Here's a live version https://dev.tarina.org/

**Comment by rbckman** [comment]
Same thing occurs on 3 different Debian boxes with latest stable and python 3.7.3. Running apache2 and web.py-0.61

**Comment by iredmail** [comment]
Fixed in PR #684, could you please help test it?

**Comment by rbckman** [comment]
YES! ! it works!!! thank you so much <3 wowoweewaa

**Comment by iredmail** [comment]
Great. it's now waiting for reviewers to approve the PR.
