### ISSUE TITLE
dead link in documentation

### ISSUE THREAD

**Issue by UweSauter** [webpy/webpy#691]
Dear webpy website admins,

I found a dead link in the tutorial section (https://webpy.org/docs/0.3/tutorial#forms):

The form module of web.py allows the ability to generate html forms, get user input, and validate it before processing it or
adding it to a database. If you want to learn more about using the module forms web.py, see the Documentation (working ->
https://webpy.org/docs/0.3/) or direct link to Form Library (dead -> https://webpy.org/form).

Regards,

Uwe

**Comment by iredmail** [comment]
Fixed: https://github.com/webpy/webpy.github.com/commit/170ab7e05a8b0d1343c894aa9b67a53104b546b1

**Comment by UweSauter** [comment]
Hi,

I found one more:

https://webpy.org/docs/0.3/ -> Component Documentation -> Forms. Dealing with user input

**Comment by iredmail** [comment]
Fixed seconds ago before your post. :)
