### ISSUE TITLE
How to use multiple submit buttons?

### ISSUE THREAD

**Issue by UweSauter** [webpy/webpy#693]
Hi there,

I'm not a web developer so I just might have not enough background to solve this on my own.

What I'm trying to figure out is: If I have a form with several submit buttons, how can I recognize which one was pressed to submit that form?

In the following minimal (non-)working example, I'm looking for what is called `.was_pressed()` in there:

`app.py`
```
#!/usr/bin/env python3

import web

urls = ('/', 'Index')

render = web.template.render('templates/')

myform = web.form.Form(
    web.form.Button("red", type="submit", description="Register"),
    web.form.Button("green", type="submit", description="Register"),
    web.form.Button("blue", type="submit", description="Register"),
)

def process_form(form):
    if form.get('red').was_pressed():
        return 'You pressed red.'
    elif form.get('green').was_pressed():
        return 'You pressed green.'
    return 'You pressed blue.'

class Index:
    def GET(self):
        f = myform()
        return render.index(f)

    def POST(self):
        f = myform()
        return process_form(f)

if __name__ == '__main__':
  app = web.application(urls, globals())
  app.run()
```
`templates/index.html`
```
$def with (form)

<form method="POST">
    $:form.render()
</form>
```

Any hints are appreciated.

EDIT: Typo

**Comment by iredmail** [comment]
Try to add `value=` like this:

```
    web.form.Button("red", type="submit", description="Register", value="red"),
```

Note: i don't think you should use multiple buttons, instead you should use another input element (maybe "radio" box) to identify the "red", "green", "blue" things.

**Comment by UweSauter** [comment]
I've already tried this in a more complex scenario (values for login and password are only given while development):

```
[…]
query_form = form.Form(
    form.Textbox('server', description='Login server', value='qb1'),
    form.Textbox('login', description='Username', value='testuser'),
    form.Password('password', description='Password', value='testpw'),
    form.Button('submit', html='List tenants', value='list_tenants'),
    form.Textbox('tenant', description='Tenant name'),
    form.Button('submit', html='Show tenant details', value='show_tenant'),
)
[…]
```
but when processing this, I always get the first submit button, not the one that was pressed:
```
def process_form(form):
    action = form.get('submit').value
    server = form.get('server').value
    user = form.get('login').value
    password = form.get('password').value
    if action == 'list_tenants':
        return list_tenants(server, user, password)
    elif action == 'show_tenant':
        tenant = form.get('tenant').value
        return show_tenant(server, user, password, tenant)
```
I suspect this is because in this example both submit buttons have the name `'submit'`.
So even if I would change the names the problem would still exist that I cannot decide which one was used to post the form (as in the first example).
Using radio boxes or a dropdown menu to select the action would probably work but would also require at least one more click from the user so I don'f find this appealing from the UX view.

**Comment by UweSauter** [comment]
Here is an HTML example from the popular (german) SelfHTML [1] documentation that explicitly uses two submit buttons:

```
<h1>IP-Adresse oder Uhrzeit</h1>
<p>Sie können die eingegebenen Daten an ein Script senden. Dabei werden keine Daten gespeichert.</p>
<form action="/extensions/Selfhtml/show-request-params.php" method="post" autocomplete="off">
  <label for="vorname">Vorname</label> 
  <input id="vorname" name="vorname" maxlength="100">
  <label for="name">Name</label> 
  <input id="name" name="name" maxlength="100">
  <button type="submit" name="action" value="0">IP-Adresse</button>
  <button type="submit" name="action" value="1">Uhrzeit</button>
</form>
```
Roughly translated:
`In this example are two submit buttons. Depending on the pressed button the serverside script will receive an "action" parameter with value "0" (for IP-address) or "1" (for time). […]`

[1] https://wiki.selfhtml.org/wiki/HTML/Formulare/button#Formulare_absenden
