### ISSUE TITLE
Stream large video files in static folder

### ISSUE THREAD

**Issue by ZhaoXiangXML** [webpy/webpy#702]
I'm trying to host some video files in the static folder.

It seems my VLC player on phones can only open certain small files, not the large ones. My best guess is that `Transfer-Encoding: chunked` header is required, according to https://webpy.org/cookbook/streaming_large_files.

So is it possible to add headers for static files?

Thanks

**Comment by ZhaoXiangXML** [comment]
I think I've a solution:

```python
old_call = StaticMiddleware.__call__
def call(self, environ, start_response):
    response = old_call(self, environ, start_response)
    response.headers.append(('Transfer-Encoding', 'chunked'))
    return response
StaticMiddleware.__call__ = call
```

**Comment by ZhaoXiangXML** [comment]
However this does not solve my problem, do I need something else to stream large videos in web.py?

**Comment by anandology** [comment]
> (Note: applications and middleware must not apply any kind of Transfer-Encoding to their output, such as chunking or gzipping; as "hop-by-hop" operations, these encodings are the province of the actual web server/gateway. See Other HTTP Features below, for more details.)
-- PEP 3333 -- Python Web Server Gateway Interface v1.0.1

**Comment by ZhaoXiangXML** [comment]
Guess that means I need to install nginx.

Thanks
