### ISSUE TITLE
cgiFieldStorage.makefile is erroneous

### ISSUE THREAD

**Issue by jn0** [webpy/webpy#705]
https://github.com/webpy/webpy/blob/772f5b338de803ec4ef1cda410cfd52482996805/web/webapi.py#L405

The code **always** creates a "binary" stream, while in Python3 (3.7 was in use) it has special AI (via `FieldStorage._binary_file` flag) to select bytes-or-str.

We have triggered this error trying to POST a form/multipart data without `filename` with form date of more than 1000 chars.

Thanks to @igorlidin for help in debugging.

Just return `super().make_file()` instead of creating always-binary temporary file in your code.

**Comment by cclauss** [comment]
Is there a pull request to fix this situation?

**Comment by jn0** [comment]
https://github.com/webpy/webpy/pull/706 created.

It's untested single-line patch (it just forwards the call downward to `cgi.FieldStorage.make_file` discarding [compatibility] parameter).

**Comment by jn0** [comment]
New https://github.com/webpy/webpy/pull/707 PR - with cleanup.

**Comment by jn0** [comment]
If it matters, I've tested the patch with my app.

**Comment by igorlidin** [comment]
I can confirm that multipart/form-data POSTs with form fields which contain more than 1000 chars are broken. This should possibly be considered as a critical bug.

**Comment by cclauss** [comment]
Would it be possible to create a [test](https://github.com/webpy/webpy/tree/master/tests) that fails so we have an executable example of the failure?  When we can get that test to pass this bug will be fixed.  The test will also help us to ensure that we do not have future regressions.  Thanks.

**Comment by jn0** [comment]
Something like
```
yes | head -n 1001 | curl -F data=@- http://where.webpy.live.example.com/path/to/form/page.py
```

**Comment by cclauss** [comment]
Nice @jn0 !!  Would it be possible for you to put that in a pull request so we can make it part of our continuous integration?

**Comment by acmol** [comment]
Meet the same bug.

The cgiFieldStorage class has no need to be existing any more.

**Comment by GJSeason** [comment]
This bug is still not handled. It is sad to see that.

**Comment by tfmorris** [comment]
The `cgi` module is no longer used, so this can probably be closed.

**Comment by cclauss** [comment]
Fixed in
* #773
