### ISSUE TITLE
DBUtils >= v2.0 changes 'import DBUtils' --> 'import dbutils'

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#710]
* https://pypi.org/project/DBUtils
* https://webwareforpython.github.io/DBUtils/changelog.html

In DBUtils < v2.0 must use the syntax `import DBUtils`
In DBUtils >= v2.0 must use the syntax `import dbutils`

Where does this repo have references to `DBUtils`:
https://github.com/webpy/webpy/search?q=dbutils

**Comment by iredmail** [comment]
Feel free to change it. :)

**Comment by cclauss** [comment]
@pycarus Which version of https://pypi.org/project/DBUtils are you using?

**Comment by pycarus** [comment]
@cclauss Python 3.8.5 with DB Utils 3.0.1
