### ISSUE TITLE
I couldn't get datas from mysql by using web.py

### ISSUE THREAD

**Issue by shalun77** [webpy/webpy#721]
<class 'mysql.connector.errors.InternalError'> at /
Unread result found
D:\pythonPath\python\lib\site-packages\mysql\connector\connection.py in handle_unread_result
            raise errors.InternalError("Unread result found") ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\mysql\connector\connection.py in _execute_query
        self.handle_unread_result() ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\mysql\connector\connection.py in commit
        self._execute_query("COMMIT") ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\db.py in commit
            ctx.db.commit() ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\db.py in query
            self.ctx.commit() ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\db.py in select
        return self.query(qout, processed=True) ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonProj\code.py in GET
          zs=db.select('employee') ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\application.py in handle_class
            return tocall(*args) ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\application.py in _delegate
            return handle_class(cls) ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\application.py in handle
        return self._delegate(fn, self.fvars, args) ...
[▶ Local vars](http://127.0.0.1:8080/#)
D:\pythonPath\python\lib\site-packages\web\application.py in process
                    return self.handle() ...
[▶ Local vars](http://127.0.0.1:8080/#)

**Comment by iredmail** [comment]
Please paste your Python code snippet here so that others can help troubleshoot.

**Comment by shalun77** [comment]
#this is test.py
import web
urls = (
    '/', 'index'
)
app = web.application(urls, globals())
render = web.template.render('templates/')
db = web.database(dbn='mysql', host='127.0.0.1', port=3306,
                  db='employee', user='root', pw='root')
class index:
    def GET(self):
        email = db.select('mintest')
        return render.index(email)
if __name__ == "__main__":
    app.run()

#this is index.html
$def with (mintests)
<ul>
$for test in mintests:
    <li id="t$test.id">$test.email</li>
    <li id="t$test.id">$test.NAME</li>
</ul>
#this from db employee
  mysql> select * from mintest;
+----+-----------------+-----------+---------------------+
| id | email           | NAME      | TIME                |
+----+-----------------+-----------+---------------------+
|  1 | 90732041@qq.com | caimouse1 | 2022-02-25 15:44:19 |
+----+-----------------+-----------+---------------------+

**Comment by shalun77** [comment]
i want to get datas from mysql through test.py and show the datas on index.html

**Comment by shalun77** [comment]
i have installed mysql and web.py,python,pycharm and mysql-connector also

**Comment by shalun77** [comment]
Could any friend guide me to do the right code here,,many thanks

**Comment by shalun77** [comment]
(my)  python 3.7.7 , mysql 8.0.12

**Comment by shalun77** [comment]
i'm offline now,i will reply to you immediately, when i get back.
