### ISSUE TITLE
application stops working randomly

### ISSUE THREAD

**Issue by xinthose** [webpy/webpy#734]
I have noticed in production environments (Linux, running 24/7), sometimes my REST service is no longer accessible until I SSH into the machine and restart the application, then it works fine for weeks or months on end.  How can I troubleshoot this?

**Comment by Zemke** [comment]
By looking into the logs.

**Comment by xinthose** [comment]
> By looking into the logs.

I use custom python logging in the application that does not reveal any errors.  Are there system log files I should be checking?

**Comment by xinthose** [comment]
I think I'll use [FastAPI ](https://github.com/tiangolo/fastapi) instead.
