### ISSUE TITLE
Sorry to interupt, when will the new version be released?

### ISSUE THREAD

**Issue by kongyi182** [webpy/webpy#738]

**Comment by cclauss** [comment]
Python 3.11 release candidate 1 https://www.python.org/download/pre-releases is currently being tested on our GitHub Actions.  https://github.com/webpy/webpy/blob/master/.github/workflows/lint_python.yml#L35

Let's do a web.py release just after Py3.11 releases (scheduled for the first days of October 2022).

Before that release, we should automate the release process via the addition of a new GitHub Action based on https://github.com/pypa/gh-action-pypi-publish#readme  Does anyone want to create that PR?

**Comment by kongyi182** [comment]
thank you

**Comment by cclauss** [comment]
Let's leave this open until we have made our release.

**Comment by kangxy** [comment]
When will the next version of webpy be released? October 1, 2022 has passed, but the version has not been released. Is there a correct release time? Thank you

**Comment by kangxy** [comment]
> Let's leave this open until we have made our release.
When will the next version of webpy be released? October 1, 2022 has passed, but the version has not been released. Is there a correct release time? Thank you

**Comment by xinthose** [comment]
bump

**Comment by kongyi182** [comment]
0.70 has been released
