### ISSUE TITLE
__del__ method of utils.ThreadedDict

### ISSUE THREAD

**Issue by lovelylain** [webpy/webpy#75]
`__del__` method of utils.ThreadedDict is not needed or should use weakref instead.
Because ThreadedDict._instances has kept a reference of ThreadedDict instances, the `__del__`method will not automatically be called, I also think we should not directly override threading.local's`**del**`.
If we use weakref, it can be like this:

``` python
_instances = set()

def __init__(self):
    ThreadedDict._instances.add(weakref.ref(self, ThreadedDict._instances.remove))

@staticmethod
def clear_all():
    for d in ThreadedDict._instances:
        d().clear()
```

**Comment by iredmail** [comment]
No plan to fix it recently. Feel free to reopen this issue if it's required.
