### ISSUE TITLE
failed to compile the project due to "ImportError"

### ISSUE THREAD

**Issue by Donkeydoky** [webpy/webpy#767]
![image](https://github.com/webpy/webpy/assets/35181162/901e21bf-c156-4c2a-990c-2253fd692c31)
As the graph shows, I just download the repo from the web to my local machine, And open it for a runing test. It fails with this wired error.
Is there anything missing before I run the project？

ps： I have already follow the instructions in the readme.txt to setup.
My machine is a Windows 11 with python 3.11 installed, And I compile it in Pycharm's virtual environment.

**Comment by cclauss** [comment]
Please try running this inside a normal terminal instead of the PyCharm terminal.

**Comment by cclauss** [comment]
@Donkeydoky Can this issue be closed?

**Comment by anandology** [comment]
The files in that directory `web/` are the source files for the python package and they are not meant to be executed directly. This is true for any python package. 

If you would like to run tests, please use `runtests.sh`.

```
$ ./runtests.sh 
============================= test session starts ==============================
platform linux -- Python 3.10.6, pytest-8.2.2, pluggy-1.5.0
rootdir: /home/anand/github/webpy
configfile: pyproject.toml
collected 65 items                                                             

tests/test_application.py ................                               [ 24%]
tests/test_browser.py ...                                                [ 29%]
tests/test_db.py ...........                                             [ 46%]
tests/test_form.py .                                                     [ 47%]
tests/test_form_validators.py .                                          [ 49%]
tests/test_session.py .................                                  [ 75%]
tests/test_template.py ........                                          [ 87%]
tests/test_utils.py .....                                                [ 95%]
tests/test_wsgi.py ...                                                   [100%]

============================= 65 passed in 10.99s ==============================
```
