### ISSUE TITLE
CI failing lint/ruff on unchanged lines

### ISSUE THREAD

**Issue by tfmorris** [webpy/webpy#771]
Ruff is complaining about a whole bunch of unchanged code in this pull request:

https://github.com/webpy/webpy/actions/runs/5742663968

It shouldn't be incumbent upon pull request authors to fix a whole bunch of pre-existing problems

**Comment by cclauss** [comment]
#772

**Comment by tfmorris** [comment]
This was fixed by #772. Not sure why it didn't get closed automatically by Github.
