### ISSUE TITLE
UnicodeDecodeError in 0.70

### ISSUE THREAD

**Issue by scottbarnes** [webpy/webpy#776]
Alas, it appears I missed something in #769, specifically with respect to `utils.py`.

With 0.70 and the Open Library code base, the following occurs when `web.input()` in called when trying to read an attached file, such as a book cover sent via POST as a multipart attachment:
```python
Traceback (most recent call last):
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/application.py", line 276, in process
    return self.handle()
           ^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/application.py", line 267, in handle
    return self._delegate(fn, self.fvars, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/application.py", line 509, in _delegate
    return handle_class(cls)
           ^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/application.py", line 487, in handle_class
    return tocall(*args)
           ^^^^^^^^^^^^^
  File "/openlibrary/openlibrary/coverstore/code.py", line 164, in POST
    i = web.input(
        ^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/webapi.py", line 474, in input
    return storify(out, *requireds, **defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/utils.py", line 184, in storify
    value = getvalue(value)
            ^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/web/utils.py", line 168, in getvalue
    if hasattr(x, "file") and hasattr(x, "value"):
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/openlibrary/.local/lib/python3.11/site-packages/multipart.py", line 425, in value
    return self.raw.decode(self.charset)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

This is likely because the content of `.file` has changed in `multipart`, and `webpy` shouldn't be trying to decode it as unicode when it's a binary file.

Updating `getvalue()` in `utils.py` to the following fixes covers on Open Library, but I still need to compare the output to the `cgi.FieldStorage` equivalent:
```python
def getvalue(x):
    if hasattr(x, 'file') and hasattr(x, 'raw'):                                                                                          
        # There's an attached file; return the content directly.
        return x.file.read()
    elif hasattr(x, 'value'):                
        return unicodify(x.value)                                  
    else:                   
        return unicodify(x)
```

How did I miss this? I think because I did not rebuild the containers with `--no-cache` I had a cached copy of the `covers` container, and because no tests exercised the code in `utils.py`, there was no warning about `cgi` being deprecated, so I falsely thought `cgi` was no longer in use. However, when doing final testing and rebuilding the containers with `--no-cache` I found I was mistaken.

I will look more at this tomorrow and submit hopefully submit a PR.

Note, 0.70 is not yet on PyPi, so people who are using `pip install webpy` are not affected by this currently, as they will still get 0.62: https://pypi.org/project/web.py/#history.

@cclauss

**Comment by cclauss** [comment]
Thanks for your diligent review of v0.70!  Let's NOT release that to PyPI.  ;-)  Slack me if you would like to discuss.
```python
    elif hasattr(x, 'value'):                
        return unicodify(x.value)                                  
    else:                   
        return unicodify(x)

# can be rewritten as -->

    else
        return unicodify(getattr(x, 'value', x
```

**Comment by tfmorris** [comment]
@scottbarnes Please also see my (belated) review comments on #773 and, if possible, resolve the TODOs/FIXMEs, delete commented out dead code, etc.

For those who want to see what the current code mentioned above looks like, here's a quick link: https://github.com/webpy/webpy/blob/a1d2ee4b100985606b69ad6602a46dca4d5c66c1/web/utils.py#L167-L173

It looks to me like the `multipart` module has code to correctly decode the bytes using the given charset, so I wouldn't expect you to have to do anything further to decode it.

https://github.com/defnull/multipart/blob/13af8ab9feeec19ce5a5a44c08d6a1b3fb717885/multipart.py#L425-L425

**Comment by scottbarnes** [comment]
@tfmorris, will do. Thanks!
