### ISSUE TITLE
pip install web.py doesn't install the latest version.

### ISSUE THREAD

**Issue by WhitewaterDave** [webpy/webpy#777]
I tried to install the latest version of web.py but it installed the previous stable version (0.6.2). I checked PYPI and version 0.6.2 is the latest version listed.

`pip install web.py

Collecting web.py
  Downloading web.py-0.62.tar.gz (623 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 623.2/623.2 kB 7.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cheroot (from web.py)
  Downloading cheroot-10.0.0-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: more-itertools>=2.6 in ./venv/lib/python3.11/site-packages (from cheroot->web.py) (10.1.0)
Requirement already satisfied: jaraco.functools in ./venv/lib/python3.11/site-packages (from cheroot->web.py) (3.9.0)
Downloading cheroot-10.0.0-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 14.7 MB/s eta 0:00:00
Building wheels for collected packages: web.py
  Building wheel for web.py (pyproject.toml) ... done
  Created wheel for web.py: filename=web.py-0.62-py3-none-any.whl size=78567 sha256=3dc063bd7b398e7e7bbb1360d02e4798799e09a164bbae530c9793124e788d3d
  Stored in directory: /home/david/.cache/pip/wheels/ce/56/6e/0e399681158faaa4d3b15c5d095b0047357e1c727e6c3fd004
Successfully built web.py
Installing collected packages: cheroot, web.py
Successfully installed cheroot-10.0.0 web.py-0.62

pip install web.py==0.7.0

ERROR: Ignored the following yanked versions: 0.60
ERROR: Could not find a version that satisfies the requirement web.py==0.7.0 (from versions: 0.22, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.40.dev0, 0.40.dev1, 0.40, 0.51, 0.61, 0.62)
ERROR: No matching distribution found for web.py==0.7.0`

Thanks

**Comment by cclauss** [comment]
`pip` installs from https://pypi.org/project/web.py

We did not release to PyPI as discussed at https://github.com/webpy/webpy/issues/776#issuecomment-1765734146

**Comment by WhitewaterDave** [comment]
There was no way for anyone installng it for the first time to know to reference #776. Plus, the install instructions in the README.md file say:

`To install web.py, please run:

python3 -m pip install web.py`

It can be installed by cloning the repo and using `pip install .` which I was able to do. However, someone new to web.py may try to install in using the instructions in the README.md file which will give them the older version. 

Thanks

**Comment by cclauss** [comment]
We do not want our users to install software with a known bug.  We will update PyPI when we have a stable release that we want to publish.  Until then, PyPI holds the correct version of this software.

**Comment by WhitewaterDave** [comment]
This is almost a year old and still not fixed. 
This issue associated with this

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte`

I've had this issue with other projects. It's possible that the file causing the error is encoded as UTF-16 instead of UTF-8? You gould get this error. The file can be converted to UTF-8 on Linux using: 

`iconv -f UTF-16LE -t UTF-8 infile > outfile`

This is Linux/FreeBSD/macOS. Just a suggestion.
