### ISSUE TITLE
Maintainance of the project

### ISSUE THREAD

**Issue by cclauss** [webpy/webpy#789]
Dear @anandology and @iredmail,

I no longer use `web.py` in my projects but I care that it remains in good shape to serve its audience.

I would therefore recommend that you add at least one of the following people as a project maintainer:
@scottbarnes, @cdrini, @mekarpeles, @tfmorris

I have worked with all of them on the https://github.com/internetarchive/openlibrary codebase which uses `web.py` and I highly recommend them all as diligent and skilled software engineers.

On this repo:
* https://github.com/webpy/webpy/pulls/cdrini
* https://github.com/webpy/webpy/pulls/scottbarnes
* https://github.com/webpy/webpy/pulls/tfmorris

**Comment by tfmorris** [comment]
Thanks for the vote of confidence @cclauss, but my days with OpenLibrary were long ago, so I'd suggest at least one of the other three as having the most direct interest in the continued operation of web.py

**Comment by iredmail** [comment]
I'm moving to Golang, not qualified as webpy maintainer anymore. Please help remove me from maintainer team. :)

Appreciate for all the great works done by @anandology  and @cclauss

**Comment by anandology** [comment]
Dear @iredmail and @cclauss, thank you so much for maintaining web.py so
well so far. I've been completely off the radar and both of you have done
a great job to keep things moving. Thank you so much.

@tfmorris thank you for your contributions to web.py.

@ccaluss your recommendations for project maintainer looks good to me.
Thanks!

@scottbarnes, @cdrini and @mek we are looking for a new maintainers for
web.py. please reply to thread if you would be interested.

**Comment by cclauss** [comment]
@mekarpeles

**Comment by mekarpeles** [comment]
Happy to co-maintain.

**Comment by anandology** [comment]
Thanks @scottbarnes and @mek. I'll get back to you soon with access.

@iredmail and @cclauss, it would be great if you could share the current
process that you follow for reviewing PRs, making releases etc, and
anything else that needs to kept in mind.

**Comment by cclauss** [comment]
## CAUTION: It is @mekarpeles, not @mek.  My mistake.

**Comment by anandology** [comment]
Apologies for going silent on this thread. I've invited @mekarpeles and @scottbarnes to the team. They should get commit access once they accept the invitation. 

I guess it would be good to clean up the pending PRs and issues and make the next release so that both @mekarpeles and @scottbarnes (and also me) knows what goes in making a new release etc. @cclauss and @iredmail I think your inputs would be greatly helpful for this release.

**Comment by mekarpeles** [comment]
I'll do my best to support @scottbarnes in keeping a pulse on things in the meantime in addressing high urgency issues and reviewing PRs. Thank you!
